declare namespace org {
    namespace GNOME {
        namespace Accessibility {
            interface AtkSignal {
                TEXT_CARET_MOVED: int
                TEXT_PROPERTY_CHANGED_INSERT: int
                TEXT_PROPERTY_CHANGED_DELETE: int
                TEXT_PROPERTY_CHANGED_REPLACE: int
                OBJECT_CHILDREN_CHANGED_ADD: int
                OBJECT_CHILDREN_CHANGED_REMOVE: int
                OBJECT_ACTIVE_DESCENDANT_CHANGED: int
                OBJECT_SELECTION_CHANGED: int
                OBJECT_VISIBLE_DATA_CHANGED: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_ACTIONS: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_VALUE: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_DESCRIPTION: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_NAME: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_HYPERTEXT_OFFSET: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_TABLE_CAPTION: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_TABLE_SUMMARY: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_TABLE_COLUMN_HEADER: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_TABLE_COLUMN_DESCRIPTION: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_TABLE_ROW_HEADER: int
                OBJECT_PROPERTY_CHANGE_ACCESSIBLE_TABLE_ROW_DESCRIPTION: int
                TABLE_MODEL_CHANGED: int
                TEXT_PROPERTY_CHANGED: int
            }
        }
    }
}