declare namespace javax {
  namespace imageio {
    namespace plugins {
      namespace tiff {

        class BaselineTIFFTagSet extends javax.imageio.plugins.tiff.TIFFTagSet {
          public static readonly TAG_NEW_SUBFILE_TYPE: int
          public static readonly NEW_SUBFILE_TYPE_REDUCED_RESOLUTION: int
          public static readonly NEW_SUBFILE_TYPE_SINGLE_PAGE: int
          public static readonly NEW_SUBFILE_TYPE_TRANSPARENCY: int
          public static readonly TAG_SUBFILE_TYPE: int
          public static readonly SUBFILE_TYPE_FULL_RESOLUTION: int
          public static readonly SUBFILE_TYPE_REDUCED_RESOLUTION: int
          public static readonly SUBFILE_TYPE_SINGLE_PAGE: int
          public static readonly TAG_IMAGE_WIDTH: int
          public static readonly TAG_IMAGE_LENGTH: int
          public static readonly TAG_BITS_PER_SAMPLE: int
          public static readonly TAG_COMPRESSION: int
          public static readonly COMPRESSION_NONE: int
          public static readonly COMPRESSION_CCITT_RLE: int
          public static readonly COMPRESSION_CCITT_T_4: int
          public static readonly COMPRESSION_CCITT_T_6: int
          public static readonly COMPRESSION_LZW: int
          public static readonly COMPRESSION_OLD_JPEG: int
          public static readonly COMPRESSION_JPEG: int
          public static readonly COMPRESSION_ZLIB: int
          public static readonly COMPRESSION_PACKBITS: int
          public static readonly COMPRESSION_DEFLATE: int
          public static readonly TAG_PHOTOMETRIC_INTERPRETATION: int
          public static readonly PHOTOMETRIC_INTERPRETATION_WHITE_IS_ZERO: int
          public static readonly PHOTOMETRIC_INTERPRETATION_BLACK_IS_ZERO: int
          public static readonly PHOTOMETRIC_INTERPRETATION_RGB: int
          public static readonly PHOTOMETRIC_INTERPRETATION_PALETTE_COLOR: int
          public static readonly PHOTOMETRIC_INTERPRETATION_TRANSPARENCY_MASK: int
          public static readonly PHOTOMETRIC_INTERPRETATION_CMYK: int
          public static readonly PHOTOMETRIC_INTERPRETATION_Y_CB_CR: int
          public static readonly PHOTOMETRIC_INTERPRETATION_CIELAB: int
          public static readonly PHOTOMETRIC_INTERPRETATION_ICCLAB: int
          public static readonly TAG_THRESHHOLDING: int
          public static readonly THRESHHOLDING_NONE: int
          public static readonly THRESHHOLDING_ORDERED_DITHER: int
          public static readonly THRESHHOLDING_RANDOMIZED_DITHER: int
          public static readonly TAG_CELL_WIDTH: int
          public static readonly TAG_CELL_LENGTH: int
          public static readonly TAG_FILL_ORDER: int
          public static readonly FILL_ORDER_LEFT_TO_RIGHT: int
          public static readonly FILL_ORDER_RIGHT_TO_LEFT: int
          public static readonly TAG_DOCUMENT_NAME: int
          public static readonly TAG_IMAGE_DESCRIPTION: int
          public static readonly TAG_MAKE: int
          public static readonly TAG_MODEL: int
          public static readonly TAG_STRIP_OFFSETS: int
          public static readonly TAG_ORIENTATION: int
          public static readonly ORIENTATION_ROW_0_TOP_COLUMN_0_LEFT: int
          public static readonly ORIENTATION_ROW_0_TOP_COLUMN_0_RIGHT: int
          public static readonly ORIENTATION_ROW_0_BOTTOM_COLUMN_0_RIGHT: int
          public static readonly ORIENTATION_ROW_0_BOTTOM_COLUMN_0_LEFT: int
          public static readonly ORIENTATION_ROW_0_LEFT_COLUMN_0_TOP: int
          public static readonly ORIENTATION_ROW_0_RIGHT_COLUMN_0_TOP: int
          public static readonly ORIENTATION_ROW_0_RIGHT_COLUMN_0_BOTTOM: int
          public static readonly ORIENTATION_ROW_0_LEFT_COLUMN_0_BOTTOM: int
          public static readonly TAG_SAMPLES_PER_PIXEL: int
          public static readonly TAG_ROWS_PER_STRIP: int
          public static readonly TAG_STRIP_BYTE_COUNTS: int
          public static readonly TAG_MIN_SAMPLE_VALUE: int
          public static readonly TAG_MAX_SAMPLE_VALUE: int
          public static readonly TAG_X_RESOLUTION: int
          public static readonly TAG_Y_RESOLUTION: int
          public static readonly TAG_PLANAR_CONFIGURATION: int
          public static readonly PLANAR_CONFIGURATION_CHUNKY: int
          public static readonly PLANAR_CONFIGURATION_PLANAR: int
          public static readonly TAG_PAGE_NAME: int
          public static readonly TAG_X_POSITION: int
          public static readonly TAG_Y_POSITION: int
          public static readonly TAG_FREE_OFFSETS: int
          public static readonly TAG_FREE_BYTE_COUNTS: int
          public static readonly TAG_GRAY_RESPONSE_UNIT: int
          public static readonly GRAY_RESPONSE_UNIT_TENTHS: int
          public static readonly GRAY_RESPONSE_UNIT_HUNDREDTHS: int
          public static readonly GRAY_RESPONSE_UNIT_THOUSANDTHS: int
          public static readonly GRAY_RESPONSE_UNIT_TEN_THOUSANDTHS: int
          public static readonly GRAY_RESPONSE_UNIT_HUNDRED_THOUSANDTHS: int
          public static readonly TAG_GRAY_RESPONSE_CURVE: int
          public static readonly TAG_T4_OPTIONS: int
          public static readonly T4_OPTIONS_2D_CODING: int
          public static readonly T4_OPTIONS_UNCOMPRESSED: int
          public static readonly T4_OPTIONS_EOL_BYTE_ALIGNED: int
          public static readonly TAG_T6_OPTIONS: int
          public static readonly T6_OPTIONS_UNCOMPRESSED: int
          public static readonly TAG_RESOLUTION_UNIT: int
          public static readonly RESOLUTION_UNIT_NONE: int
          public static readonly RESOLUTION_UNIT_INCH: int
          public static readonly RESOLUTION_UNIT_CENTIMETER: int
          public static readonly TAG_PAGE_NUMBER: int
          public static readonly TAG_TRANSFER_FUNCTION: int
          public static readonly TAG_SOFTWARE: int
          public static readonly TAG_DATE_TIME: int
          public static readonly TAG_ARTIST: int
          public static readonly TAG_HOST_COMPUTER: int
          public static readonly TAG_PREDICTOR: int
          public static readonly PREDICTOR_NONE: int
          public static readonly PREDICTOR_HORIZONTAL_DIFFERENCING: int
          public static readonly TAG_WHITE_POINT: int
          public static readonly TAG_PRIMARY_CHROMATICITES: int
          public static readonly TAG_COLOR_MAP: int
          public static readonly TAG_HALFTONE_HINTS: int
          public static readonly TAG_TILE_WIDTH: int
          public static readonly TAG_TILE_LENGTH: int
          public static readonly TAG_TILE_OFFSETS: int
          public static readonly TAG_TILE_BYTE_COUNTS: int
          public static readonly TAG_INK_SET: int
          public static readonly INK_SET_CMYK: int
          public static readonly INK_SET_NOT_CMYK: int
          public static readonly TAG_INK_NAMES: int
          public static readonly TAG_NUMBER_OF_INKS: int
          public static readonly TAG_DOT_RANGE: int
          public static readonly TAG_TARGET_PRINTER: int
          public static readonly TAG_EXTRA_SAMPLES: int
          public static readonly EXTRA_SAMPLES_UNSPECIFIED: int
          public static readonly EXTRA_SAMPLES_ASSOCIATED_ALPHA: int
          public static readonly EXTRA_SAMPLES_UNASSOCIATED_ALPHA: int
          public static readonly TAG_SAMPLE_FORMAT: int
          public static readonly SAMPLE_FORMAT_UNSIGNED_INTEGER: int
          public static readonly SAMPLE_FORMAT_SIGNED_INTEGER: int
          public static readonly SAMPLE_FORMAT_FLOATING_POINT: int
          public static readonly SAMPLE_FORMAT_UNDEFINED: int
          public static readonly TAG_S_MIN_SAMPLE_VALUE: int
          public static readonly TAG_S_MAX_SAMPLE_VALUE: int
          public static readonly TAG_TRANSFER_RANGE: int
          public static readonly TAG_JPEG_TABLES: int
          public static readonly TAG_JPEG_PROC: int
          public static readonly JPEG_PROC_BASELINE: int
          public static readonly JPEG_PROC_LOSSLESS: int
          public static readonly TAG_JPEG_INTERCHANGE_FORMAT: int
          public static readonly TAG_JPEG_INTERCHANGE_FORMAT_LENGTH: int
          public static readonly TAG_JPEG_RESTART_INTERVAL: int
          public static readonly TAG_JPEG_LOSSLESS_PREDICTORS: int
          public static readonly TAG_JPEG_POINT_TRANSFORMS: int
          public static readonly TAG_JPEG_Q_TABLES: int
          public static readonly TAG_JPEG_DC_TABLES: int
          public static readonly TAG_JPEG_AC_TABLES: int
          public static readonly TAG_Y_CB_CR_COEFFICIENTS: int
          public static readonly TAG_Y_CB_CR_SUBSAMPLING: int
          public static readonly TAG_Y_CB_CR_POSITIONING: int
          public static readonly Y_CB_CR_POSITIONING_CENTERED: int
          public static readonly Y_CB_CR_POSITIONING_COSITED: int
          public static readonly TAG_REFERENCE_BLACK_WHITE: int
          public static readonly TAG_COPYRIGHT: int
          public static readonly TAG_ICC_PROFILE: int
          public static getInstance(): javax.imageio.plugins.tiff.BaselineTIFFTagSet
        }

      }
    }
  }
}
