declare namespace java {
  namespace awt {

    class PageAttributes$MediaType extends java.awt.AttributeValue {
      public static readonly ISO_4A0: java.awt.PageAttributes$MediaType
      public static readonly ISO_2A0: java.awt.PageAttributes$MediaType
      public static readonly ISO_A0: java.awt.PageAttributes$MediaType
      public static readonly ISO_A1: java.awt.PageAttributes$MediaType
      public static readonly ISO_A2: java.awt.PageAttributes$MediaType
      public static readonly ISO_A3: java.awt.PageAttributes$MediaType
      public static readonly ISO_A4: java.awt.PageAttributes$MediaType
      public static readonly ISO_A5: java.awt.PageAttributes$MediaType
      public static readonly ISO_A6: java.awt.PageAttributes$MediaType
      public static readonly ISO_A7: java.awt.PageAttributes$MediaType
      public static readonly ISO_A8: java.awt.PageAttributes$MediaType
      public static readonly ISO_A9: java.awt.PageAttributes$MediaType
      public static readonly ISO_A10: java.awt.PageAttributes$MediaType
      public static readonly ISO_B0: java.awt.PageAttributes$MediaType
      public static readonly ISO_B1: java.awt.PageAttributes$MediaType
      public static readonly ISO_B2: java.awt.PageAttributes$MediaType
      public static readonly ISO_B3: java.awt.PageAttributes$MediaType
      public static readonly ISO_B4: java.awt.PageAttributes$MediaType
      public static readonly ISO_B5: java.awt.PageAttributes$MediaType
      public static readonly ISO_B6: java.awt.PageAttributes$MediaType
      public static readonly ISO_B7: java.awt.PageAttributes$MediaType
      public static readonly ISO_B8: java.awt.PageAttributes$MediaType
      public static readonly ISO_B9: java.awt.PageAttributes$MediaType
      public static readonly ISO_B10: java.awt.PageAttributes$MediaType
      public static readonly JIS_B0: java.awt.PageAttributes$MediaType
      public static readonly JIS_B1: java.awt.PageAttributes$MediaType
      public static readonly JIS_B2: java.awt.PageAttributes$MediaType
      public static readonly JIS_B3: java.awt.PageAttributes$MediaType
      public static readonly JIS_B4: java.awt.PageAttributes$MediaType
      public static readonly JIS_B5: java.awt.PageAttributes$MediaType
      public static readonly JIS_B6: java.awt.PageAttributes$MediaType
      public static readonly JIS_B7: java.awt.PageAttributes$MediaType
      public static readonly JIS_B8: java.awt.PageAttributes$MediaType
      public static readonly JIS_B9: java.awt.PageAttributes$MediaType
      public static readonly JIS_B10: java.awt.PageAttributes$MediaType
      public static readonly ISO_C0: java.awt.PageAttributes$MediaType
      public static readonly ISO_C1: java.awt.PageAttributes$MediaType
      public static readonly ISO_C2: java.awt.PageAttributes$MediaType
      public static readonly ISO_C3: java.awt.PageAttributes$MediaType
      public static readonly ISO_C4: java.awt.PageAttributes$MediaType
      public static readonly ISO_C5: java.awt.PageAttributes$MediaType
      public static readonly ISO_C6: java.awt.PageAttributes$MediaType
      public static readonly ISO_C7: java.awt.PageAttributes$MediaType
      public static readonly ISO_C8: java.awt.PageAttributes$MediaType
      public static readonly ISO_C9: java.awt.PageAttributes$MediaType
      public static readonly ISO_C10: java.awt.PageAttributes$MediaType
      public static readonly ISO_DESIGNATED_LONG: java.awt.PageAttributes$MediaType
      public static readonly EXECUTIVE: java.awt.PageAttributes$MediaType
      public static readonly FOLIO: java.awt.PageAttributes$MediaType
      public static readonly INVOICE: java.awt.PageAttributes$MediaType
      public static readonly LEDGER: java.awt.PageAttributes$MediaType
      public static readonly NA_LETTER: java.awt.PageAttributes$MediaType
      public static readonly NA_LEGAL: java.awt.PageAttributes$MediaType
      public static readonly QUARTO: java.awt.PageAttributes$MediaType
      public static readonly A: java.awt.PageAttributes$MediaType
      public static readonly B: java.awt.PageAttributes$MediaType
      public static readonly C: java.awt.PageAttributes$MediaType
      public static readonly D: java.awt.PageAttributes$MediaType
      public static readonly E: java.awt.PageAttributes$MediaType
      public static readonly NA_10X15_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_10X14_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_10X13_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_9X12_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_9X11_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_7X9_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_6X9_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_NUMBER_9_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_NUMBER_10_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_NUMBER_11_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_NUMBER_12_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly NA_NUMBER_14_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly INVITE_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly ITALY_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly MONARCH_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly PERSONAL_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly A0: java.awt.PageAttributes$MediaType
      public static readonly A1: java.awt.PageAttributes$MediaType
      public static readonly A2: java.awt.PageAttributes$MediaType
      public static readonly A3: java.awt.PageAttributes$MediaType
      public static readonly A4: java.awt.PageAttributes$MediaType
      public static readonly A5: java.awt.PageAttributes$MediaType
      public static readonly A6: java.awt.PageAttributes$MediaType
      public static readonly A7: java.awt.PageAttributes$MediaType
      public static readonly A8: java.awt.PageAttributes$MediaType
      public static readonly A9: java.awt.PageAttributes$MediaType
      public static readonly A10: java.awt.PageAttributes$MediaType
      public static readonly B0: java.awt.PageAttributes$MediaType
      public static readonly B1: java.awt.PageAttributes$MediaType
      public static readonly B2: java.awt.PageAttributes$MediaType
      public static readonly B3: java.awt.PageAttributes$MediaType
      public static readonly B4: java.awt.PageAttributes$MediaType
      public static readonly ISO_B4_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly B5: java.awt.PageAttributes$MediaType
      public static readonly ISO_B5_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly B6: java.awt.PageAttributes$MediaType
      public static readonly B7: java.awt.PageAttributes$MediaType
      public static readonly B8: java.awt.PageAttributes$MediaType
      public static readonly B9: java.awt.PageAttributes$MediaType
      public static readonly B10: java.awt.PageAttributes$MediaType
      public static readonly C0: java.awt.PageAttributes$MediaType
      public static readonly ISO_C0_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly C1: java.awt.PageAttributes$MediaType
      public static readonly ISO_C1_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly C2: java.awt.PageAttributes$MediaType
      public static readonly ISO_C2_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly C3: java.awt.PageAttributes$MediaType
      public static readonly ISO_C3_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly C4: java.awt.PageAttributes$MediaType
      public static readonly ISO_C4_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly C5: java.awt.PageAttributes$MediaType
      public static readonly ISO_C5_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly C6: java.awt.PageAttributes$MediaType
      public static readonly ISO_C6_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly C7: java.awt.PageAttributes$MediaType
      public static readonly ISO_C7_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly C8: java.awt.PageAttributes$MediaType
      public static readonly ISO_C8_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly C9: java.awt.PageAttributes$MediaType
      public static readonly ISO_C9_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly C10: java.awt.PageAttributes$MediaType
      public static readonly ISO_C10_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly ISO_DESIGNATED_LONG_ENVELOPE: java.awt.PageAttributes$MediaType
      public static readonly STATEMENT: java.awt.PageAttributes$MediaType
      public static readonly TABLOID: java.awt.PageAttributes$MediaType
      public static readonly LETTER: java.awt.PageAttributes$MediaType
      public static readonly NOTE: java.awt.PageAttributes$MediaType
      public static readonly LEGAL: java.awt.PageAttributes$MediaType
      public static readonly ENV_10X15: java.awt.PageAttributes$MediaType
      public static readonly ENV_10X14: java.awt.PageAttributes$MediaType
      public static readonly ENV_10X13: java.awt.PageAttributes$MediaType
      public static readonly ENV_9X12: java.awt.PageAttributes$MediaType
      public static readonly ENV_9X11: java.awt.PageAttributes$MediaType
      public static readonly ENV_7X9: java.awt.PageAttributes$MediaType
      public static readonly ENV_6X9: java.awt.PageAttributes$MediaType
      public static readonly ENV_9: java.awt.PageAttributes$MediaType
      public static readonly ENV_10: java.awt.PageAttributes$MediaType
      public static readonly ENV_11: java.awt.PageAttributes$MediaType
      public static readonly ENV_12: java.awt.PageAttributes$MediaType
      public static readonly ENV_14: java.awt.PageAttributes$MediaType
      public static readonly ENV_INVITE: java.awt.PageAttributes$MediaType
      public static readonly ENV_ITALY: java.awt.PageAttributes$MediaType
      public static readonly ENV_MONARCH: java.awt.PageAttributes$MediaType
      public static readonly ENV_PERSONAL: java.awt.PageAttributes$MediaType
      public static readonly INVITE: java.awt.PageAttributes$MediaType
      public static readonly ITALY: java.awt.PageAttributes$MediaType
      public static readonly MONARCH: java.awt.PageAttributes$MediaType
      public static readonly PERSONAL: java.awt.PageAttributes$MediaType
      public toString(): java.lang.String
      public hashCode(): int
    }

  }
}
