declare namespace javax {
  namespace imageio {
    namespace plugins {
      namespace tiff {

        class ExifTIFFTagSet extends javax.imageio.plugins.tiff.TIFFTagSet {
          public static readonly TAG_GPS_INFO_IFD_POINTER: int
          public static readonly TAG_INTEROPERABILITY_IFD_POINTER: int
          public static readonly TAG_EXIF_VERSION: int
          public static readonly EXIF_VERSION_2_1: java.lang.String
          public static readonly EXIF_VERSION_2_2: java.lang.String
          public static readonly TAG_FLASHPIX_VERSION: int
          public static readonly TAG_COLOR_SPACE: int
          public static readonly COLOR_SPACE_SRGB: int
          public static readonly COLOR_SPACE_UNCALIBRATED: int
          public static readonly TAG_COMPONENTS_CONFIGURATION: int
          public static readonly COMPONENTS_CONFIGURATION_DOES_NOT_EXIST: int
          public static readonly COMPONENTS_CONFIGURATION_Y: int
          public static readonly COMPONENTS_CONFIGURATION_CB: int
          public static readonly COMPONENTS_CONFIGURATION_CR: int
          public static readonly COMPONENTS_CONFIGURATION_R: int
          public static readonly COMPONENTS_CONFIGURATION_G: int
          public static readonly COMPONENTS_CONFIGURATION_B: int
          public static readonly TAG_COMPRESSED_BITS_PER_PIXEL: int
          public static readonly TAG_PIXEL_X_DIMENSION: int
          public static readonly TAG_PIXEL_Y_DIMENSION: int
          public static readonly TAG_MAKER_NOTE: int
          public static readonly TAG_MARKER_NOTE: int
          public static readonly TAG_USER_COMMENT: int
          public static readonly TAG_RELATED_SOUND_FILE: int
          public static readonly TAG_DATE_TIME_ORIGINAL: int
          public static readonly TAG_DATE_TIME_DIGITIZED: int
          public static readonly TAG_SUB_SEC_TIME: int
          public static readonly TAG_SUB_SEC_TIME_ORIGINAL: int
          public static readonly TAG_SUB_SEC_TIME_DIGITIZED: int
          public static readonly TAG_EXPOSURE_TIME: int
          public static readonly TAG_F_NUMBER: int
          public static readonly TAG_EXPOSURE_PROGRAM: int
          public static readonly EXPOSURE_PROGRAM_NOT_DEFINED: int
          public static readonly EXPOSURE_PROGRAM_MANUAL: int
          public static readonly EXPOSURE_PROGRAM_NORMAL_PROGRAM: int
          public static readonly EXPOSURE_PROGRAM_APERTURE_PRIORITY: int
          public static readonly EXPOSURE_PROGRAM_SHUTTER_PRIORITY: int
          public static readonly EXPOSURE_PROGRAM_CREATIVE_PROGRAM: int
          public static readonly EXPOSURE_PROGRAM_ACTION_PROGRAM: int
          public static readonly EXPOSURE_PROGRAM_PORTRAIT_MODE: int
          public static readonly EXPOSURE_PROGRAM_LANDSCAPE_MODE: int
          public static readonly EXPOSURE_PROGRAM_MAX_RESERVED: int
          public static readonly TAG_SPECTRAL_SENSITIVITY: int
          public static readonly TAG_ISO_SPEED_RATINGS: int
          public static readonly TAG_OECF: int
          public static readonly TAG_SHUTTER_SPEED_VALUE: int
          public static readonly TAG_APERTURE_VALUE: int
          public static readonly TAG_BRIGHTNESS_VALUE: int
          public static readonly TAG_EXPOSURE_BIAS_VALUE: int
          public static readonly TAG_MAX_APERTURE_VALUE: int
          public static readonly TAG_SUBJECT_DISTANCE: int
          public static readonly TAG_METERING_MODE: int
          public static readonly METERING_MODE_UNKNOWN: int
          public static readonly METERING_MODE_AVERAGE: int
          public static readonly METERING_MODE_CENTER_WEIGHTED_AVERAGE: int
          public static readonly METERING_MODE_SPOT: int
          public static readonly METERING_MODE_MULTI_SPOT: int
          public static readonly METERING_MODE_PATTERN: int
          public static readonly METERING_MODE_PARTIAL: int
          public static readonly METERING_MODE_MIN_RESERVED: int
          public static readonly METERING_MODE_MAX_RESERVED: int
          public static readonly METERING_MODE_OTHER: int
          public static readonly TAG_LIGHT_SOURCE: int
          public static readonly LIGHT_SOURCE_UNKNOWN: int
          public static readonly LIGHT_SOURCE_DAYLIGHT: int
          public static readonly LIGHT_SOURCE_FLUORESCENT: int
          public static readonly LIGHT_SOURCE_TUNGSTEN: int
          public static readonly LIGHT_SOURCE_FLASH: int
          public static readonly LIGHT_SOURCE_FINE_WEATHER: int
          public static readonly LIGHT_SOURCE_CLOUDY_WEATHER: int
          public static readonly LIGHT_SOURCE_SHADE: int
          public static readonly LIGHT_SOURCE_DAYLIGHT_FLUORESCENT: int
          public static readonly LIGHT_SOURCE_DAY_WHITE_FLUORESCENT: int
          public static readonly LIGHT_SOURCE_COOL_WHITE_FLUORESCENT: int
          public static readonly LIGHT_SOURCE_WHITE_FLUORESCENT: int
          public static readonly LIGHT_SOURCE_STANDARD_LIGHT_A: int
          public static readonly LIGHT_SOURCE_STANDARD_LIGHT_B: int
          public static readonly LIGHT_SOURCE_STANDARD_LIGHT_C: int
          public static readonly LIGHT_SOURCE_D55: int
          public static readonly LIGHT_SOURCE_D65: int
          public static readonly LIGHT_SOURCE_D75: int
          public static readonly LIGHT_SOURCE_D50: int
          public static readonly LIGHT_SOURCE_ISO_STUDIO_TUNGSTEN: int
          public static readonly LIGHT_SOURCE_OTHER: int
          public static readonly TAG_FLASH: int
          public static readonly FLASH_DID_NOT_FIRE: int
          public static readonly FLASH_FIRED: int
          public static readonly FLASH_STROBE_RETURN_LIGHT_NOT_DETECTED: int
          public static readonly FLASH_STROBE_RETURN_LIGHT_DETECTED: int
          public static readonly FLASH_MASK_FIRED: int
          public static readonly FLASH_MASK_RETURN_NOT_DETECTED: int
          public static readonly FLASH_MASK_RETURN_DETECTED: int
          public static readonly FLASH_MASK_MODE_FLASH_FIRING: int
          public static readonly FLASH_MASK_MODE_FLASH_SUPPRESSION: int
          public static readonly FLASH_MASK_MODE_AUTO: int
          public static readonly FLASH_MASK_FUNCTION_NOT_PRESENT: int
          public static readonly FLASH_MASK_RED_EYE_REDUCTION: int
          public static readonly TAG_FOCAL_LENGTH: int
          public static readonly TAG_SUBJECT_AREA: int
          public static readonly TAG_FLASH_ENERGY: int
          public static readonly TAG_SPATIAL_FREQUENCY_RESPONSE: int
          public static readonly TAG_FOCAL_PLANE_X_RESOLUTION: int
          public static readonly TAG_FOCAL_PLANE_Y_RESOLUTION: int
          public static readonly TAG_FOCAL_PLANE_RESOLUTION_UNIT: int
          public static readonly FOCAL_PLANE_RESOLUTION_UNIT_NONE: int
          public static readonly FOCAL_PLANE_RESOLUTION_UNIT_INCH: int
          public static readonly FOCAL_PLANE_RESOLUTION_UNIT_CENTIMETER: int
          public static readonly TAG_SUBJECT_LOCATION: int
          public static readonly TAG_EXPOSURE_INDEX: int
          public static readonly TAG_SENSING_METHOD: int
          public static readonly SENSING_METHOD_NOT_DEFINED: int
          public static readonly SENSING_METHOD_ONE_CHIP_COLOR_AREA_SENSOR: int
          public static readonly SENSING_METHOD_TWO_CHIP_COLOR_AREA_SENSOR: int
          public static readonly SENSING_METHOD_THREE_CHIP_COLOR_AREA_SENSOR: int
          public static readonly SENSING_METHOD_COLOR_SEQUENTIAL_AREA_SENSOR: int
          public static readonly SENSING_METHOD_TRILINEAR_SENSOR: int
          public static readonly SENSING_METHOD_COLOR_SEQUENTIAL_LINEAR_SENSOR: int
          public static readonly TAG_FILE_SOURCE: int
          public static readonly FILE_SOURCE_DSC: int
          public static readonly TAG_SCENE_TYPE: int
          public static readonly SCENE_TYPE_DSC: int
          public static readonly TAG_CFA_PATTERN: int
          public static readonly TAG_CUSTOM_RENDERED: int
          public static readonly CUSTOM_RENDERED_NORMAL: int
          public static readonly CUSTOM_RENDERED_CUSTOM: int
          public static readonly TAG_EXPOSURE_MODE: int
          public static readonly EXPOSURE_MODE_AUTO_EXPOSURE: int
          public static readonly EXPOSURE_MODE_MANUAL_EXPOSURE: int
          public static readonly EXPOSURE_MODE_AUTO_BRACKET: int
          public static readonly TAG_WHITE_BALANCE: int
          public static readonly WHITE_BALANCE_AUTO: int
          public static readonly WHITE_BALANCE_MANUAL: int
          public static readonly TAG_DIGITAL_ZOOM_RATIO: int
          public static readonly TAG_FOCAL_LENGTH_IN_35MM_FILM: int
          public static readonly TAG_SCENE_CAPTURE_TYPE: int
          public static readonly SCENE_CAPTURE_TYPE_STANDARD: int
          public static readonly SCENE_CAPTURE_TYPE_LANDSCAPE: int
          public static readonly SCENE_CAPTURE_TYPE_PORTRAIT: int
          public static readonly SCENE_CAPTURE_TYPE_NIGHT_SCENE: int
          public static readonly TAG_GAIN_CONTROL: int
          public static readonly GAIN_CONTROL_NONE: int
          public static readonly GAIN_CONTROL_LOW_GAIN_UP: int
          public static readonly GAIN_CONTROL_HIGH_GAIN_UP: int
          public static readonly GAIN_CONTROL_LOW_GAIN_DOWN: int
          public static readonly GAIN_CONTROL_HIGH_GAIN_DOWN: int
          public static readonly TAG_CONTRAST: int
          public static readonly CONTRAST_NORMAL: int
          public static readonly CONTRAST_SOFT: int
          public static readonly CONTRAST_HARD: int
          public static readonly TAG_SATURATION: int
          public static readonly SATURATION_NORMAL: int
          public static readonly SATURATION_LOW: int
          public static readonly SATURATION_HIGH: int
          public static readonly TAG_SHARPNESS: int
          public static readonly SHARPNESS_NORMAL: int
          public static readonly SHARPNESS_SOFT: int
          public static readonly SHARPNESS_HARD: int
          public static readonly TAG_DEVICE_SETTING_DESCRIPTION: int
          public static readonly TAG_SUBJECT_DISTANCE_RANGE: int
          public static readonly SUBJECT_DISTANCE_RANGE_UNKNOWN: int
          public static readonly SUBJECT_DISTANCE_RANGE_MACRO: int
          public static readonly SUBJECT_DISTANCE_RANGE_CLOSE_VIEW: int
          public static readonly SUBJECT_DISTANCE_RANGE_DISTANT_VIEW: int
          public static readonly TAG_IMAGE_UNIQUE_ID: int
          public static getInstance(): javax.imageio.plugins.tiff.ExifTIFFTagSet
        }

      }
    }
  }
}
