declare namespace com {
    namespace sun {
        namespace corba {
            namespace se {
                namespace impl {
                    namespace orbutil {
                        class ORBConstants {
                            public static readonly STRINGIFY_PREFIX: string
                            public static readonly NEO_FIRST_SERVICE_CONTEXT: int
                            public static readonly NUM_NEO_SERVICE_CONTEXTS: int
                            public static readonly TAG_ORB_VERSION: int
                            public static readonly SUN_TAGGED_COMPONENT_ID_BASE: int
                            public static readonly SUN_SERVICE_CONTEXT_ID_BASE: int
                            public static readonly TAG_CONTAINER_ID: int
                            public static readonly TAG_REQUEST_PARTITIONING_ID: int
                            public static readonly TAG_JAVA_SERIALIZATION_ID: int
                            public static readonly CONTAINER_ID_SERVICE_CONTEXT: int
                            public static readonly SERVANT_CACHING_POLICY: int
                            public static readonly ZERO_PORT_POLICY: int
                            public static readonly COPY_OBJECT_POLICY: int
                            public static readonly REQUEST_PARTITIONING_POLICY: int
                            public static readonly TOA_SCID: int
                            public static readonly DEFAULT_SCID: int
                            public static readonly FIRST_POA_SCID: int
                            public static readonly MAX_POA_SCID: int
                            public static readonly TRANSIENT_SCID: int
                            public static readonly PERSISTENT_SCID: int
                            public static readonly SC_TRANSIENT_SCID: int
                            public static readonly SC_PERSISTENT_SCID: int
                            public static readonly IISC_TRANSIENT_SCID: int
                            public static readonly IISC_PERSISTENT_SCID: int
                            public static readonly MINSC_TRANSIENT_SCID: int
                            public static readonly MINSC_PERSISTENT_SCID: int
                            public static readonly ORG_OMG_PREFIX: string
                            public static readonly ORG_OMG_CORBA_PREFIX: string
                            public static readonly INITIAL_HOST_PROPERTY: string
                            public static readonly INITIAL_PORT_PROPERTY: string
                            public static readonly INITIAL_SERVICES_PROPERTY: string
                            public static readonly DEFAULT_INIT_REF_PROPERTY: string
                            public static readonly ORB_INIT_REF_PROPERTY: string
                            public static readonly SUN_PREFIX: string
                            public static readonly ALLOW_LOCAL_OPTIMIZATION: string
                            public static readonly SERVER_PORT_PROPERTY: string
                            public static readonly SERVER_HOST_PROPERTY: string
                            public static readonly ORB_ID_PROPERTY: string
                            public static readonly OLD_ORB_ID_PROPERTY: string
                            public static readonly ORB_SERVER_ID_PROPERTY: string
                            public static readonly DEBUG_PROPERTY: string
                            public static readonly USE_REP_ID: string
                            public static readonly LISTEN_ON_ALL_INTERFACES: string
                            public static readonly GIOP_VERSION: string
                            public static readonly GIOP_FRAGMENT_SIZE: string
                            public static readonly GIOP_BUFFER_SIZE: string
                            public static readonly GIOP_11_BUFFMGR: string
                            public static readonly GIOP_12_BUFFMGR: string
                            public static readonly GIOP_TARGET_ADDRESSING: string
                            public static readonly GIOP_DEFAULT_FRAGMENT_SIZE: int
                            public static readonly GIOP_DEFAULT_BUFFER_SIZE: int
                            public static readonly DEFAULT_GIOP_11_BUFFMGR: int
                            public static readonly DEFAULT_GIOP_12_BUFFMGR: int
                            public static readonly ADDR_DISP_OBJKEY: short
                            public static readonly ADDR_DISP_PROFILE: short
                            public static readonly ADDR_DISP_IOR: short
                            public static readonly ADDR_DISP_HANDLE_ALL: short
                            public static readonly GIOP_12_MSG_BODY_ALIGNMENT: int
                            public static readonly GIOP_FRAGMENT_DIVISOR: int
                            public static readonly GIOP_FRAGMENT_MINIMUM_SIZE: int
                            public static readonly HIGH_WATER_MARK_PROPERTY: string
                            public static readonly LOW_WATER_MARK_PROPERTY: string
                            public static readonly NUMBER_TO_RECLAIM_PROPERTY: string
                            public static readonly ACCEPTOR_CLASS_PREFIX_PROPERTY: string
                            public static readonly CONTACT_INFO_LIST_FACTORY_CLASS_PROPERTY: string
                            public static readonly LEGACY_SOCKET_FACTORY_CLASS_PROPERTY: string
                            public static readonly SOCKET_FACTORY_CLASS_PROPERTY: string
                            public static readonly LISTEN_SOCKET_PROPERTY: string
                            public static readonly IOR_TO_SOCKET_INFO_CLASS_PROPERTY: string
                            public static readonly IIOP_PRIMARY_TO_CONTACT_INFO_CLASS_PROPERTY: string
                            public static readonly REQUEST_PARTITIONING_MIN_THREAD_POOL_ID: int
                            public static readonly REQUEST_PARTITIONING_MAX_THREAD_POOL_ID: int
                            public static readonly TRANSPORT_TCP_READ_TIMEOUTS_PROPERTY: string
                            public static readonly TRANSPORT_TCP_INITIAL_TIME_TO_WAIT: int
                            public static readonly TRANSPORT_TCP_MAX_TIME_TO_WAIT: int
                            public static readonly TRANSPORT_TCP_GIOP_HEADER_MAX_TIME_TO_WAIT: int
                            public static readonly TRANSPORT_TCP_TIME_TO_WAIT_BACKOFF_FACTOR: int
                            public static readonly USE_NIO_SELECT_TO_WAIT_PROPERTY: string
                            public static readonly ACCEPTOR_SOCKET_TYPE_PROPERTY: string
                            public static readonly ACCEPTOR_SOCKET_USE_WORKER_THREAD_FOR_EVENT_PROPERTY: string
                            public static readonly CONNECTION_SOCKET_TYPE_PROPERTY: string
                            public static readonly CONNECTION_SOCKET_USE_WORKER_THREAD_FOR_EVENT_PROPERTY: string
                            public static readonly DISABLE_DIRECT_BYTE_BUFFER_USE_PROPERTY: string
                            public static readonly SOCKET: string
                            public static readonly SOCKETCHANNEL: string
                            public static readonly PERSISTENT_SERVER_PORT_PROPERTY: string
                            public static readonly SERVER_ID_PROPERTY: string
                            public static readonly BAD_SERVER_ID_HANDLER_CLASS_PROPERTY: string
                            public static readonly ACTIVATED_PROPERTY: string
                            public static readonly SERVER_NAME_PROPERTY: string
                            public static readonly SERVER_DEF_VERIFY_PROPERTY: string
                            public static readonly SUN_LC_PREFIX: string
                            public static readonly SUN_LC_VERSION_PREFIX: string
                            public static readonly JTS_CLASS_PROPERTY: string
                            public static readonly ENABLE_JAVA_SERIALIZATION_PROPERTY: string
                            public static readonly PI_ORB_INITIALIZER_CLASS_PREFIX: string
                            public static readonly USE_DYNAMIC_STUB_PROPERTY: string
                            public static readonly DYNAMIC_STUB_FACTORY_FACTORY_CLASS: string
                            public static readonly DEFAULT_INITIAL_PORT: int
                            public static readonly DEFAULT_INS_HOST: string
                            public static readonly DEFAULT_INS_PORT: int
                            public static readonly DEFAULT_INS_GIOP_MAJOR_VERSION: int
                            public static readonly DEFAULT_INS_GIOP_MINOR_VERSION: int
                            public static readonly MAJORNUMBER_SUPPORTED: int
                            public static readonly MINORNUMBERMAX: int
                            public static readonly TRANSIENT: int
                            public static readonly PERSISTENT: int
                            public static readonly DB_DIR_PROPERTY: string
                            public static readonly DB_PROPERTY: string
                            public static readonly ORBD_PORT_PROPERTY: string
                            public static readonly SERVER_POLLING_TIME: string
                            public static readonly SERVER_STARTUP_DELAY: string
                            public static readonly DEFAULT_ACTIVATION_PORT: int
                            public static readonly RI_NAMESERVICE_PORT: int
                            public static readonly DEFAULT_SERVER_POLLING_TIME: int
                            public static readonly DEFAULT_SERVER_STARTUP_DELAY: int
                            public static readonly LOG_LEVEL_PROPERTY: string
                            public static readonly LOG_RESOURCE_FILE: string
                            public static readonly TRANSIENT_NAME_SERVICE_NAME: string
                            public static readonly PERSISTENT_NAME_SERVICE_NAME: string
                            public static readonly NAME_SERVICE_SERVER_ID: string
                            public static readonly ROOT_POA_NAME: string
                            public static readonly POA_CURRENT_NAME: string
                            public static readonly SERVER_ACTIVATOR_NAME: string
                            public static readonly SERVER_LOCATOR_NAME: string
                            public static readonly SERVER_REPOSITORY_NAME: string
                            public static readonly INITIAL_NAME_SERVICE_NAME: string
                            public static readonly TRANSACTION_CURRENT_NAME: string
                            public static readonly DYN_ANY_FACTORY_NAME: string
                            public static readonly PI_CURRENT_NAME: string
                            public static readonly CODEC_FACTORY_NAME: string
                            public static readonly DEFAULT_DB_DIR: string
                            public static readonly DEFAULT_DB_NAME: string
                            public static readonly INITIAL_ORB_DB: string
                            public static readonly SERVER_LOG_DIR: string
                            public static readonly ORBID_DIR_BASE: string
                            public static readonly ORBID_DB_FILE_NAME: string
                            public static readonly DEFAULT_INACTIVITY_TIMEOUT: int
                            public static readonly THREADPOOL_DEFAULT_NAME: string
                            public static readonly WORKQUEUE_DEFAULT_NAME: string
                            public static readonly LEGACY_SUN_NOT_SERIALIZABLE: int
                            public static readonly DEFAULT_ALWAYS_SEND_CODESET_CTX: boolean
                            public static readonly ALWAYS_SEND_CODESET_CTX_PROPERTY: string
                            public static readonly DEFAULT_USE_BYTE_ORDER_MARKERS: boolean
                            public static readonly USE_BOMS: string
                            public static readonly DEFAULT_USE_BYTE_ORDER_MARKERS_IN_ENCAPS: boolean
                            public static readonly USE_BOMS_IN_ENCAPS: string
                            public static readonly CHAR_CODESETS: string
                            public static readonly WCHAR_CODESETS: string
                            public static readonly STREAM_FORMAT_VERSION_1: byte
                            public static readonly STREAM_FORMAT_VERSION_2: byte
                            public static isTransient(arg0: int): boolean
                            public static makePersistent(arg0: int): int
                            public static class: java.lang.Class<any>
                        }
                    }
                }
            }
        }
    }
}