declare namespace com {
    namespace sun {
        namespace corba {
            namespace se {
                namespace spi {
                    namespace monitoring {
interface MonitoringConstants {
    DEFAULT_MONITORING_ROOT: string
    DEFAULT_MONITORING_ROOT_DESCRIPTION: string
    CONNECTION_MONITORING_ROOT: string
    CONNECTION_MONITORING_ROOT_DESCRIPTION: string
    INBOUND_CONNECTION_MONITORING_ROOT: string
    INBOUND_CONNECTION_MONITORING_ROOT_DESCRIPTION: string
    OUTBOUND_CONNECTION_MONITORING_ROOT: string
    OUTBOUND_CONNECTION_MONITORING_ROOT_DESCRIPTION: string
    CONNECTION_MONITORING_DESCRIPTION: string
    CONNECTION_TOTAL_NUMBER_OF_CONNECTIONS: string
    CONNECTION_TOTAL_NUMBER_OF_CONNECTIONS_DESCRIPTION: string
    CONNECTION_NUMBER_OF_IDLE_CONNECTIONS: string
    CONNECTION_NUMBER_OF_IDLE_CONNECTIONS_DESCRIPTION: string
    CONNECTION_NUMBER_OF_BUSY_CONNECTIONS: string
    CONNECTION_NUMBER_OF_BUSY_CONNECTIONS_DESCRIPTION: string
    THREADPOOL_MONITORING_ROOT: string
    THREADPOOL_MONITORING_ROOT_DESCRIPTION: string
    THREADPOOL_MONITORING_DESCRIPTION: string
    THREADPOOL_CURRENT_NUMBER_OF_THREADS: string
    THREADPOOL_CURRENT_NUMBER_OF_THREADS_DESCRIPTION: string
    THREADPOOL_NUMBER_OF_AVAILABLE_THREADS: string
    THREADPOOL_NUMBER_OF_AVAILABLE_THREADS_DESCRIPTION: string
    THREADPOOL_NUMBER_OF_BUSY_THREADS: string
    THREADPOOL_NUMBER_OF_BUSY_THREADS_DESCRIPTION: string
    THREADPOOL_AVERAGE_WORK_COMPLETION_TIME: string
    THREADPOOL_AVERAGE_WORK_COMPLETION_TIME_DESCRIPTION: string
    THREADPOOL_CURRENT_PROCESSED_COUNT: string
    THREADPOOL_CURRENT_PROCESSED_COUNT_DESCRIPTION: string
    WORKQUEUE_MONITORING_DESCRIPTION: string
    WORKQUEUE_TOTAL_WORK_ITEMS_ADDED: string
    WORKQUEUE_TOTAL_WORK_ITEMS_ADDED_DESCRIPTION: string
    WORKQUEUE_WORK_ITEMS_IN_QUEUE: string
    WORKQUEUE_WORK_ITEMS_IN_QUEUE_DESCRIPTION: string
    WORKQUEUE_AVERAGE_TIME_IN_QUEUE: string
    WORKQUEUE_AVERAGE_TIME_IN_QUEUE_DESCRIPTION: string
}

                    }
                }
            }
        }
    }
}