declare namespace com {
    namespace sun {
        namespace org {
            namespace apache {
                namespace xalan {
                    namespace internal {
                        namespace xsltc {
                            namespace compiler {
                                interface Constants extends com.sun.org.apache.bcel.internal.generic.InstructionConstants {
                                    INTERNAL: int
                                    UNSUPPORTED: int
                                    FATAL: int
                                    ERROR: int
                                    WARNING: int
                                    EMPTYSTRING: string
                                    NAMESPACE_FEATURE: string
                                    TRANSLET_INTF: string
                                    TRANSLET_INTF_SIG: string
                                    ATTRIBUTES_SIG: string
                                    NODE_ITERATOR_SIG: string
                                    DOM_INTF_SIG: string
                                    DOM_IMPL_CLASS: string
                                    SAX_IMPL_CLASS: string
                                    DOM_IMPL_SIG: string
                                    SAX_IMPL_SIG: string
                                    DOM_ADAPTER_CLASS: string
                                    DOM_ADAPTER_SIG: string
                                    MULTI_DOM_CLASS: string
                                    MULTI_DOM_SIG: string
                                    STRING: string
                                    ACC_PUBLIC: int
                                    ACC_SUPER: int
                                    ACC_FINAL: int
                                    ACC_PRIVATE: int
                                    ACC_PROTECTED: int
                                    ACC_STATIC: int
                                    STRING_SIG: string
                                    STRING_BUFFER_SIG: string
                                    OBJECT_SIG: string
                                    DOUBLE_SIG: string
                                    INTEGER_SIG: string
                                    COLLATOR_CLASS: string
                                    COLLATOR_SIG: string
                                    NODE: string
                                    NODE_ITERATOR: string
                                    NODE_ITERATOR_BASE: string
                                    SORT_ITERATOR: string
                                    SORT_ITERATOR_SIG: string
                                    NODE_SORT_RECORD: string
                                    NODE_SORT_FACTORY: string
                                    NODE_SORT_RECORD_SIG: string
                                    NODE_SORT_FACTORY_SIG: string
                                    LOCALE_CLASS: string
                                    LOCALE_SIG: string
                                    STRING_VALUE_HANDLER: string
                                    STRING_VALUE_HANDLER_SIG: string
                                    OUTPUT_HANDLER: string
                                    OUTPUT_HANDLER_SIG: string
                                    FILTER_INTERFACE: string
                                    FILTER_INTERFACE_SIG: string
                                    UNION_ITERATOR_CLASS: string
                                    STEP_ITERATOR_CLASS: string
                                    CACHED_NODE_LIST_ITERATOR_CLASS: string
                                    NTH_ITERATOR_CLASS: string
                                    ABSOLUTE_ITERATOR: string
                                    DUP_FILTERED_ITERATOR: string
                                    CURRENT_NODE_LIST_ITERATOR: string
                                    CURRENT_NODE_LIST_FILTER: string
                                    CURRENT_NODE_LIST_ITERATOR_SIG: string
                                    CURRENT_NODE_LIST_FILTER_SIG: string
                                    FILTER_STEP_ITERATOR: string
                                    FILTER_ITERATOR: string
                                    SINGLETON_ITERATOR: string
                                    MATCHING_ITERATOR: string
                                    NODE_SIG: string
                                    GET_PARENT: string
                                    GET_PARENT_SIG: string
                                    NEXT_SIG: string
                                    NEXT: string
                                    NEXTID: string
                                    MAKE_NODE: string
                                    MAKE_NODE_LIST: string
                                    GET_UNPARSED_ENTITY_URI: string
                                    STRING_TO_REAL: string
                                    STRING_TO_REAL_SIG: string
                                    STRING_TO_INT: string
                                    STRING_TO_INT_SIG: string
                                    XSLT_PACKAGE: string
                                    COMPILER_PACKAGE: string
                                    RUNTIME_PACKAGE: string
                                    TRANSLET_CLASS: string
                                    TRANSLET_SIG: string
                                    UNION_ITERATOR_SIG: string
                                    TRANSLET_OUTPUT_SIG: string
                                    MAKE_NODE_SIG: string
                                    MAKE_NODE_SIG2: string
                                    MAKE_NODE_LIST_SIG: string
                                    MAKE_NODE_LIST_SIG2: string
                                    STREAM_XML_OUTPUT: string
                                    OUTPUT_BASE: string
                                    LOAD_DOCUMENT_CLASS: string
                                    KEY_INDEX_CLASS: string
                                    KEY_INDEX_SIG: string
                                    KEY_INDEX_ITERATOR_SIG: string
                                    DOM_INTF: string
                                    DOM_IMPL: string
                                    SAX_IMPL: string
                                    STRING_CLASS: string
                                    OBJECT_CLASS: string
                                    BOOLEAN_CLASS: string
                                    STRING_BUFFER_CLASS: string
                                    STRING_WRITER: string
                                    WRITER_SIG: string
                                    TRANSLET_OUTPUT_BASE: string
                                    TRANSLET_OUTPUT_INTERFACE: string
                                    BASIS_LIBRARY_CLASS: string
                                    ATTRIBUTE_LIST_IMPL_CLASS: string
                                    DOUBLE_CLASS: string
                                    INTEGER_CLASS: string
                                    RUNTIME_NODE_CLASS: string
                                    MATH_CLASS: string
                                    BOOLEAN_VALUE: string
                                    BOOLEAN_VALUE_SIG: string
                                    INT_VALUE: string
                                    INT_VALUE_SIG: string
                                    DOUBLE_VALUE: string
                                    DOUBLE_VALUE_SIG: string
                                    DOM_PNAME: string
                                    NODE_PNAME: string
                                    TRANSLET_OUTPUT_PNAME: string
                                    ITERATOR_PNAME: string
                                    DOCUMENT_PNAME: string
                                    TRANSLET_PNAME: string
                                    INVOKE_METHOD: string
                                    GET_NODE_NAME: string
                                    CHARACTERSW: string
                                    GET_CHILDREN: string
                                    GET_TYPED_CHILDREN: string
                                    CHARACTERS: string
                                    APPLY_TEMPLATES: string
                                    GET_NODE_TYPE: string
                                    GET_NODE_VALUE: string
                                    GET_ELEMENT_VALUE: string
                                    GET_ATTRIBUTE_VALUE: string
                                    HAS_ATTRIBUTE: string
                                    ADD_ITERATOR: string
                                    SET_START_NODE: string
                                    RESET: string
                                    ATTR_SET_SIG: string
                                    GET_NODE_NAME_SIG: string
                                    CHARACTERSW_SIG: string
                                    CHARACTERS_SIG: string
                                    GET_CHILDREN_SIG: string
                                    GET_TYPED_CHILDREN_SIG: string
                                    GET_NODE_TYPE_SIG: string
                                    GET_NODE_VALUE_SIG: string
                                    GET_ELEMENT_VALUE_SIG: string
                                    GET_ATTRIBUTE_VALUE_SIG: string
                                    HAS_ATTRIBUTE_SIG: string
                                    GET_ITERATOR_SIG: string
                                    NAMES_INDEX: string
                                    NAMES_INDEX_SIG: string
                                    URIS_INDEX: string
                                    URIS_INDEX_SIG: string
                                    TYPES_INDEX: string
                                    TYPES_INDEX_SIG: string
                                    NAMESPACE_INDEX: string
                                    NAMESPACE_INDEX_SIG: string
                                    HASIDCALL_INDEX: string
                                    HASIDCALL_INDEX_SIG: string
                                    TRANSLET_VERSION_INDEX: string
                                    TRANSLET_VERSION_INDEX_SIG: string
                                    DOM_FIELD: string
                                    STATIC_NAMES_ARRAY_FIELD: string
                                    STATIC_URIS_ARRAY_FIELD: string
                                    STATIC_TYPES_ARRAY_FIELD: string
                                    STATIC_NAMESPACE_ARRAY_FIELD: string
                                    STATIC_CHAR_DATA_FIELD: string
                                    STATIC_CHAR_DATA_FIELD_SIG: string
                                    FORMAT_SYMBOLS_FIELD: string
                                    ITERATOR_FIELD_SIG: string
                                    NODE_FIELD: string
                                    NODE_FIELD_SIG: string
                                    EMPTYATTR_FIELD: string
                                    ATTRIBUTE_LIST_FIELD: string
                                    CLEAR_ATTRIBUTES: string
                                    ADD_ATTRIBUTE: string
                                    ATTRIBUTE_LIST_IMPL_SIG: string
                                    CLEAR_ATTRIBUTES_SIG: string
                                    ADD_ATTRIBUTE_SIG: string
                                    ADD_ITERATOR_SIG: string
                                    ORDER_ITERATOR: string
                                    ORDER_ITERATOR_SIG: string
                                    SET_START_NODE_SIG: string
                                    NODE_COUNTER: string
                                    NODE_COUNTER_SIG: string
                                    DEFAULT_NODE_COUNTER: string
                                    DEFAULT_NODE_COUNTER_SIG: string
                                    TRANSLET_FIELD: string
                                    TRANSLET_FIELD_SIG: string
                                    RESET_SIG: string
                                    GET_PARAMETER: string
                                    ADD_PARAMETER: string
                                    PUSH_PARAM_FRAME: string
                                    PUSH_PARAM_FRAME_SIG: string
                                    POP_PARAM_FRAME: string
                                    POP_PARAM_FRAME_SIG: string
                                    GET_PARAMETER_SIG: string
                                    ADD_PARAMETER_SIG: string
                                    STRIP_SPACE: string
                                    STRIP_SPACE_INTF: string
                                    STRIP_SPACE_SIG: string
                                    STRIP_SPACE_PARAMS: string
                                    GET_NODE_VALUE_ITERATOR: string
                                    GET_NODE_VALUE_ITERATOR_SIG: string
                                    GET_UNPARSED_ENTITY_URI_SIG: string
                                    POSITION_INDEX: int
                                    LAST_INDEX: int
                                    XMLNS_PREFIX: string
                                    XMLNS_STRING: string
                                    XMLNS_URI: string
                                    XSLT_URI: string
                                    XHTML_URI: string
                                    TRANSLET_URI: string
                                    REDIRECT_URI: string
                                    FALLBACK_CLASS: string
                                    RTF_INITIAL_SIZE: int
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}