declare namespace com {
    namespace sun {
        namespace xml {
            namespace internal {
                namespace fastinfoset {
class EncodingConstants {
    public static XML_NAMESPACE_PREFIX: string
    public static XML_NAMESPACE_PREFIX_LENGTH: int
    public static XML_NAMESPACE_NAME: string
    public static XML_NAMESPACE_NAME_LENGTH: int
    public static XMLNS_NAMESPACE_PREFIX: string
    public static XMLNS_NAMESPACE_PREFIX_LENGTH: int
    public static XMLNS_NAMESPACE_NAME: string
    public static XMLNS_NAMESPACE_NAME_LENGTH: int
    public static DEFAULT_NAMESPACE_DECLARATION: com.sun.xml.internal.fastinfoset.QualifiedName
    public static DOCUMENT_ADDITIONAL_DATA_FLAG: int
    public static DOCUMENT_INITIAL_VOCABULARY_FLAG: int
    public static DOCUMENT_NOTATIONS_FLAG: int
    public static DOCUMENT_UNPARSED_ENTITIES_FLAG: int
    public static DOCUMENT_CHARACTER_ENCODING_SCHEME: int
    public static DOCUMENT_STANDALONE_FLAG: int
    public static DOCUMENT_VERSION_FLAG: int
    public static INITIAL_VOCABULARY_EXTERNAL_VOCABULARY_FLAG: int
    public static INITIAL_VOCABULARY_RESTRICTED_ALPHABETS_FLAG: int
    public static INITIAL_VOCABULARY_ENCODING_ALGORITHMS_FLAG: int
    public static INITIAL_VOCABULARY_PREFIXES_FLAG: int
    public static INITIAL_VOCABULARY_NAMESPACE_NAMES_FLAG: int
    public static INITIAL_VOCABULARY_LOCAL_NAMES_FLAG: int
    public static INITIAL_VOCABULARY_OTHER_NCNAMES_FLAG: int
    public static INITIAL_VOCABULARY_OTHER_URIS_FLAG: int
    public static INITIAL_VOCABULARY_ATTRIBUTE_VALUES_FLAG: int
    public static INITIAL_VOCABULARY_CONTENT_CHARACTER_CHUNKS_FLAG: int
    public static INITIAL_VOCABULARY_OTHER_STRINGS_FLAG: int
    public static INITIAL_VOCABULARY_ELEMENT_NAME_SURROGATES_FLAG: int
    public static INITIAL_VOCABULARY_ATTRIBUTE_NAME_SURROGATES_FLAG: int
    public static NAME_SURROGATE_PREFIX_FLAG: int
    public static NAME_SURROGATE_NAME_FLAG: int
    public static NOTATIONS: int
    public static NOTATIONS_MASK: int
    public static NOTATIONS_SYSTEM_IDENTIFIER_FLAG: int
    public static NOTATIONS_PUBLIC_IDENTIFIER_FLAG: int
    public static UNPARSED_ENTITIES: int
    public static UNPARSED_ENTITIES_MASK: int
    public static UNPARSED_ENTITIES_PUBLIC_IDENTIFIER_FLAG: int
    public static PROCESSING_INSTRUCTION: int
    public static PROCESSING_INSTRUCTION_MASK: int
    public static COMMENT: int
    public static COMMENT_MASK: int
    public static DOCUMENT_TYPE_DECLARATION: int
    public static DOCUMENT_TYPE_DECLARATION_MASK: int
    public static DOCUMENT_TYPE_SYSTEM_IDENTIFIER_FLAG: int
    public static DOCUMENT_TYPE_PUBLIC_IDENTIFIER_FLAG: int
    public static ELEMENT: int
    public static ELEMENT_ATTRIBUTE_FLAG: int
    public static ELEMENT_NAMESPACES_FLAG: int
    public static ELEMENT_LITERAL_QNAME_FLAG: int
    public static NAMESPACE_ATTRIBUTE: int
    public static NAMESPACE_ATTRIBUTE_MASK: int
    public static NAMESPACE_ATTRIBUTE_PREFIX_NAME_MASK: int
    public static NAMESPACE_ATTRIBUTE_PREFIX_FLAG: int
    public static NAMESPACE_ATTRIBUTE_NAME_FLAG: int
    public static ATTRIBUTE_LITERAL_QNAME_FLAG: int
    public static LITERAL_QNAME_PREFIX_NAMESPACE_NAME_MASK: int
    public static LITERAL_QNAME_PREFIX_FLAG: int
    public static LITERAL_QNAME_NAMESPACE_NAME_FLAG: int
    public static CHARACTER_CHUNK: int
    public static CHARACTER_CHUNK_ADD_TO_TABLE_FLAG: int
    public static CHARACTER_CHUNK_UTF_8_FLAG: int
    public static CHARACTER_CHUNK_UTF_16_FLAG: int
    public static CHARACTER_CHUNK_RESTRICTED_ALPHABET_FLAG: int
    public static CHARACTER_CHUNK_ENCODING_ALGORITHM_FLAG: int
    public static UNEXPANDED_ENTITY_REFERENCE: int
    public static UNEXPANDED_ENTITY_REFERENCE_MASK: int
    public static UNEXPANDED_ENTITY_SYSTEM_IDENTIFIER_FLAG: int
    public static UNEXPANDED_ENTITY_PUBLIC_IDENTIFIER_FLAG: int
    public static NISTRING_ADD_TO_TABLE_FLAG: int
    public static NISTRING_UTF_8_FLAG: int
    public static NISTRING_UTF_16_FLAG: int
    public static NISTRING_RESTRICTED_ALPHABET_FLAG: int
    public static NISTRING_ENCODING_ALGORITHM_FLAG: int
    public static TERMINATOR: int
    public static DOUBLE_TERMINATOR: int
    public static ENCODING_ALGORITHM_BUILTIN_END: int
    public static ENCODING_ALGORITHM_APPLICATION_START: int
    public static ENCODING_ALGORITHM_APPLICATION_MAX: int
    public static RESTRICTED_ALPHABET_BUILTIN_END: int
    public static RESTRICTED_ALPHABET_APPLICATION_START: int
    public static RESTRICTED_ALPHABET_APPLICATION_MAX: int
    public static OCTET_STRING_LENGTH_SMALL_LIMIT: int
    public static OCTET_STRING_LENGTH_MEDIUM_LIMIT: int
    public static OCTET_STRING_LENGTH_MEDIUM_FLAG: int
    public static OCTET_STRING_LENGTH_LARGE_FLAG: int
    public static OCTET_STRING_MAXIMUM_LENGTH: long
    public static OCTET_STRING_LENGTH_2ND_BIT_SMALL_LIMIT: int
    public static OCTET_STRING_LENGTH_2ND_BIT_MEDIUM_LIMIT: int
    public static OCTET_STRING_LENGTH_2ND_BIT_MEDIUM_FLAG: int
    public static OCTET_STRING_LENGTH_2ND_BIT_LARGE_FLAG: int
    public static OCTET_STRING_LENGTH_2ND_BIT_SMALL_MASK: int
    public static OCTET_STRING_LENGTH_5TH_BIT_SMALL_LIMIT: int
    public static OCTET_STRING_LENGTH_5TH_BIT_MEDIUM_LIMIT: int
    public static OCTET_STRING_LENGTH_5TH_BIT_MEDIUM_FLAG: int
    public static OCTET_STRING_LENGTH_5TH_BIT_LARGE_FLAG: int
    public static OCTET_STRING_LENGTH_5TH_BIT_SMALL_MASK: int
    public static OCTET_STRING_LENGTH_7TH_BIT_SMALL_LIMIT: int
    public static OCTET_STRING_LENGTH_7TH_BIT_MEDIUM_LIMIT: int
    public static OCTET_STRING_LENGTH_7TH_BIT_MEDIUM_FLAG: int
    public static OCTET_STRING_LENGTH_7TH_BIT_LARGE_FLAG: int
    public static OCTET_STRING_LENGTH_7TH_BIT_SMALL_MASK: int
    public static INTEGER_SMALL_LIMIT: int
    public static INTEGER_MEDIUM_LIMIT: int
    public static INTEGER_LARGE_LIMIT: int
    public static INTEGER_MEDIUM_FLAG: int
    public static INTEGER_LARGE_FLAG: int
    public static INTEGER_LARGE_LARGE_FLAG: int
    public static INTEGER_MAXIMUM_SIZE: int
    public static INTEGER_2ND_BIT_SMALL_LIMIT: int
    public static INTEGER_2ND_BIT_MEDIUM_LIMIT: int
    public static INTEGER_2ND_BIT_LARGE_LIMIT: int
    public static INTEGER_2ND_BIT_MEDIUM_FLAG: int
    public static INTEGER_2ND_BIT_LARGE_FLAG: int
    public static INTEGER_2ND_BIT_SMALL_MASK: int
    public static INTEGER_2ND_BIT_MEDIUM_MASK: int
    public static INTEGER_2ND_BIT_LARGE_MASK: int
    public static INTEGER_3RD_BIT_SMALL_LIMIT: int
    public static INTEGER_3RD_BIT_MEDIUM_LIMIT: int
    public static INTEGER_3RD_BIT_LARGE_LIMIT: int
    public static INTEGER_3RD_BIT_MEDIUM_FLAG: int
    public static INTEGER_3RD_BIT_LARGE_FLAG: int
    public static INTEGER_3RD_BIT_LARGE_LARGE_FLAG: int
    public static INTEGER_3RD_BIT_SMALL_MASK: int
    public static INTEGER_3RD_BIT_MEDIUM_MASK: int
    public static INTEGER_3RD_BIT_LARGE_MASK: int
    public static INTEGER_3RD_BIT_LARGE_LARGE_MASK: int
    public static INTEGER_4TH_BIT_SMALL_LIMIT: int
    public static INTEGER_4TH_BIT_MEDIUM_LIMIT: int
    public static INTEGER_4TH_BIT_LARGE_LIMIT: int
    public static INTEGER_4TH_BIT_MEDIUM_FLAG: int
    public static INTEGER_4TH_BIT_LARGE_FLAG: int
    public static INTEGER_4TH_BIT_LARGE_LARGE_FLAG: int
    public static INTEGER_4TH_BIT_SMALL_MASK: int
    public static INTEGER_4TH_BIT_MEDIUM_MASK: int
    public static INTEGER_4TH_BIT_LARGE_MASK: int
    public constructor()
    public static class: java.lang.Class<any>
}

                }
            }
        }
    }
}