declare namespace com {
    namespace sun {
        namespace org {
            namespace apache {
                namespace bcel {
                    namespace internal {
                        interface Constants {
                            MAJOR_1_1: short
                            MINOR_1_1: short
                            MAJOR_1_2: short
                            MINOR_1_2: short
                            MAJOR_1_3: short
                            MINOR_1_3: short
                            MAJOR: short
                            MINOR: short
                            MAX_SHORT: int
                            MAX_BYTE: int
                            ACC_PUBLIC: short
                            ACC_PRIVATE: short
                            ACC_PROTECTED: short
                            ACC_STATIC: short
                            ACC_FINAL: short
                            ACC_SYNCHRONIZED: short
                            ACC_VOLATILE: short
                            ACC_TRANSIENT: short
                            ACC_NATIVE: short
                            ACC_INTERFACE: short
                            ACC_ABSTRACT: short
                            ACC_STRICT: short
                            ACC_SUPER: short
                            MAX_ACC_FLAG: short
                            ACCESS_NAMES: java.lang.String[]
                            CONSTANT_Utf8: byte
                            CONSTANT_Integer: byte
                            CONSTANT_Float: byte
                            CONSTANT_Long: byte
                            CONSTANT_Double: byte
                            CONSTANT_Class: byte
                            CONSTANT_Fieldref: byte
                            CONSTANT_String: byte
                            CONSTANT_Methodref: byte
                            CONSTANT_InterfaceMethodref: byte
                            CONSTANT_NameAndType: byte
                            CONSTANT_NAMES: java.lang.String[]
                            STATIC_INITIALIZER_NAME: string
                            CONSTRUCTOR_NAME: string
                            INTERFACES_IMPLEMENTED_BY_ARRAYS: java.lang.String[]
                            MAX_CP_ENTRIES: int
                            MAX_CODE_SIZE: int
                            NOP: short
                            ACONST_NULL: short
                            ICONST_M1: short
                            ICONST_0: short
                            ICONST_1: short
                            ICONST_2: short
                            ICONST_3: short
                            ICONST_4: short
                            ICONST_5: short
                            LCONST_0: short
                            LCONST_1: short
                            FCONST_0: short
                            FCONST_1: short
                            FCONST_2: short
                            DCONST_0: short
                            DCONST_1: short
                            BIPUSH: short
                            SIPUSH: short
                            LDC: short
                            LDC_W: short
                            LDC2_W: short
                            ILOAD: short
                            LLOAD: short
                            FLOAD: short
                            DLOAD: short
                            ALOAD: short
                            ILOAD_0: short
                            ILOAD_1: short
                            ILOAD_2: short
                            ILOAD_3: short
                            LLOAD_0: short
                            LLOAD_1: short
                            LLOAD_2: short
                            LLOAD_3: short
                            FLOAD_0: short
                            FLOAD_1: short
                            FLOAD_2: short
                            FLOAD_3: short
                            DLOAD_0: short
                            DLOAD_1: short
                            DLOAD_2: short
                            DLOAD_3: short
                            ALOAD_0: short
                            ALOAD_1: short
                            ALOAD_2: short
                            ALOAD_3: short
                            IALOAD: short
                            LALOAD: short
                            FALOAD: short
                            DALOAD: short
                            AALOAD: short
                            BALOAD: short
                            CALOAD: short
                            SALOAD: short
                            ISTORE: short
                            LSTORE: short
                            FSTORE: short
                            DSTORE: short
                            ASTORE: short
                            ISTORE_0: short
                            ISTORE_1: short
                            ISTORE_2: short
                            ISTORE_3: short
                            LSTORE_0: short
                            LSTORE_1: short
                            LSTORE_2: short
                            LSTORE_3: short
                            FSTORE_0: short
                            FSTORE_1: short
                            FSTORE_2: short
                            FSTORE_3: short
                            DSTORE_0: short
                            DSTORE_1: short
                            DSTORE_2: short
                            DSTORE_3: short
                            ASTORE_0: short
                            ASTORE_1: short
                            ASTORE_2: short
                            ASTORE_3: short
                            IASTORE: short
                            LASTORE: short
                            FASTORE: short
                            DASTORE: short
                            AASTORE: short
                            BASTORE: short
                            CASTORE: short
                            SASTORE: short
                            POP: short
                            POP2: short
                            DUP: short
                            DUP_X1: short
                            DUP_X2: short
                            DUP2: short
                            DUP2_X1: short
                            DUP2_X2: short
                            SWAP: short
                            IADD: short
                            LADD: short
                            FADD: short
                            DADD: short
                            ISUB: short
                            LSUB: short
                            FSUB: short
                            DSUB: short
                            IMUL: short
                            LMUL: short
                            FMUL: short
                            DMUL: short
                            IDIV: short
                            LDIV: short
                            FDIV: short
                            DDIV: short
                            IREM: short
                            LREM: short
                            FREM: short
                            DREM: short
                            INEG: short
                            LNEG: short
                            FNEG: short
                            DNEG: short
                            ISHL: short
                            LSHL: short
                            ISHR: short
                            LSHR: short
                            IUSHR: short
                            LUSHR: short
                            IAND: short
                            LAND: short
                            IOR: short
                            LOR: short
                            IXOR: short
                            LXOR: short
                            IINC: short
                            I2L: short
                            I2F: short
                            I2D: short
                            L2I: short
                            L2F: short
                            L2D: short
                            F2I: short
                            F2L: short
                            F2D: short
                            D2I: short
                            D2L: short
                            D2F: short
                            I2B: short
                            INT2BYTE: short
                            I2C: short
                            INT2CHAR: short
                            I2S: short
                            INT2SHORT: short
                            LCMP: short
                            FCMPL: short
                            FCMPG: short
                            DCMPL: short
                            DCMPG: short
                            IFEQ: short
                            IFNE: short
                            IFLT: short
                            IFGE: short
                            IFGT: short
                            IFLE: short
                            IF_ICMPEQ: short
                            IF_ICMPNE: short
                            IF_ICMPLT: short
                            IF_ICMPGE: short
                            IF_ICMPGT: short
                            IF_ICMPLE: short
                            IF_ACMPEQ: short
                            IF_ACMPNE: short
                            GOTO: short
                            JSR: short
                            RET: short
                            TABLESWITCH: short
                            LOOKUPSWITCH: short
                            IRETURN: short
                            LRETURN: short
                            FRETURN: short
                            DRETURN: short
                            ARETURN: short
                            RETURN: short
                            GETSTATIC: short
                            PUTSTATIC: short
                            GETFIELD: short
                            PUTFIELD: short
                            INVOKEVIRTUAL: short
                            INVOKESPECIAL: short
                            INVOKENONVIRTUAL: short
                            INVOKESTATIC: short
                            INVOKEINTERFACE: short
                            NEW: short
                            NEWARRAY: short
                            ANEWARRAY: short
                            ARRAYLENGTH: short
                            ATHROW: short
                            CHECKCAST: short
                            INSTANCEOF: short
                            MONITORENTER: short
                            MONITOREXIT: short
                            WIDE: short
                            MULTIANEWARRAY: short
                            IFNULL: short
                            IFNONNULL: short
                            GOTO_W: short
                            JSR_W: short
                            BREAKPOINT: short
                            LDC_QUICK: short
                            LDC_W_QUICK: short
                            LDC2_W_QUICK: short
                            GETFIELD_QUICK: short
                            PUTFIELD_QUICK: short
                            GETFIELD2_QUICK: short
                            PUTFIELD2_QUICK: short
                            GETSTATIC_QUICK: short
                            PUTSTATIC_QUICK: short
                            GETSTATIC2_QUICK: short
                            PUTSTATIC2_QUICK: short
                            INVOKEVIRTUAL_QUICK: short
                            INVOKENONVIRTUAL_QUICK: short
                            INVOKESUPER_QUICK: short
                            INVOKESTATIC_QUICK: short
                            INVOKEINTERFACE_QUICK: short
                            INVOKEVIRTUALOBJECT_QUICK: short
                            NEW_QUICK: short
                            ANEWARRAY_QUICK: short
                            MULTIANEWARRAY_QUICK: short
                            CHECKCAST_QUICK: short
                            INSTANCEOF_QUICK: short
                            INVOKEVIRTUAL_QUICK_W: short
                            GETFIELD_QUICK_W: short
                            PUTFIELD_QUICK_W: short
                            IMPDEP1: short
                            IMPDEP2: short
                            PUSH: short
                            SWITCH: short
                            UNDEFINED: short
                            UNPREDICTABLE: short
                            RESERVED: short
                            ILLEGAL_OPCODE: string
                            ILLEGAL_TYPE: string
                            T_BOOLEAN: byte
                            T_CHAR: byte
                            T_FLOAT: byte
                            T_DOUBLE: byte
                            T_BYTE: byte
                            T_SHORT: byte
                            T_INT: byte
                            T_LONG: byte
                            T_VOID: byte
                            T_ARRAY: byte
                            T_OBJECT: byte
                            T_REFERENCE: byte
                            T_UNKNOWN: byte
                            T_ADDRESS: byte
                            TYPE_NAMES: java.lang.String[]
                            CLASS_TYPE_NAMES: java.lang.String[]
                            SHORT_TYPE_NAMES: java.lang.String[]
                            NO_OF_OPERANDS: short[]
                            TYPE_OF_OPERANDS: short[][]
                            OPCODE_NAMES: java.lang.String[]
                            CONSUME_STACK: int[]
                            PRODUCE_STACK: int[]
                            ATTR_UNKNOWN: byte
                            ATTR_SOURCE_FILE: byte
                            ATTR_CONSTANT_VALUE: byte
                            ATTR_CODE: byte
                            ATTR_EXCEPTIONS: byte
                            ATTR_LINE_NUMBER_TABLE: byte
                            ATTR_LOCAL_VARIABLE_TABLE: byte
                            ATTR_INNER_CLASSES: byte
                            ATTR_SYNTHETIC: byte
                            ATTR_DEPRECATED: byte
                            ATTR_PMG: byte
                            ATTR_SIGNATURE: byte
                            ATTR_STACK_MAP: byte
                            ATTR_LOCAL_VARIABLE_TYPE_TABLE: byte
                            KNOWN_ATTRIBUTES: short
                            ATTRIBUTE_NAMES: java.lang.String[]
                            ITEM_Bogus: byte
                            ITEM_Integer: byte
                            ITEM_Float: byte
                            ITEM_Double: byte
                            ITEM_Long: byte
                            ITEM_Null: byte
                            ITEM_InitObject: byte
                            ITEM_Object: byte
                            ITEM_NewObject: byte
                            ITEM_NAMES: java.lang.String[]
                        }
                    }
                }
            }
        }
    }
}