declare namespace com {
    namespace sun {
        namespace org {
            namespace apache {
                namespace bcel {
                    namespace internal {
                        namespace generic {
                            interface Visitor {
                                visitStackInstruction(arg0: com.sun.org.apache.bcel.internal.generic.StackInstruction): void
                                visitLocalVariableInstruction(arg0: com.sun.org.apache.bcel.internal.generic.LocalVariableInstruction): void
                                visitBranchInstruction(arg0: com.sun.org.apache.bcel.internal.generic.BranchInstruction): void
                                visitLoadClass(arg0: com.sun.org.apache.bcel.internal.generic.LoadClass): void
                                visitFieldInstruction(arg0: com.sun.org.apache.bcel.internal.generic.FieldInstruction): void
                                visitIfInstruction(arg0: com.sun.org.apache.bcel.internal.generic.IfInstruction): void
                                visitConversionInstruction(arg0: com.sun.org.apache.bcel.internal.generic.ConversionInstruction): void
                                visitPopInstruction(arg0: com.sun.org.apache.bcel.internal.generic.PopInstruction): void
                                visitStoreInstruction(arg0: com.sun.org.apache.bcel.internal.generic.StoreInstruction): void
                                visitTypedInstruction(arg0: com.sun.org.apache.bcel.internal.generic.TypedInstruction | com.sun.org.apache.bcel.internal.generic.TypedInstruction$$Lambda): void
                                visitSelect(arg0: com.sun.org.apache.bcel.internal.generic.Select): void
                                visitJsrInstruction(arg0: com.sun.org.apache.bcel.internal.generic.JsrInstruction): void
                                visitGotoInstruction(arg0: com.sun.org.apache.bcel.internal.generic.GotoInstruction): void
                                visitUnconditionalBranch(arg0: com.sun.org.apache.bcel.internal.generic.UnconditionalBranch): void
                                visitPushInstruction(arg0: com.sun.org.apache.bcel.internal.generic.PushInstruction): void
                                visitArithmeticInstruction(arg0: com.sun.org.apache.bcel.internal.generic.ArithmeticInstruction): void
                                visitCPInstruction(arg0: com.sun.org.apache.bcel.internal.generic.CPInstruction): void
                                visitInvokeInstruction(arg0: com.sun.org.apache.bcel.internal.generic.InvokeInstruction): void
                                visitArrayInstruction(arg0: com.sun.org.apache.bcel.internal.generic.ArrayInstruction): void
                                visitAllocationInstruction(arg0: com.sun.org.apache.bcel.internal.generic.AllocationInstruction): void
                                visitReturnInstruction(arg0: com.sun.org.apache.bcel.internal.generic.ReturnInstruction): void
                                visitFieldOrMethod(arg0: com.sun.org.apache.bcel.internal.generic.FieldOrMethod): void
                                visitConstantPushInstruction(arg0: com.sun.org.apache.bcel.internal.generic.ConstantPushInstruction | com.sun.org.apache.bcel.internal.generic.ConstantPushInstruction$$Lambda): void
                                visitExceptionThrower(arg0: com.sun.org.apache.bcel.internal.generic.ExceptionThrower | com.sun.org.apache.bcel.internal.generic.ExceptionThrower$$Lambda): void
                                visitLoadInstruction(arg0: com.sun.org.apache.bcel.internal.generic.LoadInstruction): void
                                visitVariableLengthInstruction(arg0: com.sun.org.apache.bcel.internal.generic.VariableLengthInstruction): void
                                visitStackProducer(arg0: com.sun.org.apache.bcel.internal.generic.StackProducer | com.sun.org.apache.bcel.internal.generic.StackProducer$$Lambda): void
                                visitStackConsumer(arg0: com.sun.org.apache.bcel.internal.generic.StackConsumer | com.sun.org.apache.bcel.internal.generic.StackConsumer$$Lambda): void
                                visitACONST_NULL(arg0: com.sun.org.apache.bcel.internal.generic.ACONST_NULL): void
                                visitGETSTATIC(arg0: com.sun.org.apache.bcel.internal.generic.GETSTATIC): void
                                visitIF_ICMPLT(arg0: com.sun.org.apache.bcel.internal.generic.IF_ICMPLT): void
                                visitMONITOREXIT(arg0: com.sun.org.apache.bcel.internal.generic.MONITOREXIT): void
                                visitIFLT(arg0: com.sun.org.apache.bcel.internal.generic.IFLT): void
                                visitLSTORE(arg0: com.sun.org.apache.bcel.internal.generic.LSTORE): void
                                visitPOP2(arg0: com.sun.org.apache.bcel.internal.generic.POP2): void
                                visitBASTORE(arg0: com.sun.org.apache.bcel.internal.generic.BASTORE): void
                                visitISTORE(arg0: com.sun.org.apache.bcel.internal.generic.ISTORE): void
                                visitCHECKCAST(arg0: com.sun.org.apache.bcel.internal.generic.CHECKCAST): void
                                visitFCMPG(arg0: com.sun.org.apache.bcel.internal.generic.FCMPG): void
                                visitI2F(arg0: com.sun.org.apache.bcel.internal.generic.I2F): void
                                visitATHROW(arg0: com.sun.org.apache.bcel.internal.generic.ATHROW): void
                                visitDCMPL(arg0: com.sun.org.apache.bcel.internal.generic.DCMPL): void
                                visitARRAYLENGTH(arg0: com.sun.org.apache.bcel.internal.generic.ARRAYLENGTH): void
                                visitDUP(arg0: com.sun.org.apache.bcel.internal.generic.DUP): void
                                visitINVOKESTATIC(arg0: com.sun.org.apache.bcel.internal.generic.INVOKESTATIC): void
                                visitLCONST(arg0: com.sun.org.apache.bcel.internal.generic.LCONST): void
                                visitDREM(arg0: com.sun.org.apache.bcel.internal.generic.DREM): void
                                visitIFGE(arg0: com.sun.org.apache.bcel.internal.generic.IFGE): void
                                visitCALOAD(arg0: com.sun.org.apache.bcel.internal.generic.CALOAD): void
                                visitLASTORE(arg0: com.sun.org.apache.bcel.internal.generic.LASTORE): void
                                visitI2D(arg0: com.sun.org.apache.bcel.internal.generic.I2D): void
                                visitDADD(arg0: com.sun.org.apache.bcel.internal.generic.DADD): void
                                visitINVOKESPECIAL(arg0: com.sun.org.apache.bcel.internal.generic.INVOKESPECIAL): void
                                visitIAND(arg0: com.sun.org.apache.bcel.internal.generic.IAND): void
                                visitPUTFIELD(arg0: com.sun.org.apache.bcel.internal.generic.PUTFIELD): void
                                visitILOAD(arg0: com.sun.org.apache.bcel.internal.generic.ILOAD): void
                                visitDLOAD(arg0: com.sun.org.apache.bcel.internal.generic.DLOAD): void
                                visitDCONST(arg0: com.sun.org.apache.bcel.internal.generic.DCONST): void
                                visitNEW(arg0: com.sun.org.apache.bcel.internal.generic.NEW): void
                                visitIFNULL(arg0: com.sun.org.apache.bcel.internal.generic.IFNULL): void
                                visitLSUB(arg0: com.sun.org.apache.bcel.internal.generic.LSUB): void
                                visitL2I(arg0: com.sun.org.apache.bcel.internal.generic.L2I): void
                                visitISHR(arg0: com.sun.org.apache.bcel.internal.generic.ISHR): void
                                visitTABLESWITCH(arg0: com.sun.org.apache.bcel.internal.generic.TABLESWITCH): void
                                visitIINC(arg0: com.sun.org.apache.bcel.internal.generic.IINC): void
                                visitDRETURN(arg0: com.sun.org.apache.bcel.internal.generic.DRETURN): void
                                visitFSTORE(arg0: com.sun.org.apache.bcel.internal.generic.FSTORE): void
                                visitDASTORE(arg0: com.sun.org.apache.bcel.internal.generic.DASTORE): void
                                visitIALOAD(arg0: com.sun.org.apache.bcel.internal.generic.IALOAD): void
                                visitDDIV(arg0: com.sun.org.apache.bcel.internal.generic.DDIV): void
                                visitIF_ICMPGE(arg0: com.sun.org.apache.bcel.internal.generic.IF_ICMPGE): void
                                visitLAND(arg0: com.sun.org.apache.bcel.internal.generic.LAND): void
                                visitIDIV(arg0: com.sun.org.apache.bcel.internal.generic.IDIV): void
                                visitLOR(arg0: com.sun.org.apache.bcel.internal.generic.LOR): void
                                visitCASTORE(arg0: com.sun.org.apache.bcel.internal.generic.CASTORE): void
                                visitFREM(arg0: com.sun.org.apache.bcel.internal.generic.FREM): void
                                visitLDC(arg0: com.sun.org.apache.bcel.internal.generic.LDC): void
                                visitBIPUSH(arg0: com.sun.org.apache.bcel.internal.generic.BIPUSH): void
                                visitDSTORE(arg0: com.sun.org.apache.bcel.internal.generic.DSTORE): void
                                visitF2L(arg0: com.sun.org.apache.bcel.internal.generic.F2L): void
                                visitFMUL(arg0: com.sun.org.apache.bcel.internal.generic.FMUL): void
                                visitLLOAD(arg0: com.sun.org.apache.bcel.internal.generic.LLOAD): void
                                visitJSR(arg0: com.sun.org.apache.bcel.internal.generic.JSR): void
                                visitFSUB(arg0: com.sun.org.apache.bcel.internal.generic.FSUB): void
                                visitSASTORE(arg0: com.sun.org.apache.bcel.internal.generic.SASTORE): void
                                visitALOAD(arg0: com.sun.org.apache.bcel.internal.generic.ALOAD): void
                                visitDUP2_X2(arg0: com.sun.org.apache.bcel.internal.generic.DUP2_X2): void
                                visitRETURN(arg0: com.sun.org.apache.bcel.internal.generic.RETURN): void
                                visitDALOAD(arg0: com.sun.org.apache.bcel.internal.generic.DALOAD): void
                                visitSIPUSH(arg0: com.sun.org.apache.bcel.internal.generic.SIPUSH): void
                                visitDSUB(arg0: com.sun.org.apache.bcel.internal.generic.DSUB): void
                                visitL2F(arg0: com.sun.org.apache.bcel.internal.generic.L2F): void
                                visitIF_ICMPGT(arg0: com.sun.org.apache.bcel.internal.generic.IF_ICMPGT): void
                                visitF2D(arg0: com.sun.org.apache.bcel.internal.generic.F2D): void
                                visitI2L(arg0: com.sun.org.apache.bcel.internal.generic.I2L): void
                                visitIF_ACMPNE(arg0: com.sun.org.apache.bcel.internal.generic.IF_ACMPNE): void
                                visitPOP(arg0: com.sun.org.apache.bcel.internal.generic.POP): void
                                visitI2S(arg0: com.sun.org.apache.bcel.internal.generic.I2S): void
                                visitIFEQ(arg0: com.sun.org.apache.bcel.internal.generic.IFEQ): void
                                visitSWAP(arg0: com.sun.org.apache.bcel.internal.generic.SWAP): void
                                visitIOR(arg0: com.sun.org.apache.bcel.internal.generic.IOR): void
                                visitIREM(arg0: com.sun.org.apache.bcel.internal.generic.IREM): void
                                visitIASTORE(arg0: com.sun.org.apache.bcel.internal.generic.IASTORE): void
                                visitNEWARRAY(arg0: com.sun.org.apache.bcel.internal.generic.NEWARRAY): void
                                visitINVOKEINTERFACE(arg0: com.sun.org.apache.bcel.internal.generic.INVOKEINTERFACE): void
                                visitINEG(arg0: com.sun.org.apache.bcel.internal.generic.INEG): void
                                visitLCMP(arg0: com.sun.org.apache.bcel.internal.generic.LCMP): void
                                visitJSR_W(arg0: com.sun.org.apache.bcel.internal.generic.JSR_W): void
                                visitMULTIANEWARRAY(arg0: com.sun.org.apache.bcel.internal.generic.MULTIANEWARRAY): void
                                visitDUP_X2(arg0: com.sun.org.apache.bcel.internal.generic.DUP_X2): void
                                visitSALOAD(arg0: com.sun.org.apache.bcel.internal.generic.SALOAD): void
                                visitIFNONNULL(arg0: com.sun.org.apache.bcel.internal.generic.IFNONNULL): void
                                visitDMUL(arg0: com.sun.org.apache.bcel.internal.generic.DMUL): void
                                visitIFNE(arg0: com.sun.org.apache.bcel.internal.generic.IFNE): void
                                visitIF_ICMPLE(arg0: com.sun.org.apache.bcel.internal.generic.IF_ICMPLE): void
                                visitLDC2_W(arg0: com.sun.org.apache.bcel.internal.generic.LDC2_W): void
                                visitGETFIELD(arg0: com.sun.org.apache.bcel.internal.generic.GETFIELD): void
                                visitLADD(arg0: com.sun.org.apache.bcel.internal.generic.LADD): void
                                visitNOP(arg0: com.sun.org.apache.bcel.internal.generic.NOP): void
                                visitFALOAD(arg0: com.sun.org.apache.bcel.internal.generic.FALOAD): void
                                visitINSTANCEOF(arg0: com.sun.org.apache.bcel.internal.generic.INSTANCEOF): void
                                visitIFLE(arg0: com.sun.org.apache.bcel.internal.generic.IFLE): void
                                visitLXOR(arg0: com.sun.org.apache.bcel.internal.generic.LXOR): void
                                visitLRETURN(arg0: com.sun.org.apache.bcel.internal.generic.LRETURN): void
                                visitFCONST(arg0: com.sun.org.apache.bcel.internal.generic.FCONST): void
                                visitIUSHR(arg0: com.sun.org.apache.bcel.internal.generic.IUSHR): void
                                visitBALOAD(arg0: com.sun.org.apache.bcel.internal.generic.BALOAD): void
                                visitDUP2(arg0: com.sun.org.apache.bcel.internal.generic.DUP2): void
                                visitIF_ACMPEQ(arg0: com.sun.org.apache.bcel.internal.generic.IF_ACMPEQ): void
                                visitIMPDEP1(arg0: com.sun.org.apache.bcel.internal.generic.IMPDEP1): void
                                visitMONITORENTER(arg0: com.sun.org.apache.bcel.internal.generic.MONITORENTER): void
                                visitLSHL(arg0: com.sun.org.apache.bcel.internal.generic.LSHL): void
                                visitDCMPG(arg0: com.sun.org.apache.bcel.internal.generic.DCMPG): void
                                visitD2L(arg0: com.sun.org.apache.bcel.internal.generic.D2L): void
                                visitIMPDEP2(arg0: com.sun.org.apache.bcel.internal.generic.IMPDEP2): void
                                visitL2D(arg0: com.sun.org.apache.bcel.internal.generic.L2D): void
                                visitRET(arg0: com.sun.org.apache.bcel.internal.generic.RET): void
                                visitIFGT(arg0: com.sun.org.apache.bcel.internal.generic.IFGT): void
                                visitIXOR(arg0: com.sun.org.apache.bcel.internal.generic.IXOR): void
                                visitINVOKEVIRTUAL(arg0: com.sun.org.apache.bcel.internal.generic.INVOKEVIRTUAL): void
                                visitFASTORE(arg0: com.sun.org.apache.bcel.internal.generic.FASTORE): void
                                visitIRETURN(arg0: com.sun.org.apache.bcel.internal.generic.IRETURN): void
                                visitIF_ICMPNE(arg0: com.sun.org.apache.bcel.internal.generic.IF_ICMPNE): void
                                visitFLOAD(arg0: com.sun.org.apache.bcel.internal.generic.FLOAD): void
                                visitLDIV(arg0: com.sun.org.apache.bcel.internal.generic.LDIV): void
                                visitPUTSTATIC(arg0: com.sun.org.apache.bcel.internal.generic.PUTSTATIC): void
                                visitAALOAD(arg0: com.sun.org.apache.bcel.internal.generic.AALOAD): void
                                visitD2I(arg0: com.sun.org.apache.bcel.internal.generic.D2I): void
                                visitIF_ICMPEQ(arg0: com.sun.org.apache.bcel.internal.generic.IF_ICMPEQ): void
                                visitAASTORE(arg0: com.sun.org.apache.bcel.internal.generic.AASTORE): void
                                visitARETURN(arg0: com.sun.org.apache.bcel.internal.generic.ARETURN): void
                                visitDUP2_X1(arg0: com.sun.org.apache.bcel.internal.generic.DUP2_X1): void
                                visitFNEG(arg0: com.sun.org.apache.bcel.internal.generic.FNEG): void
                                visitGOTO_W(arg0: com.sun.org.apache.bcel.internal.generic.GOTO_W): void
                                visitD2F(arg0: com.sun.org.apache.bcel.internal.generic.D2F): void
                                visitGOTO(arg0: com.sun.org.apache.bcel.internal.generic.GOTO): void
                                visitISUB(arg0: com.sun.org.apache.bcel.internal.generic.ISUB): void
                                visitF2I(arg0: com.sun.org.apache.bcel.internal.generic.F2I): void
                                visitDNEG(arg0: com.sun.org.apache.bcel.internal.generic.DNEG): void
                                visitICONST(arg0: com.sun.org.apache.bcel.internal.generic.ICONST): void
                                visitFDIV(arg0: com.sun.org.apache.bcel.internal.generic.FDIV): void
                                visitI2B(arg0: com.sun.org.apache.bcel.internal.generic.I2B): void
                                visitLNEG(arg0: com.sun.org.apache.bcel.internal.generic.LNEG): void
                                visitLREM(arg0: com.sun.org.apache.bcel.internal.generic.LREM): void
                                visitIMUL(arg0: com.sun.org.apache.bcel.internal.generic.IMUL): void
                                visitIADD(arg0: com.sun.org.apache.bcel.internal.generic.IADD): void
                                visitLSHR(arg0: com.sun.org.apache.bcel.internal.generic.LSHR): void
                                visitLOOKUPSWITCH(arg0: com.sun.org.apache.bcel.internal.generic.LOOKUPSWITCH): void
                                visitDUP_X1(arg0: com.sun.org.apache.bcel.internal.generic.DUP_X1): void
                                visitFCMPL(arg0: com.sun.org.apache.bcel.internal.generic.FCMPL): void
                                visitI2C(arg0: com.sun.org.apache.bcel.internal.generic.I2C): void
                                visitLMUL(arg0: com.sun.org.apache.bcel.internal.generic.LMUL): void
                                visitLUSHR(arg0: com.sun.org.apache.bcel.internal.generic.LUSHR): void
                                visitISHL(arg0: com.sun.org.apache.bcel.internal.generic.ISHL): void
                                visitLALOAD(arg0: com.sun.org.apache.bcel.internal.generic.LALOAD): void
                                visitASTORE(arg0: com.sun.org.apache.bcel.internal.generic.ASTORE): void
                                visitANEWARRAY(arg0: com.sun.org.apache.bcel.internal.generic.ANEWARRAY): void
                                visitFRETURN(arg0: com.sun.org.apache.bcel.internal.generic.FRETURN): void
                                visitFADD(arg0: com.sun.org.apache.bcel.internal.generic.FADD): void
                                visitBREAKPOINT(arg0: com.sun.org.apache.bcel.internal.generic.BREAKPOINT): void
                            }
                        }
                    }
                }
            }
        }
    }
}