declare namespace com {
    namespace sun {
        namespace xml {
            namespace internal {
                namespace ws {
                    namespace org {
                        namespace objectweb {
                            namespace asm {
interface Opcodes {
    V1_1: int
    V1_2: int
    V1_3: int
    V1_4: int
    V1_5: int
    V1_6: int
    ACC_PUBLIC: int
    ACC_PRIVATE: int
    ACC_PROTECTED: int
    ACC_STATIC: int
    ACC_FINAL: int
    ACC_SUPER: int
    ACC_SYNCHRONIZED: int
    ACC_VOLATILE: int
    ACC_BRIDGE: int
    ACC_VARARGS: int
    ACC_TRANSIENT: int
    ACC_NATIVE: int
    ACC_INTERFACE: int
    ACC_ABSTRACT: int
    ACC_STRICT: int
    ACC_SYNTHETIC: int
    ACC_ANNOTATION: int
    ACC_ENUM: int
    ACC_DEPRECATED: int
    T_BOOLEAN: int
    T_CHAR: int
    T_FLOAT: int
    T_DOUBLE: int
    T_BYTE: int
    T_SHORT: int
    T_INT: int
    T_LONG: int
    F_NEW: int
    F_FULL: int
    F_APPEND: int
    F_CHOP: int
    F_SAME: int
    F_SAME1: int
    TOP: java.lang.Integer
    INTEGER: java.lang.Integer
    FLOAT: java.lang.Integer
    DOUBLE: java.lang.Integer
    LONG: java.lang.Integer
    NULL: java.lang.Integer
    UNINITIALIZED_THIS: java.lang.Integer
    NOP: int
    ACONST_NULL: int
    ICONST_M1: int
    ICONST_0: int
    ICONST_1: int
    ICONST_2: int
    ICONST_3: int
    ICONST_4: int
    ICONST_5: int
    LCONST_0: int
    LCONST_1: int
    FCONST_0: int
    FCONST_1: int
    FCONST_2: int
    DCONST_0: int
    DCONST_1: int
    BIPUSH: int
    SIPUSH: int
    LDC: int
    ILOAD: int
    LLOAD: int
    FLOAD: int
    DLOAD: int
    ALOAD: int
    IALOAD: int
    LALOAD: int
    FALOAD: int
    DALOAD: int
    AALOAD: int
    BALOAD: int
    CALOAD: int
    SALOAD: int
    ISTORE: int
    LSTORE: int
    FSTORE: int
    DSTORE: int
    ASTORE: int
    IASTORE: int
    LASTORE: int
    FASTORE: int
    DASTORE: int
    AASTORE: int
    BASTORE: int
    CASTORE: int
    SASTORE: int
    POP: int
    POP2: int
    DUP: int
    DUP_X1: int
    DUP_X2: int
    DUP2: int
    DUP2_X1: int
    DUP2_X2: int
    SWAP: int
    IADD: int
    LADD: int
    FADD: int
    DADD: int
    ISUB: int
    LSUB: int
    FSUB: int
    DSUB: int
    IMUL: int
    LMUL: int
    FMUL: int
    DMUL: int
    IDIV: int
    LDIV: int
    FDIV: int
    DDIV: int
    IREM: int
    LREM: int
    FREM: int
    DREM: int
    INEG: int
    LNEG: int
    FNEG: int
    DNEG: int
    ISHL: int
    LSHL: int
    ISHR: int
    LSHR: int
    IUSHR: int
    LUSHR: int
    IAND: int
    LAND: int
    IOR: int
    LOR: int
    IXOR: int
    LXOR: int
    IINC: int
    I2L: int
    I2F: int
    I2D: int
    L2I: int
    L2F: int
    L2D: int
    F2I: int
    F2L: int
    F2D: int
    D2I: int
    D2L: int
    D2F: int
    I2B: int
    I2C: int
    I2S: int
    LCMP: int
    FCMPL: int
    FCMPG: int
    DCMPL: int
    DCMPG: int
    IFEQ: int
    IFNE: int
    IFLT: int
    IFGE: int
    IFGT: int
    IFLE: int
    IF_ICMPEQ: int
    IF_ICMPNE: int
    IF_ICMPLT: int
    IF_ICMPGE: int
    IF_ICMPGT: int
    IF_ICMPLE: int
    IF_ACMPEQ: int
    IF_ACMPNE: int
    GOTO: int
    JSR: int
    RET: int
    TABLESWITCH: int
    LOOKUPSWITCH: int
    IRETURN: int
    LRETURN: int
    FRETURN: int
    DRETURN: int
    ARETURN: int
    RETURN: int
    GETSTATIC: int
    PUTSTATIC: int
    GETFIELD: int
    PUTFIELD: int
    INVOKEVIRTUAL: int
    INVOKESPECIAL: int
    INVOKESTATIC: int
    INVOKEINTERFACE: int
    NEW: int
    NEWARRAY: int
    ANEWARRAY: int
    ARRAYLENGTH: int
    ATHROW: int
    CHECKCAST: int
    INSTANCEOF: int
    MONITORENTER: int
    MONITOREXIT: int
    MULTIANEWARRAY: int
    IFNULL: int
    IFNONNULL: int
}

                            }
                        }
                    }
                }
            }
        }
    }
}