declare namespace com {
    namespace sun {
        namespace java {
            namespace util {
                namespace jar {
                    namespace pack {
class Constants {
    public static JAVA_MAGIC: int
    public static JAVA_MIN_CLASS_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static JAVA5_MAX_CLASS_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static JAVA6_MAX_CLASS_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static JAVA7_MAX_CLASS_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static JAVA8_MAX_CLASS_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static JAVA_PACKAGE_MAGIC: int
    public static JAVA5_PACKAGE_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static JAVA6_PACKAGE_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static JAVA7_PACKAGE_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static JAVA8_PACKAGE_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static JAVA_MAX_CLASS_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static MAX_PACKAGE_VERSION: com.sun.java.util.jar.pack.Package$Version
    public static CONSTANT_POOL_INDEX_LIMIT: int
    public static CONSTANT_POOL_NARROW_LIMIT: int
    public static JAVA_SIGNATURE_CHARS: string
    public static CONSTANT_Utf8: byte
    public static CONSTANT_unused2: byte
    public static CONSTANT_Integer: byte
    public static CONSTANT_Float: byte
    public static CONSTANT_Long: byte
    public static CONSTANT_Double: byte
    public static CONSTANT_Class: byte
    public static CONSTANT_String: byte
    public static CONSTANT_Fieldref: byte
    public static CONSTANT_Methodref: byte
    public static CONSTANT_InterfaceMethodref: byte
    public static CONSTANT_NameandType: byte
    public static CONSTANT_unused13: byte
    public static CONSTANT_unused14: byte
    public static CONSTANT_MethodHandle: byte
    public static CONSTANT_MethodType: byte
    public static CONSTANT_unused17: byte
    public static CONSTANT_InvokeDynamic: byte
    public static CONSTANT_None: byte
    public static CONSTANT_Signature: byte
    public static CONSTANT_BootstrapMethod: byte
    public static CONSTANT_Limit: byte
    public static CONSTANT_All: byte
    public static CONSTANT_LoadableValue: byte
    public static CONSTANT_AnyMember: byte
    public static CONSTANT_FieldSpecific: byte
    public static CONSTANT_GroupFirst: byte
    public static CONSTANT_GroupLimit: byte
    public static REF_getField: byte
    public static REF_getStatic: byte
    public static REF_putField: byte
    public static REF_putStatic: byte
    public static REF_invokeVirtual: byte
    public static REF_invokeStatic: byte
    public static REF_invokeSpecial: byte
    public static REF_newInvokeSpecial: byte
    public static REF_invokeInterface: byte
    public static ACC_IC_LONG_FORM: int
    public static ATTR_CONTEXT_CLASS: int
    public static ATTR_CONTEXT_FIELD: int
    public static ATTR_CONTEXT_METHOD: int
    public static ATTR_CONTEXT_CODE: int
    public static ATTR_CONTEXT_LIMIT: int
    public static ATTR_CONTEXT_NAME: java.lang.String[]
    public static X_ATTR_OVERFLOW: int
    public static CLASS_ATTR_SourceFile: int
    public static METHOD_ATTR_Code: int
    public static FIELD_ATTR_ConstantValue: int
    public static CLASS_ATTR_EnclosingMethod: int
    public static METHOD_ATTR_Exceptions: int
    public static X_ATTR_Signature: int
    public static X_ATTR_Deprecated: int
    public static X_ATTR_RuntimeVisibleAnnotations: int
    public static X_ATTR_RuntimeInvisibleAnnotations: int
    public static METHOD_ATTR_RuntimeVisibleParameterAnnotations: int
    public static CLASS_ATTR_InnerClasses: int
    public static METHOD_ATTR_RuntimeInvisibleParameterAnnotations: int
    public static CLASS_ATTR_ClassFile_version: int
    public static METHOD_ATTR_AnnotationDefault: int
    public static METHOD_ATTR_MethodParameters: int
    public static X_ATTR_RuntimeVisibleTypeAnnotations: int
    public static X_ATTR_RuntimeInvisibleTypeAnnotations: int
    public static CODE_ATTR_StackMapTable: int
    public static CODE_ATTR_LineNumberTable: int
    public static CODE_ATTR_LocalVariableTable: int
    public static CODE_ATTR_LocalVariableTypeTable: int
    public static FO_DEFLATE_HINT: int
    public static FO_IS_CLASS_STUB: int
    public static AO_HAVE_SPECIAL_FORMATS: int
    public static AO_HAVE_CP_NUMBERS: int
    public static AO_HAVE_ALL_CODE_FLAGS: int
    public static AO_HAVE_CP_EXTRAS: int
    public static AO_HAVE_FILE_HEADERS: int
    public static AO_DEFLATE_HINT: int
    public static AO_HAVE_FILE_MODTIME: int
    public static AO_HAVE_FILE_OPTIONS: int
    public static AO_HAVE_FILE_SIZE_HI: int
    public static AO_HAVE_CLASS_FLAGS_HI: int
    public static AO_HAVE_FIELD_FLAGS_HI: int
    public static AO_HAVE_METHOD_FLAGS_HI: int
    public static AO_HAVE_CODE_FLAGS_HI: int
    public static AO_UNUSED_MBZ: int
    public static LG_AO_HAVE_XXX_FLAGS_HI: int
    public static NO_MODTIME: int
    public static noInts: int[]
    public static noBytes: byte[]
    public static noValues: java.lang.Object[]
    public static noStrings: java.lang.String[]
    public static emptyList: java.util.List<java.lang.Object>
    public static _meta_default: int
    public static _meta_canon_min: int
    public static _meta_canon_max: int
    public static _meta_arb: int
    public static _meta_run: int
    public static _meta_pop: int
    public static _meta_limit: int
    public static _nop: int
    public static _aconst_null: int
    public static _iconst_m1: int
    public static _iconst_0: int
    public static _iconst_1: int
    public static _iconst_2: int
    public static _iconst_3: int
    public static _iconst_4: int
    public static _iconst_5: int
    public static _lconst_0: int
    public static _lconst_1: int
    public static _fconst_0: int
    public static _fconst_1: int
    public static _fconst_2: int
    public static _dconst_0: int
    public static _dconst_1: int
    public static _bipush: int
    public static _sipush: int
    public static _ldc: int
    public static _ldc_w: int
    public static _ldc2_w: int
    public static _iload: int
    public static _lload: int
    public static _fload: int
    public static _dload: int
    public static _aload: int
    public static _iload_0: int
    public static _iload_1: int
    public static _iload_2: int
    public static _iload_3: int
    public static _lload_0: int
    public static _lload_1: int
    public static _lload_2: int
    public static _lload_3: int
    public static _fload_0: int
    public static _fload_1: int
    public static _fload_2: int
    public static _fload_3: int
    public static _dload_0: int
    public static _dload_1: int
    public static _dload_2: int
    public static _dload_3: int
    public static _aload_0: int
    public static _aload_1: int
    public static _aload_2: int
    public static _aload_3: int
    public static _iaload: int
    public static _laload: int
    public static _faload: int
    public static _daload: int
    public static _aaload: int
    public static _baload: int
    public static _caload: int
    public static _saload: int
    public static _istore: int
    public static _lstore: int
    public static _fstore: int
    public static _dstore: int
    public static _astore: int
    public static _istore_0: int
    public static _istore_1: int
    public static _istore_2: int
    public static _istore_3: int
    public static _lstore_0: int
    public static _lstore_1: int
    public static _lstore_2: int
    public static _lstore_3: int
    public static _fstore_0: int
    public static _fstore_1: int
    public static _fstore_2: int
    public static _fstore_3: int
    public static _dstore_0: int
    public static _dstore_1: int
    public static _dstore_2: int
    public static _dstore_3: int
    public static _astore_0: int
    public static _astore_1: int
    public static _astore_2: int
    public static _astore_3: int
    public static _iastore: int
    public static _lastore: int
    public static _fastore: int
    public static _dastore: int
    public static _aastore: int
    public static _bastore: int
    public static _castore: int
    public static _sastore: int
    public static _pop: int
    public static _pop2: int
    public static _dup: int
    public static _dup_x1: int
    public static _dup_x2: int
    public static _dup2: int
    public static _dup2_x1: int
    public static _dup2_x2: int
    public static _swap: int
    public static _iadd: int
    public static _ladd: int
    public static _fadd: int
    public static _dadd: int
    public static _isub: int
    public static _lsub: int
    public static _fsub: int
    public static _dsub: int
    public static _imul: int
    public static _lmul: int
    public static _fmul: int
    public static _dmul: int
    public static _idiv: int
    public static _ldiv: int
    public static _fdiv: int
    public static _ddiv: int
    public static _irem: int
    public static _lrem: int
    public static _frem: int
    public static _drem: int
    public static _ineg: int
    public static _lneg: int
    public static _fneg: int
    public static _dneg: int
    public static _ishl: int
    public static _lshl: int
    public static _ishr: int
    public static _lshr: int
    public static _iushr: int
    public static _lushr: int
    public static _iand: int
    public static _land: int
    public static _ior: int
    public static _lor: int
    public static _ixor: int
    public static _lxor: int
    public static _iinc: int
    public static _i2l: int
    public static _i2f: int
    public static _i2d: int
    public static _l2i: int
    public static _l2f: int
    public static _l2d: int
    public static _f2i: int
    public static _f2l: int
    public static _f2d: int
    public static _d2i: int
    public static _d2l: int
    public static _d2f: int
    public static _i2b: int
    public static _i2c: int
    public static _i2s: int
    public static _lcmp: int
    public static _fcmpl: int
    public static _fcmpg: int
    public static _dcmpl: int
    public static _dcmpg: int
    public static _ifeq: int
    public static _ifne: int
    public static _iflt: int
    public static _ifge: int
    public static _ifgt: int
    public static _ifle: int
    public static _if_icmpeq: int
    public static _if_icmpne: int
    public static _if_icmplt: int
    public static _if_icmpge: int
    public static _if_icmpgt: int
    public static _if_icmple: int
    public static _if_acmpeq: int
    public static _if_acmpne: int
    public static _goto: int
    public static _jsr: int
    public static _ret: int
    public static _tableswitch: int
    public static _lookupswitch: int
    public static _ireturn: int
    public static _lreturn: int
    public static _freturn: int
    public static _dreturn: int
    public static _areturn: int
    public static _return: int
    public static _getstatic: int
    public static _putstatic: int
    public static _getfield: int
    public static _putfield: int
    public static _invokevirtual: int
    public static _invokespecial: int
    public static _invokestatic: int
    public static _invokeinterface: int
    public static _invokedynamic: int
    public static _new: int
    public static _newarray: int
    public static _anewarray: int
    public static _arraylength: int
    public static _athrow: int
    public static _checkcast: int
    public static _instanceof: int
    public static _monitorenter: int
    public static _monitorexit: int
    public static _wide: int
    public static _multianewarray: int
    public static _ifnull: int
    public static _ifnonnull: int
    public static _goto_w: int
    public static _jsr_w: int
    public static _bytecode_limit: int
    public static _end_marker: int
    public static _byte_escape: int
    public static _ref_escape: int
    public static _first_linker_op: int
    public static _last_linker_op: int
    public static _num_linker_ops: int
    public static _self_linker_op: int
    public static _self_linker_aload_flag: int
    public static _self_linker_super_flag: int
    public static _self_linker_limit: int
    public static _invokeinit_op: int
    public static _invokeinit_self_option: int
    public static _invokeinit_super_option: int
    public static _invokeinit_new_option: int
    public static _invokeinit_limit: int
    public static _pseudo_instruction_limit: int
    public static _xldc_op: int
    public static _sldc: int
    public static _cldc: int
    public static _ildc: int
    public static _fldc: int
    public static _sldc_w: int
    public static _cldc_w: int
    public static _ildc_w: int
    public static _fldc_w: int
    public static _lldc2_w: int
    public static _dldc2_w: int
    public static _qldc: int
    public static _qldc_w: int
    public static _xldc_limit: int
    public static _invoke_int_op: int
    public static _invokespecial_int: int
    public static _invokestatic_int: int
    public static _invoke_int_limit: int
    public static class: java.lang.Class<any>
}

                    }
                }
            }
        }
    }
}