declare namespace com {
    namespace sun {
        namespace org {
            namespace apache {
                namespace xerces {
                    namespace internal {
                        namespace impl {
                            class Constants {
                                public static NS_XMLSCHEMA: string
                                public static NS_DTD: string
                                public static SUN_SCHEMA_FEATURE_PREFIX: string
                                public static SUN_REPORT_IGNORED_ELEMENT_CONTENT_WHITESPACE: string
                                public static ZEPHYR_PROPERTY_PREFIX: string
                                public static STAX_PROPERTIES: string
                                public static STAX_ENTITY_RESOLVER_PROPERTY: string
                                public static STAX_REPORT_CDATA_EVENT: string
                                public static READER_IN_DEFINED_STATE: string
                                public static ADD_NAMESPACE_DECL_AS_ATTRIBUTE: string
                                public static ESCAPE_CHARACTERS: string
                                public static REUSE_INSTANCE: string
                                public static SUN_DOM_PROPERTY_PREFIX: string
                                public static SUN_DOM_ANCESTOR_CHECCK: string
                                public static IGNORE_EXTERNAL_DTD: string
                                public static SAX_FEATURE_PREFIX: string
                                public static NAMESPACES_FEATURE: string
                                public static NAMESPACE_PREFIXES_FEATURE: string
                                public static STRING_INTERNING_FEATURE: string
                                public static VALIDATION_FEATURE: string
                                public static EXTERNAL_GENERAL_ENTITIES_FEATURE: string
                                public static EXTERNAL_PARAMETER_ENTITIES_FEATURE: string
                                public static LEXICAL_HANDLER_PARAMETER_ENTITIES_FEATURE: string
                                public static IS_STANDALONE_FEATURE: string
                                public static RESOLVE_DTD_URIS_FEATURE: string
                                public static USE_ATTRIBUTES2_FEATURE: string
                                public static USE_LOCATOR2_FEATURE: string
                                public static USE_ENTITY_RESOLVER2_FEATURE: string
                                public static UNICODE_NORMALIZATION_CHECKING_FEATURE: string
                                public static XMLNS_URIS_FEATURE: string
                                public static XML_11_FEATURE: string
                                public static ALLOW_DTD_EVENTS_AFTER_ENDDTD_FEATURE: string
                                public static SAX_PROPERTY_PREFIX: string
                                public static DECLARATION_HANDLER_PROPERTY: string
                                public static LEXICAL_HANDLER_PROPERTY: string
                                public static DOM_NODE_PROPERTY: string
                                public static XML_STRING_PROPERTY: string
                                public static FEATURE_SECURE_PROCESSING: string
                                public static ORACLE_FEATURE_SERVICE_MECHANISM: string
                                public static DOCUMENT_XML_VERSION_PROPERTY: string
                                public static JAXP_PROPERTY_PREFIX: string
                                public static SCHEMA_SOURCE: string
                                public static SCHEMA_LANGUAGE: string
                                public static JAXPAPI_PROPERTY_PREFIX: string
                                public static ORACLE_JAXP_PROPERTY_PREFIX: string
                                public static XML_SECURITY_PROPERTY_MANAGER: string
                                public static SP_ACCESS_EXTERNAL_DTD: string
                                public static SP_ACCESS_EXTERNAL_SCHEMA: string
                                public static ACCESS_EXTERNAL_ALL: string
                                public static EXTERNAL_ACCESS_DEFAULT_FSP: string
                                public static EXTERNAL_ACCESS_DEFAULT: string
                                public static IS_JDK8_OR_ABOVE: boolean
                                public static JDK_ENTITY_EXPANSION_LIMIT: string
                                public static JDK_ELEMENT_ATTRIBUTE_LIMIT: string
                                public static JDK_MAX_OCCUR_LIMIT: string
                                public static JDK_TOTAL_ENTITY_SIZE_LIMIT: string
                                public static JDK_GENERAL_ENTITY_SIZE_LIMIT: string
                                public static JDK_ENTITY_REPLACEMENT_LIMIT: string
                                public static JDK_PARAMETER_ENTITY_SIZE_LIMIT: string
                                public static JDK_XML_NAME_LIMIT: string
                                public static JDK_MAX_ELEMENT_DEPTH: string
                                public static JDK_ENTITY_COUNT_INFO: string
                                public static SP_ENTITY_EXPANSION_LIMIT: string
                                public static SP_ELEMENT_ATTRIBUTE_LIMIT: string
                                public static SP_MAX_OCCUR_LIMIT: string
                                public static SP_TOTAL_ENTITY_SIZE_LIMIT: string
                                public static SP_GENERAL_ENTITY_SIZE_LIMIT: string
                                public static SP_ENTITY_REPLACEMENT_LIMIT: string
                                public static SP_PARAMETER_ENTITY_SIZE_LIMIT: string
                                public static SP_XML_NAME_LIMIT: string
                                public static SP_MAX_ELEMENT_DEPTH: string
                                public static ENTITY_EXPANSION_LIMIT: string
                                public static ELEMENT_ATTRIBUTE_LIMIT: string
                                public static MAX_OCCUR_LIMIT: string
                                public static JDK_YES: string
                                public static INCLUDE_COMMENTS_FEATURE: string
                                public static CREATE_CDATA_NODES_FEATURE: string
                                public static LOAD_AS_INFOSET: string
                                public static DOM_CANONICAL_FORM: string
                                public static DOM_CDATA_SECTIONS: string
                                public static DOM_COMMENTS: string
                                public static DOM_CHARSET_OVERRIDES_XML_ENCODING: string
                                public static DOM_DATATYPE_NORMALIZATION: string
                                public static DOM_ENTITIES: string
                                public static DOM_INFOSET: string
                                public static DOM_NAMESPACES: string
                                public static DOM_NAMESPACE_DECLARATIONS: string
                                public static DOM_SUPPORTED_MEDIATYPES_ONLY: string
                                public static DOM_VALIDATE_IF_SCHEMA: string
                                public static DOM_VALIDATE: string
                                public static DOM_ELEMENT_CONTENT_WHITESPACE: string
                                public static DOM_DISCARD_DEFAULT_CONTENT: string
                                public static DOM_NORMALIZE_CHARACTERS: string
                                public static DOM_CHECK_CHAR_NORMALIZATION: string
                                public static DOM_WELLFORMED: string
                                public static DOM_SPLIT_CDATA: string
                                public static DOM_FORMAT_PRETTY_PRINT: string
                                public static DOM_XMLDECL: string
                                public static DOM_UNKNOWNCHARS: string
                                public static DOM_CERTIFIED: string
                                public static DOM_DISALLOW_DOCTYPE: string
                                public static DOM_IGNORE_UNKNOWN_CHARACTER_DENORMALIZATIONS: string
                                public static DOM_RESOURCE_RESOLVER: string
                                public static DOM_ERROR_HANDLER: string
                                public static DOM_SCHEMA_TYPE: string
                                public static DOM_SCHEMA_LOCATION: string
                                public static DOM_ANCESTOR_CHECCK: string
                                public static DOM_PSVI: string
                                public static XERCES_FEATURE_PREFIX: string
                                public static SCHEMA_VALIDATION_FEATURE: string
                                public static SCHEMA_NORMALIZED_VALUE: string
                                public static SCHEMA_ELEMENT_DEFAULT: string
                                public static SCHEMA_FULL_CHECKING: string
                                public static SCHEMA_AUGMENT_PSVI: string
                                public static DYNAMIC_VALIDATION_FEATURE: string
                                public static WARN_ON_DUPLICATE_ATTDEF_FEATURE: string
                                public static WARN_ON_UNDECLARED_ELEMDEF_FEATURE: string
                                public static WARN_ON_DUPLICATE_ENTITYDEF_FEATURE: string
                                public static ALLOW_JAVA_ENCODINGS_FEATURE: string
                                public static DISALLOW_DOCTYPE_DECL_FEATURE: string
                                public static CONTINUE_AFTER_FATAL_ERROR_FEATURE: string
                                public static LOAD_DTD_GRAMMAR_FEATURE: string
                                public static LOAD_EXTERNAL_DTD_FEATURE: string
                                public static DEFER_NODE_EXPANSION_FEATURE: string
                                public static CREATE_ENTITY_REF_NODES_FEATURE: string
                                public static INCLUDE_IGNORABLE_WHITESPACE: string
                                public static DEFAULT_ATTRIBUTE_VALUES_FEATURE: string
                                public static VALIDATE_CONTENT_MODELS_FEATURE: string
                                public static VALIDATE_DATATYPES_FEATURE: string
                                public static BALANCE_SYNTAX_TREES: string
                                public static NOTIFY_CHAR_REFS_FEATURE: string
                                public static NOTIFY_BUILTIN_REFS_FEATURE: string
                                public static STANDARD_URI_CONFORMANT_FEATURE: string
                                public static GENERATE_SYNTHETIC_ANNOTATIONS_FEATURE: string
                                public static VALIDATE_ANNOTATIONS_FEATURE: string
                                public static HONOUR_ALL_SCHEMALOCATIONS_FEATURE: string
                                public static NAMESPACE_GROWTH_FEATURE: string
                                public static TOLERATE_DUPLICATES_FEATURE: string
                                public static XINCLUDE_FEATURE: string
                                public static XINCLUDE_FIXUP_BASE_URIS_FEATURE: string
                                public static XINCLUDE_FIXUP_LANGUAGE_FEATURE: string
                                public static USE_GRAMMAR_POOL_ONLY_FEATURE: string
                                public static PARSER_SETTINGS: string
                                public static XINCLUDE_AWARE: string
                                public static IGNORE_SCHEMA_LOCATION_HINTS: string
                                public static CHANGE_IGNORABLE_CHARACTERS_INTO_IGNORABLE_WHITESPACES: string
                                public static XERCES_PROPERTY_PREFIX: string
                                public static CURRENT_ELEMENT_NODE_PROPERTY: string
                                public static DOCUMENT_CLASS_NAME_PROPERTY: string
                                public static SYMBOL_TABLE_PROPERTY: string
                                public static ERROR_REPORTER_PROPERTY: string
                                public static ERROR_HANDLER_PROPERTY: string
                                public static XINCLUDE_HANDLER_PROPERTY: string
                                public static XPOINTER_HANDLER_PROPERTY: string
                                public static ENTITY_MANAGER_PROPERTY: string
                                public static BUFFER_SIZE_PROPERTY: string
                                public static SECURITY_MANAGER_PROPERTY: string
                                public static LOCALE_PROPERTY: string
                                public static SECURITY_MANAGER: string
                                public static ENTITY_RESOLVER_PROPERTY: string
                                public static XMLGRAMMAR_POOL_PROPERTY: string
                                public static DATATYPE_VALIDATOR_FACTORY_PROPERTY: string
                                public static DOCUMENT_SCANNER_PROPERTY: string
                                public static DTD_SCANNER_PROPERTY: string
                                public static DTD_PROCESSOR_PROPERTY: string
                                public static VALIDATOR_PROPERTY: string
                                public static DTD_VALIDATOR_PROPERTY: string
                                public static SCHEMA_VALIDATOR_PROPERTY: string
                                public static SCHEMA_LOCATION: string
                                public static SCHEMA_NONS_LOCATION: string
                                public static NAMESPACE_BINDER_PROPERTY: string
                                public static NAMESPACE_CONTEXT_PROPERTY: string
                                public static VALIDATION_MANAGER_PROPERTY: string
                                public static XPOINTER_SCHEMA_PROPERTY: string
                                public static SCHEMA_DV_FACTORY_PROPERTY: string
                                public static ELEMENT_PSVI: string
                                public static ATTRIBUTE_PSVI: string
                                public static ATTRIBUTE_DECLARED: string
                                public static TYPEINFO: string
                                public static ID_ATTRIBUTE: string
                                public static ENTITY_SKIPPED: string
                                public static CHAR_REF_PROBABLE_WS: string
                                public static LAST_ENTITY: string
                                public static XML_VERSION_ERROR: short
                                public static XML_VERSION_1_0: short
                                public static XML_VERSION_1_1: short
                                public static ANONYMOUS_TYPE_NAMESPACE: string
                                public static SCHEMA_1_1_SUPPORT: boolean
                                public static SCHEMA_VERSION_1_0: short
                                public static SCHEMA_VERSION_1_0_EXTENDED: short
                                public static getSAXFeatures(): java.util.Enumeration
                                public static getSAXProperties(): java.util.Enumeration
                                public static getXercesFeatures(): java.util.Enumeration
                                public static getXercesProperties(): java.util.Enumeration
                                public static isJavaVersionAtLeast(arg0: int): boolean
                                public static main(arg0: java.lang.String[]): void
                                public static class: java.lang.Class<any>
                            }
                        }
                    }
                }
            }
        }
    }
}