declare namespace com {
    namespace sun {
        namespace org {
            namespace apache {
                namespace xalan {
                    namespace internal {
                        namespace res {
                            class XSLTErrorResources_zh_CN extends java.util.ListResourceBundle {
                                public static readonly ER_INVALID_NAMESPACE_URI_VALUE_FOR_RESULT_PREFIX: string
                                public static readonly ER_INVALID_NAMESPACE_URI_VALUE_FOR_RESULT_PREFIX_FOR_DEFAULT: string
                                public static readonly ER_NO_CURLYBRACE: string
                                public static readonly ER_FUNCTION_NOT_SUPPORTED: string
                                public static readonly ER_ILLEGAL_ATTRIBUTE: string
                                public static readonly ER_NULL_SOURCENODE_APPLYIMPORTS: string
                                public static readonly ER_CANNOT_ADD: string
                                public static readonly ER_NULL_SOURCENODE_HANDLEAPPLYTEMPLATES: string
                                public static readonly ER_NO_NAME_ATTRIB: string
                                public static readonly ER_TEMPLATE_NOT_FOUND: string
                                public static readonly ER_CANT_RESOLVE_NAME_AVT: string
                                public static readonly ER_REQUIRES_ATTRIB: string
                                public static readonly ER_MUST_HAVE_TEST_ATTRIB: string
                                public static readonly ER_BAD_VAL_ON_LEVEL_ATTRIB: string
                                public static readonly ER_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML: string
                                public static readonly ER_PROCESSINGINSTRUCTION_NOTVALID_NCNAME: string
                                public static readonly ER_NEED_MATCH_ATTRIB: string
                                public static readonly ER_NEED_NAME_OR_MATCH_ATTRIB: string
                                public static readonly ER_CANT_RESOLVE_NSPREFIX: string
                                public static readonly ER_ILLEGAL_VALUE: string
                                public static readonly ER_NO_OWNERDOC: string
                                public static readonly ER_ELEMTEMPLATEELEM_ERR: string
                                public static readonly ER_NULL_CHILD: string
                                public static readonly ER_NEED_SELECT_ATTRIB: string
                                public static readonly ER_NEED_TEST_ATTRIB: string
                                public static readonly ER_NEED_NAME_ATTRIB: string
                                public static readonly ER_NO_CONTEXT_OWNERDOC: string
                                public static readonly ER_COULD_NOT_CREATE_XML_PROC_LIAISON: string
                                public static readonly ER_PROCESS_NOT_SUCCESSFUL: string
                                public static readonly ER_NOT_SUCCESSFUL: string
                                public static readonly ER_ENCODING_NOT_SUPPORTED: string
                                public static readonly ER_COULD_NOT_CREATE_TRACELISTENER: string
                                public static readonly ER_KEY_REQUIRES_NAME_ATTRIB: string
                                public static readonly ER_KEY_REQUIRES_MATCH_ATTRIB: string
                                public static readonly ER_KEY_REQUIRES_USE_ATTRIB: string
                                public static readonly ER_REQUIRES_ELEMENTS_ATTRIB: string
                                public static readonly ER_MISSING_PREFIX_ATTRIB: string
                                public static readonly ER_BAD_STYLESHEET_URL: string
                                public static readonly ER_FILE_NOT_FOUND: string
                                public static readonly ER_IOEXCEPTION: string
                                public static readonly ER_NO_HREF_ATTRIB: string
                                public static readonly ER_STYLESHEET_INCLUDES_ITSELF: string
                                public static readonly ER_PROCESSINCLUDE_ERROR: string
                                public static readonly ER_MISSING_LANG_ATTRIB: string
                                public static readonly ER_MISSING_CONTAINER_ELEMENT_COMPONENT: string
                                public static readonly ER_CAN_ONLY_OUTPUT_TO_ELEMENT: string
                                public static readonly ER_PROCESS_ERROR: string
                                public static readonly ER_UNIMPLNODE_ERROR: string
                                public static readonly ER_NO_SELECT_EXPRESSION: string
                                public static readonly ER_CANNOT_SERIALIZE_XSLPROCESSOR: string
                                public static readonly ER_NO_INPUT_STYLESHEET: string
                                public static readonly ER_FAILED_PROCESS_STYLESHEET: string
                                public static readonly ER_COULDNT_PARSE_DOC: string
                                public static readonly ER_COULDNT_FIND_FRAGMENT: string
                                public static readonly ER_NODE_NOT_ELEMENT: string
                                public static readonly ER_FOREACH_NEED_MATCH_OR_NAME_ATTRIB: string
                                public static readonly ER_TEMPLATES_NEED_MATCH_OR_NAME_ATTRIB: string
                                public static readonly ER_NO_CLONE_OF_DOCUMENT_FRAG: string
                                public static readonly ER_CANT_CREATE_ITEM: string
                                public static readonly ER_XMLSPACE_ILLEGAL_VALUE: string
                                public static readonly ER_NO_XSLKEY_DECLARATION: string
                                public static readonly ER_CANT_CREATE_URL: string
                                public static readonly ER_XSLFUNCTIONS_UNSUPPORTED: string
                                public static readonly ER_PROCESSOR_ERROR: string
                                public static readonly ER_NOT_ALLOWED_INSIDE_STYLESHEET: string
                                public static readonly ER_RESULTNS_NOT_SUPPORTED: string
                                public static readonly ER_DEFAULTSPACE_NOT_SUPPORTED: string
                                public static readonly ER_INDENTRESULT_NOT_SUPPORTED: string
                                public static readonly ER_ILLEGAL_ATTRIB: string
                                public static readonly ER_UNKNOWN_XSL_ELEM: string
                                public static readonly ER_BAD_XSLSORT_USE: string
                                public static readonly ER_MISPLACED_XSLWHEN: string
                                public static readonly ER_XSLWHEN_NOT_PARENTED_BY_XSLCHOOSE: string
                                public static readonly ER_MISPLACED_XSLOTHERWISE: string
                                public static readonly ER_XSLOTHERWISE_NOT_PARENTED_BY_XSLCHOOSE: string
                                public static readonly ER_NOT_ALLOWED_INSIDE_TEMPLATE: string
                                public static readonly ER_UNKNOWN_EXT_NS_PREFIX: string
                                public static readonly ER_IMPORTS_AS_FIRST_ELEM: string
                                public static readonly ER_IMPORTING_ITSELF: string
                                public static readonly ER_XMLSPACE_ILLEGAL_VAL: string
                                public static readonly ER_PROCESSSTYLESHEET_NOT_SUCCESSFUL: string
                                public static readonly ER_SAX_EXCEPTION: string
                                public static readonly ER_XSLT_ERROR: string
                                public static readonly ER_CURRENCY_SIGN_ILLEGAL: string
                                public static readonly ER_DOCUMENT_FUNCTION_INVALID_IN_STYLESHEET_DOM: string
                                public static readonly ER_CANT_RESOLVE_PREFIX_OF_NON_PREFIX_RESOLVER: string
                                public static readonly ER_REDIRECT_COULDNT_GET_FILENAME: string
                                public static readonly ER_CANNOT_BUILD_FORMATTERLISTENER_IN_REDIRECT: string
                                public static readonly ER_INVALID_PREFIX_IN_EXCLUDERESULTPREFIX: string
                                public static readonly ER_MISSING_NS_URI: string
                                public static readonly ER_MISSING_ARG_FOR_OPTION: string
                                public static readonly ER_INVALID_OPTION: string
                                public static readonly ER_MALFORMED_FORMAT_STRING: string
                                public static readonly ER_STYLESHEET_REQUIRES_VERSION_ATTRIB: string
                                public static readonly ER_ILLEGAL_ATTRIBUTE_VALUE: string
                                public static readonly ER_CHOOSE_REQUIRES_WHEN: string
                                public static readonly ER_NO_APPLY_IMPORT_IN_FOR_EACH: string
                                public static readonly ER_CANT_USE_DTM_FOR_OUTPUT: string
                                public static readonly ER_CANT_USE_DTM_FOR_INPUT: string
                                public static readonly ER_CALL_TO_EXT_FAILED: string
                                public static readonly ER_PREFIX_MUST_RESOLVE: string
                                public static readonly ER_INVALID_UTF16_SURROGATE: string
                                public static readonly ER_XSLATTRSET_USED_ITSELF: string
                                public static readonly ER_CANNOT_MIX_XERCESDOM: string
                                public static readonly ER_TOO_MANY_LISTENERS: string
                                public static readonly ER_IN_ELEMTEMPLATEELEM_READOBJECT: string
                                public static readonly ER_DUPLICATE_NAMED_TEMPLATE: string
                                public static readonly ER_INVALID_KEY_CALL: string
                                public static readonly ER_REFERENCING_ITSELF: string
                                public static readonly ER_ILLEGAL_DOMSOURCE_INPUT: string
                                public static readonly ER_CLASS_NOT_FOUND_FOR_OPTION: string
                                public static readonly ER_REQUIRED_ELEM_NOT_FOUND: string
                                public static readonly ER_INPUT_CANNOT_BE_NULL: string
                                public static readonly ER_URI_CANNOT_BE_NULL: string
                                public static readonly ER_FILE_CANNOT_BE_NULL: string
                                public static readonly ER_SOURCE_CANNOT_BE_NULL: string
                                public static readonly ER_CANNOT_INIT_BSFMGR: string
                                public static readonly ER_CANNOT_CMPL_EXTENSN: string
                                public static readonly ER_CANNOT_CREATE_EXTENSN: string
                                public static readonly ER_INSTANCE_MTHD_CALL_REQUIRES: string
                                public static readonly ER_INVALID_ELEMENT_NAME: string
                                public static readonly ER_ELEMENT_NAME_METHOD_STATIC: string
                                public static readonly ER_EXTENSION_FUNC_UNKNOWN: string
                                public static readonly ER_MORE_MATCH_CONSTRUCTOR: string
                                public static readonly ER_MORE_MATCH_METHOD: string
                                public static readonly ER_MORE_MATCH_ELEMENT: string
                                public static readonly ER_INVALID_CONTEXT_PASSED: string
                                public static readonly ER_POOL_EXISTS: string
                                public static readonly ER_NO_DRIVER_NAME: string
                                public static readonly ER_NO_URL: string
                                public static readonly ER_POOL_SIZE_LESSTHAN_ONE: string
                                public static readonly ER_INVALID_DRIVER: string
                                public static readonly ER_NO_STYLESHEETROOT: string
                                public static readonly ER_ILLEGAL_XMLSPACE_VALUE: string
                                public static readonly ER_PROCESSFROMNODE_FAILED: string
                                public static readonly ER_RESOURCE_COULD_NOT_LOAD: string
                                public static readonly ER_BUFFER_SIZE_LESSTHAN_ZERO: string
                                public static readonly ER_UNKNOWN_ERROR_CALLING_EXTENSION: string
                                public static readonly ER_NO_NAMESPACE_DECL: string
                                public static readonly ER_ELEM_CONTENT_NOT_ALLOWED: string
                                public static readonly ER_STYLESHEET_DIRECTED_TERMINATION: string
                                public static readonly ER_ONE_OR_TWO: string
                                public static readonly ER_TWO_OR_THREE: string
                                public static readonly ER_COULD_NOT_LOAD_RESOURCE: string
                                public static readonly ER_CANNOT_INIT_DEFAULT_TEMPLATES: string
                                public static readonly ER_RESULT_NULL: string
                                public static readonly ER_RESULT_COULD_NOT_BE_SET: string
                                public static readonly ER_NO_OUTPUT_SPECIFIED: string
                                public static readonly ER_CANNOT_TRANSFORM_TO_RESULT_TYPE: string
                                public static readonly ER_CANNOT_TRANSFORM_SOURCE_TYPE: string
                                public static readonly ER_NULL_CONTENT_HANDLER: string
                                public static readonly ER_NULL_ERROR_HANDLER: string
                                public static readonly ER_CANNOT_CALL_PARSE: string
                                public static readonly ER_NO_PARENT_FOR_FILTER: string
                                public static readonly ER_NO_STYLESHEET_IN_MEDIA: string
                                public static readonly ER_NO_STYLESHEET_PI: string
                                public static readonly ER_NOT_SUPPORTED: string
                                public static readonly ER_PROPERTY_VALUE_BOOLEAN: string
                                public static readonly ER_COULD_NOT_FIND_EXTERN_SCRIPT: string
                                public static readonly ER_RESOURCE_COULD_NOT_FIND: string
                                public static readonly ER_OUTPUT_PROPERTY_NOT_RECOGNIZED: string
                                public static readonly ER_FAILED_CREATING_ELEMLITRSLT: string
                                public static readonly ER_VALUE_SHOULD_BE_NUMBER: string
                                public static readonly ER_VALUE_SHOULD_EQUAL: string
                                public static readonly ER_FAILED_CALLING_METHOD: string
                                public static readonly ER_FAILED_CREATING_ELEMTMPL: string
                                public static readonly ER_CHARS_NOT_ALLOWED: string
                                public static readonly ER_ATTR_NOT_ALLOWED: string
                                public static readonly ER_BAD_VALUE: string
                                public static readonly ER_ATTRIB_VALUE_NOT_FOUND: string
                                public static readonly ER_ATTRIB_VALUE_NOT_RECOGNIZED: string
                                public static readonly ER_NULL_URI_NAMESPACE: string
                                public static readonly ER_NUMBER_TOO_BIG: string
                                public static readonly ER_CANNOT_FIND_SAX1_DRIVER: string
                                public static readonly ER_SAX1_DRIVER_NOT_LOADED: string
                                public static readonly ER_SAX1_DRIVER_NOT_INSTANTIATED: string
                                public static readonly ER_SAX1_DRIVER_NOT_IMPLEMENT_PARSER: string
                                public static readonly ER_PARSER_PROPERTY_NOT_SPECIFIED: string
                                public static readonly ER_PARSER_ARG_CANNOT_BE_NULL: string
                                public static readonly ER_FEATURE: string
                                public static readonly ER_PROPERTY: string
                                public static readonly ER_NULL_ENTITY_RESOLVER: string
                                public static readonly ER_NULL_DTD_HANDLER: string
                                public static readonly ER_NO_DRIVER_NAME_SPECIFIED: string
                                public static readonly ER_NO_URL_SPECIFIED: string
                                public static readonly ER_POOLSIZE_LESS_THAN_ONE: string
                                public static readonly ER_INVALID_DRIVER_NAME: string
                                public static readonly ER_ERRORLISTENER: string
                                public static readonly ER_ASSERT_NO_TEMPLATE_PARENT: string
                                public static readonly ER_ASSERT_REDUNDENT_EXPR_ELIMINATOR: string
                                public static readonly ER_NOT_ALLOWED_IN_POSITION: string
                                public static readonly ER_NONWHITESPACE_NOT_ALLOWED_IN_POSITION: string
                                public static readonly ER_NAMESPACE_CONTEXT_NULL_NAMESPACE: string
                                public static readonly ER_NAMESPACE_CONTEXT_NULL_PREFIX: string
                                public static readonly ER_XPATH_RESOLVER_NULL_QNAME: string
                                public static readonly ER_XPATH_RESOLVER_NEGATIVE_ARITY: string
                                public static readonly INVALID_TCHAR: string
                                public static readonly INVALID_QNAME: string
                                public static readonly INVALID_ENUM: string
                                public static readonly INVALID_NMTOKEN: string
                                public static readonly INVALID_NCNAME: string
                                public static readonly INVALID_BOOLEAN: string
                                public static readonly INVALID_NUMBER: string
                                public static readonly ER_ARG_LITERAL: string
                                public static readonly ER_DUPLICATE_GLOBAL_VAR: string
                                public static readonly ER_DUPLICATE_VAR: string
                                public static readonly ER_TEMPLATE_NAME_MATCH: string
                                public static readonly ER_INVALID_PREFIX: string
                                public static readonly ER_NO_ATTRIB_SET: string
                                public static readonly ER_FUNCTION_NOT_FOUND: string
                                public static readonly ER_CANT_HAVE_CONTENT_AND_SELECT: string
                                public static readonly ER_INVALID_SET_PARAM_VALUE: string
                                public static readonly ER_SET_FEATURE_NULL_NAME: string
                                public static readonly ER_GET_FEATURE_NULL_NAME: string
                                public static readonly ER_UNSUPPORTED_FEATURE: string
                                public static readonly ER_EXTENSION_ELEMENT_NOT_ALLOWED_IN_SECURE_PROCESSING: string
                                public static readonly WG_FOUND_CURLYBRACE: string
                                public static readonly WG_COUNT_ATTRIB_MATCHES_NO_ANCESTOR: string
                                public static readonly WG_EXPR_ATTRIB_CHANGED_TO_SELECT: string
                                public static readonly WG_NO_LOCALE_IN_FORMATNUMBER: string
                                public static readonly WG_LOCALE_NOT_FOUND: string
                                public static readonly WG_CANNOT_MAKE_URL_FROM: string
                                public static readonly WG_CANNOT_LOAD_REQUESTED_DOC: string
                                public static readonly WG_CANNOT_FIND_COLLATOR: string
                                public static readonly WG_FUNCTIONS_SHOULD_USE_URL: string
                                public static readonly WG_ENCODING_NOT_SUPPORTED_USING_UTF8: string
                                public static readonly WG_ENCODING_NOT_SUPPORTED_USING_JAVA: string
                                public static readonly WG_SPECIFICITY_CONFLICTS: string
                                public static readonly WG_PARSING_AND_PREPARING: string
                                public static readonly WG_ATTR_TEMPLATE: string
                                public static readonly WG_CONFLICT_BETWEEN_XSLSTRIPSPACE_AND_XSLPRESERVESPACE: string
                                public static readonly WG_ATTRIB_NOT_HANDLED: string
                                public static readonly WG_NO_DECIMALFORMAT_DECLARATION: string
                                public static readonly WG_OLD_XSLT_NS: string
                                public static readonly WG_ONE_DEFAULT_XSLDECIMALFORMAT_ALLOWED: string
                                public static readonly WG_XSLDECIMALFORMAT_NAMES_MUST_BE_UNIQUE: string
                                public static readonly WG_ILLEGAL_ATTRIBUTE: string
                                public static readonly WG_COULD_NOT_RESOLVE_PREFIX: string
                                public static readonly WG_STYLESHEET_REQUIRES_VERSION_ATTRIB: string
                                public static readonly WG_ILLEGAL_ATTRIBUTE_NAME: string
                                public static readonly WG_ILLEGAL_ATTRIBUTE_VALUE: string
                                public static readonly WG_EMPTY_SECOND_ARG: string
                                public static readonly WG_PROCESSINGINSTRUCTION_NAME_CANT_BE_XML: string
                                public static readonly WG_PROCESSINGINSTRUCTION_NOTVALID_NCNAME: string
                                public static readonly WG_ILLEGAL_ATTRIBUTE_POSITION: string
                                public static readonly NO_MODIFICATION_ALLOWED_ERR: string
                                public static readonly BAD_CODE: string
                                public static readonly FORMAT_FAILED: string
                                public static readonly ERROR_STRING: string
                                public static readonly ERROR_HEADER: string
                                public static readonly WARNING_HEADER: string
                                public static readonly XSL_HEADER: string
                                public static readonly XML_HEADER: string
                                public static readonly QUERY_HEADER: string
                                public constructor()
                                public getContents(): java.lang.Object[][]
                                public static class: java.lang.Class<any>
                            }
                        }
                    }
                }
            }
        }
    }
}