declare namespace java {
    namespace awt {
class PageAttributes$MediaType extends java.awt.AttributeValue {
    public static ISO_4A0: java.awt.PageAttributes$MediaType
    public static ISO_2A0: java.awt.PageAttributes$MediaType
    public static ISO_A0: java.awt.PageAttributes$MediaType
    public static ISO_A1: java.awt.PageAttributes$MediaType
    public static ISO_A2: java.awt.PageAttributes$MediaType
    public static ISO_A3: java.awt.PageAttributes$MediaType
    public static ISO_A4: java.awt.PageAttributes$MediaType
    public static ISO_A5: java.awt.PageAttributes$MediaType
    public static ISO_A6: java.awt.PageAttributes$MediaType
    public static ISO_A7: java.awt.PageAttributes$MediaType
    public static ISO_A8: java.awt.PageAttributes$MediaType
    public static ISO_A9: java.awt.PageAttributes$MediaType
    public static ISO_A10: java.awt.PageAttributes$MediaType
    public static ISO_B0: java.awt.PageAttributes$MediaType
    public static ISO_B1: java.awt.PageAttributes$MediaType
    public static ISO_B2: java.awt.PageAttributes$MediaType
    public static ISO_B3: java.awt.PageAttributes$MediaType
    public static ISO_B4: java.awt.PageAttributes$MediaType
    public static ISO_B5: java.awt.PageAttributes$MediaType
    public static ISO_B6: java.awt.PageAttributes$MediaType
    public static ISO_B7: java.awt.PageAttributes$MediaType
    public static ISO_B8: java.awt.PageAttributes$MediaType
    public static ISO_B9: java.awt.PageAttributes$MediaType
    public static ISO_B10: java.awt.PageAttributes$MediaType
    public static JIS_B0: java.awt.PageAttributes$MediaType
    public static JIS_B1: java.awt.PageAttributes$MediaType
    public static JIS_B2: java.awt.PageAttributes$MediaType
    public static JIS_B3: java.awt.PageAttributes$MediaType
    public static JIS_B4: java.awt.PageAttributes$MediaType
    public static JIS_B5: java.awt.PageAttributes$MediaType
    public static JIS_B6: java.awt.PageAttributes$MediaType
    public static JIS_B7: java.awt.PageAttributes$MediaType
    public static JIS_B8: java.awt.PageAttributes$MediaType
    public static JIS_B9: java.awt.PageAttributes$MediaType
    public static JIS_B10: java.awt.PageAttributes$MediaType
    public static ISO_C0: java.awt.PageAttributes$MediaType
    public static ISO_C1: java.awt.PageAttributes$MediaType
    public static ISO_C2: java.awt.PageAttributes$MediaType
    public static ISO_C3: java.awt.PageAttributes$MediaType
    public static ISO_C4: java.awt.PageAttributes$MediaType
    public static ISO_C5: java.awt.PageAttributes$MediaType
    public static ISO_C6: java.awt.PageAttributes$MediaType
    public static ISO_C7: java.awt.PageAttributes$MediaType
    public static ISO_C8: java.awt.PageAttributes$MediaType
    public static ISO_C9: java.awt.PageAttributes$MediaType
    public static ISO_C10: java.awt.PageAttributes$MediaType
    public static ISO_DESIGNATED_LONG: java.awt.PageAttributes$MediaType
    public static EXECUTIVE: java.awt.PageAttributes$MediaType
    public static FOLIO: java.awt.PageAttributes$MediaType
    public static INVOICE: java.awt.PageAttributes$MediaType
    public static LEDGER: java.awt.PageAttributes$MediaType
    public static NA_LETTER: java.awt.PageAttributes$MediaType
    public static NA_LEGAL: java.awt.PageAttributes$MediaType
    public static QUARTO: java.awt.PageAttributes$MediaType
    public static A: java.awt.PageAttributes$MediaType
    public static B: java.awt.PageAttributes$MediaType
    public static C: java.awt.PageAttributes$MediaType
    public static D: java.awt.PageAttributes$MediaType
    public static E: java.awt.PageAttributes$MediaType
    public static NA_10X15_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_10X14_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_10X13_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_9X12_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_9X11_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_7X9_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_6X9_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_NUMBER_9_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_NUMBER_10_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_NUMBER_11_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_NUMBER_12_ENVELOPE: java.awt.PageAttributes$MediaType
    public static NA_NUMBER_14_ENVELOPE: java.awt.PageAttributes$MediaType
    public static INVITE_ENVELOPE: java.awt.PageAttributes$MediaType
    public static ITALY_ENVELOPE: java.awt.PageAttributes$MediaType
    public static MONARCH_ENVELOPE: java.awt.PageAttributes$MediaType
    public static PERSONAL_ENVELOPE: java.awt.PageAttributes$MediaType
    public static A0: java.awt.PageAttributes$MediaType
    public static A1: java.awt.PageAttributes$MediaType
    public static A2: java.awt.PageAttributes$MediaType
    public static A3: java.awt.PageAttributes$MediaType
    public static A4: java.awt.PageAttributes$MediaType
    public static A5: java.awt.PageAttributes$MediaType
    public static A6: java.awt.PageAttributes$MediaType
    public static A7: java.awt.PageAttributes$MediaType
    public static A8: java.awt.PageAttributes$MediaType
    public static A9: java.awt.PageAttributes$MediaType
    public static A10: java.awt.PageAttributes$MediaType
    public static B0: java.awt.PageAttributes$MediaType
    public static B1: java.awt.PageAttributes$MediaType
    public static B2: java.awt.PageAttributes$MediaType
    public static B3: java.awt.PageAttributes$MediaType
    public static B4: java.awt.PageAttributes$MediaType
    public static ISO_B4_ENVELOPE: java.awt.PageAttributes$MediaType
    public static B5: java.awt.PageAttributes$MediaType
    public static ISO_B5_ENVELOPE: java.awt.PageAttributes$MediaType
    public static B6: java.awt.PageAttributes$MediaType
    public static B7: java.awt.PageAttributes$MediaType
    public static B8: java.awt.PageAttributes$MediaType
    public static B9: java.awt.PageAttributes$MediaType
    public static B10: java.awt.PageAttributes$MediaType
    public static C0: java.awt.PageAttributes$MediaType
    public static ISO_C0_ENVELOPE: java.awt.PageAttributes$MediaType
    public static C1: java.awt.PageAttributes$MediaType
    public static ISO_C1_ENVELOPE: java.awt.PageAttributes$MediaType
    public static C2: java.awt.PageAttributes$MediaType
    public static ISO_C2_ENVELOPE: java.awt.PageAttributes$MediaType
    public static C3: java.awt.PageAttributes$MediaType
    public static ISO_C3_ENVELOPE: java.awt.PageAttributes$MediaType
    public static C4: java.awt.PageAttributes$MediaType
    public static ISO_C4_ENVELOPE: java.awt.PageAttributes$MediaType
    public static C5: java.awt.PageAttributes$MediaType
    public static ISO_C5_ENVELOPE: java.awt.PageAttributes$MediaType
    public static C6: java.awt.PageAttributes$MediaType
    public static ISO_C6_ENVELOPE: java.awt.PageAttributes$MediaType
    public static C7: java.awt.PageAttributes$MediaType
    public static ISO_C7_ENVELOPE: java.awt.PageAttributes$MediaType
    public static C8: java.awt.PageAttributes$MediaType
    public static ISO_C8_ENVELOPE: java.awt.PageAttributes$MediaType
    public static C9: java.awt.PageAttributes$MediaType
    public static ISO_C9_ENVELOPE: java.awt.PageAttributes$MediaType
    public static C10: java.awt.PageAttributes$MediaType
    public static ISO_C10_ENVELOPE: java.awt.PageAttributes$MediaType
    public static ISO_DESIGNATED_LONG_ENVELOPE: java.awt.PageAttributes$MediaType
    public static STATEMENT: java.awt.PageAttributes$MediaType
    public static TABLOID: java.awt.PageAttributes$MediaType
    public static LETTER: java.awt.PageAttributes$MediaType
    public static NOTE: java.awt.PageAttributes$MediaType
    public static LEGAL: java.awt.PageAttributes$MediaType
    public static ENV_10X15: java.awt.PageAttributes$MediaType
    public static ENV_10X14: java.awt.PageAttributes$MediaType
    public static ENV_10X13: java.awt.PageAttributes$MediaType
    public static ENV_9X12: java.awt.PageAttributes$MediaType
    public static ENV_9X11: java.awt.PageAttributes$MediaType
    public static ENV_7X9: java.awt.PageAttributes$MediaType
    public static ENV_6X9: java.awt.PageAttributes$MediaType
    public static ENV_9: java.awt.PageAttributes$MediaType
    public static ENV_10: java.awt.PageAttributes$MediaType
    public static ENV_11: java.awt.PageAttributes$MediaType
    public static ENV_12: java.awt.PageAttributes$MediaType
    public static ENV_14: java.awt.PageAttributes$MediaType
    public static ENV_INVITE: java.awt.PageAttributes$MediaType
    public static ENV_ITALY: java.awt.PageAttributes$MediaType
    public static ENV_MONARCH: java.awt.PageAttributes$MediaType
    public static ENV_PERSONAL: java.awt.PageAttributes$MediaType
    public static INVITE: java.awt.PageAttributes$MediaType
    public static ITALY: java.awt.PageAttributes$MediaType
    public static MONARCH: java.awt.PageAttributes$MediaType
    public static PERSONAL: java.awt.PageAttributes$MediaType
    public toString(): string
    public hashCode(): int
    public static class: java.lang.Class<any>
}

    }
}