declare namespace java {
    namespace awt {
        namespace event {
            class KeyEvent extends java.awt.event.InputEvent {
                public static KEY_FIRST: int
                public static KEY_LAST: int
                public static KEY_TYPED: int
                public static KEY_PRESSED: int
                public static KEY_RELEASED: int
                public static VK_ENTER: int
                public static VK_BACK_SPACE: int
                public static VK_TAB: int
                public static VK_CANCEL: int
                public static VK_CLEAR: int
                public static VK_SHIFT: int
                public static VK_CONTROL: int
                public static VK_ALT: int
                public static VK_PAUSE: int
                public static VK_CAPS_LOCK: int
                public static VK_ESCAPE: int
                public static VK_SPACE: int
                public static VK_PAGE_UP: int
                public static VK_PAGE_DOWN: int
                public static VK_END: int
                public static VK_HOME: int
                public static VK_LEFT: int
                public static VK_UP: int
                public static VK_RIGHT: int
                public static VK_DOWN: int
                public static VK_COMMA: int
                public static VK_MINUS: int
                public static VK_PERIOD: int
                public static VK_SLASH: int
                public static VK_0: int
                public static VK_1: int
                public static VK_2: int
                public static VK_3: int
                public static VK_4: int
                public static VK_5: int
                public static VK_6: int
                public static VK_7: int
                public static VK_8: int
                public static VK_9: int
                public static VK_SEMICOLON: int
                public static VK_EQUALS: int
                public static VK_A: int
                public static VK_B: int
                public static VK_C: int
                public static VK_D: int
                public static VK_E: int
                public static VK_F: int
                public static VK_G: int
                public static VK_H: int
                public static VK_I: int
                public static VK_J: int
                public static VK_K: int
                public static VK_L: int
                public static VK_M: int
                public static VK_N: int
                public static VK_O: int
                public static VK_P: int
                public static VK_Q: int
                public static VK_R: int
                public static VK_S: int
                public static VK_T: int
                public static VK_U: int
                public static VK_V: int
                public static VK_W: int
                public static VK_X: int
                public static VK_Y: int
                public static VK_Z: int
                public static VK_OPEN_BRACKET: int
                public static VK_BACK_SLASH: int
                public static VK_CLOSE_BRACKET: int
                public static VK_NUMPAD0: int
                public static VK_NUMPAD1: int
                public static VK_NUMPAD2: int
                public static VK_NUMPAD3: int
                public static VK_NUMPAD4: int
                public static VK_NUMPAD5: int
                public static VK_NUMPAD6: int
                public static VK_NUMPAD7: int
                public static VK_NUMPAD8: int
                public static VK_NUMPAD9: int
                public static VK_MULTIPLY: int
                public static VK_ADD: int
                public static VK_SEPARATER: int
                public static VK_SEPARATOR: int
                public static VK_SUBTRACT: int
                public static VK_DECIMAL: int
                public static VK_DIVIDE: int
                public static VK_DELETE: int
                public static VK_NUM_LOCK: int
                public static VK_SCROLL_LOCK: int
                public static VK_F1: int
                public static VK_F2: int
                public static VK_F3: int
                public static VK_F4: int
                public static VK_F5: int
                public static VK_F6: int
                public static VK_F7: int
                public static VK_F8: int
                public static VK_F9: int
                public static VK_F10: int
                public static VK_F11: int
                public static VK_F12: int
                public static VK_F13: int
                public static VK_F14: int
                public static VK_F15: int
                public static VK_F16: int
                public static VK_F17: int
                public static VK_F18: int
                public static VK_F19: int
                public static VK_F20: int
                public static VK_F21: int
                public static VK_F22: int
                public static VK_F23: int
                public static VK_F24: int
                public static VK_PRINTSCREEN: int
                public static VK_INSERT: int
                public static VK_HELP: int
                public static VK_META: int
                public static VK_BACK_QUOTE: int
                public static VK_QUOTE: int
                public static VK_KP_UP: int
                public static VK_KP_DOWN: int
                public static VK_KP_LEFT: int
                public static VK_KP_RIGHT: int
                public static VK_DEAD_GRAVE: int
                public static VK_DEAD_ACUTE: int
                public static VK_DEAD_CIRCUMFLEX: int
                public static VK_DEAD_TILDE: int
                public static VK_DEAD_MACRON: int
                public static VK_DEAD_BREVE: int
                public static VK_DEAD_ABOVEDOT: int
                public static VK_DEAD_DIAERESIS: int
                public static VK_DEAD_ABOVERING: int
                public static VK_DEAD_DOUBLEACUTE: int
                public static VK_DEAD_CARON: int
                public static VK_DEAD_CEDILLA: int
                public static VK_DEAD_OGONEK: int
                public static VK_DEAD_IOTA: int
                public static VK_DEAD_VOICED_SOUND: int
                public static VK_DEAD_SEMIVOICED_SOUND: int
                public static VK_AMPERSAND: int
                public static VK_ASTERISK: int
                public static VK_QUOTEDBL: int
                public static VK_LESS: int
                public static VK_GREATER: int
                public static VK_BRACELEFT: int
                public static VK_BRACERIGHT: int
                public static VK_AT: int
                public static VK_COLON: int
                public static VK_CIRCUMFLEX: int
                public static VK_DOLLAR: int
                public static VK_EURO_SIGN: int
                public static VK_EXCLAMATION_MARK: int
                public static VK_INVERTED_EXCLAMATION_MARK: int
                public static VK_LEFT_PARENTHESIS: int
                public static VK_NUMBER_SIGN: int
                public static VK_PLUS: int
                public static VK_RIGHT_PARENTHESIS: int
                public static VK_UNDERSCORE: int
                public static VK_WINDOWS: int
                public static VK_CONTEXT_MENU: int
                public static VK_FINAL: int
                public static VK_CONVERT: int
                public static VK_NONCONVERT: int
                public static VK_ACCEPT: int
                public static VK_MODECHANGE: int
                public static VK_KANA: int
                public static VK_KANJI: int
                public static VK_ALPHANUMERIC: int
                public static VK_KATAKANA: int
                public static VK_HIRAGANA: int
                public static VK_FULL_WIDTH: int
                public static VK_HALF_WIDTH: int
                public static VK_ROMAN_CHARACTERS: int
                public static VK_ALL_CANDIDATES: int
                public static VK_PREVIOUS_CANDIDATE: int
                public static VK_CODE_INPUT: int
                public static VK_JAPANESE_KATAKANA: int
                public static VK_JAPANESE_HIRAGANA: int
                public static VK_JAPANESE_ROMAN: int
                public static VK_KANA_LOCK: int
                public static VK_INPUT_METHOD_ON_OFF: int
                public static VK_CUT: int
                public static VK_COPY: int
                public static VK_PASTE: int
                public static VK_UNDO: int
                public static VK_AGAIN: int
                public static VK_FIND: int
                public static VK_PROPS: int
                public static VK_STOP: int
                public static VK_COMPOSE: int
                public static VK_ALT_GRAPH: int
                public static VK_BEGIN: int
                public static VK_UNDEFINED: int
                public static CHAR_UNDEFINED: char
                public static KEY_LOCATION_UNKNOWN: int
                public static KEY_LOCATION_STANDARD: int
                public static KEY_LOCATION_LEFT: int
                public static KEY_LOCATION_RIGHT: int
                public static KEY_LOCATION_NUMPAD: int
                public constructor(arg0: java.awt.Component, arg1: int, arg2: long, arg3: int, arg4: int, arg5: char, arg6: int)
                public constructor(arg0: java.awt.Component, arg1: int, arg2: long, arg3: int, arg4: int, arg5: char)
                public constructor(arg0: java.awt.Component, arg1: int, arg2: long, arg3: int, arg4: int)
                public getKeyCode(): int
                public setKeyCode(arg0: int): void
                public getKeyChar(): char
                public setKeyChar(arg0: char): void
                public setModifiers(arg0: int): void
                public getKeyLocation(): int
                public static getKeyText(arg0: int): string
                public static getKeyModifiersText(arg0: int): string
                public isActionKey(): boolean
                public paramString(): string
                public getExtendedKeyCode(): int
                public static getExtendedKeyCodeForChar(arg0: int): int
                public static class: java.lang.Class<any>
            }
        }
    }
}