declare namespace java {
    namespace lang {
class Character$UnicodeScript extends java.lang.Enum<java.lang.Character$UnicodeScript> {
    public static COMMON: java.lang.Character$UnicodeScript
    public static LATIN: java.lang.Character$UnicodeScript
    public static GREEK: java.lang.Character$UnicodeScript
    public static CYRILLIC: java.lang.Character$UnicodeScript
    public static ARMENIAN: java.lang.Character$UnicodeScript
    public static HEBREW: java.lang.Character$UnicodeScript
    public static ARABIC: java.lang.Character$UnicodeScript
    public static SYRIAC: java.lang.Character$UnicodeScript
    public static THAANA: java.lang.Character$UnicodeScript
    public static DEVANAGARI: java.lang.Character$UnicodeScript
    public static BENGALI: java.lang.Character$UnicodeScript
    public static GURMUKHI: java.lang.Character$UnicodeScript
    public static GUJARATI: java.lang.Character$UnicodeScript
    public static ORIYA: java.lang.Character$UnicodeScript
    public static TAMIL: java.lang.Character$UnicodeScript
    public static TELUGU: java.lang.Character$UnicodeScript
    public static KANNADA: java.lang.Character$UnicodeScript
    public static MALAYALAM: java.lang.Character$UnicodeScript
    public static SINHALA: java.lang.Character$UnicodeScript
    public static THAI: java.lang.Character$UnicodeScript
    public static LAO: java.lang.Character$UnicodeScript
    public static TIBETAN: java.lang.Character$UnicodeScript
    public static MYANMAR: java.lang.Character$UnicodeScript
    public static GEORGIAN: java.lang.Character$UnicodeScript
    public static HANGUL: java.lang.Character$UnicodeScript
    public static ETHIOPIC: java.lang.Character$UnicodeScript
    public static CHEROKEE: java.lang.Character$UnicodeScript
    public static CANADIAN_ABORIGINAL: java.lang.Character$UnicodeScript
    public static OGHAM: java.lang.Character$UnicodeScript
    public static RUNIC: java.lang.Character$UnicodeScript
    public static KHMER: java.lang.Character$UnicodeScript
    public static MONGOLIAN: java.lang.Character$UnicodeScript
    public static HIRAGANA: java.lang.Character$UnicodeScript
    public static KATAKANA: java.lang.Character$UnicodeScript
    public static BOPOMOFO: java.lang.Character$UnicodeScript
    public static HAN: java.lang.Character$UnicodeScript
    public static YI: java.lang.Character$UnicodeScript
    public static OLD_ITALIC: java.lang.Character$UnicodeScript
    public static GOTHIC: java.lang.Character$UnicodeScript
    public static DESERET: java.lang.Character$UnicodeScript
    public static INHERITED: java.lang.Character$UnicodeScript
    public static TAGALOG: java.lang.Character$UnicodeScript
    public static HANUNOO: java.lang.Character$UnicodeScript
    public static BUHID: java.lang.Character$UnicodeScript
    public static TAGBANWA: java.lang.Character$UnicodeScript
    public static LIMBU: java.lang.Character$UnicodeScript
    public static TAI_LE: java.lang.Character$UnicodeScript
    public static LINEAR_B: java.lang.Character$UnicodeScript
    public static UGARITIC: java.lang.Character$UnicodeScript
    public static SHAVIAN: java.lang.Character$UnicodeScript
    public static OSMANYA: java.lang.Character$UnicodeScript
    public static CYPRIOT: java.lang.Character$UnicodeScript
    public static BRAILLE: java.lang.Character$UnicodeScript
    public static BUGINESE: java.lang.Character$UnicodeScript
    public static COPTIC: java.lang.Character$UnicodeScript
    public static NEW_TAI_LUE: java.lang.Character$UnicodeScript
    public static GLAGOLITIC: java.lang.Character$UnicodeScript
    public static TIFINAGH: java.lang.Character$UnicodeScript
    public static SYLOTI_NAGRI: java.lang.Character$UnicodeScript
    public static OLD_PERSIAN: java.lang.Character$UnicodeScript
    public static KHAROSHTHI: java.lang.Character$UnicodeScript
    public static BALINESE: java.lang.Character$UnicodeScript
    public static CUNEIFORM: java.lang.Character$UnicodeScript
    public static PHOENICIAN: java.lang.Character$UnicodeScript
    public static PHAGS_PA: java.lang.Character$UnicodeScript
    public static NKO: java.lang.Character$UnicodeScript
    public static SUNDANESE: java.lang.Character$UnicodeScript
    public static BATAK: java.lang.Character$UnicodeScript
    public static LEPCHA: java.lang.Character$UnicodeScript
    public static OL_CHIKI: java.lang.Character$UnicodeScript
    public static VAI: java.lang.Character$UnicodeScript
    public static SAURASHTRA: java.lang.Character$UnicodeScript
    public static KAYAH_LI: java.lang.Character$UnicodeScript
    public static REJANG: java.lang.Character$UnicodeScript
    public static LYCIAN: java.lang.Character$UnicodeScript
    public static CARIAN: java.lang.Character$UnicodeScript
    public static LYDIAN: java.lang.Character$UnicodeScript
    public static CHAM: java.lang.Character$UnicodeScript
    public static TAI_THAM: java.lang.Character$UnicodeScript
    public static TAI_VIET: java.lang.Character$UnicodeScript
    public static AVESTAN: java.lang.Character$UnicodeScript
    public static EGYPTIAN_HIEROGLYPHS: java.lang.Character$UnicodeScript
    public static SAMARITAN: java.lang.Character$UnicodeScript
    public static MANDAIC: java.lang.Character$UnicodeScript
    public static LISU: java.lang.Character$UnicodeScript
    public static BAMUM: java.lang.Character$UnicodeScript
    public static JAVANESE: java.lang.Character$UnicodeScript
    public static MEETEI_MAYEK: java.lang.Character$UnicodeScript
    public static IMPERIAL_ARAMAIC: java.lang.Character$UnicodeScript
    public static OLD_SOUTH_ARABIAN: java.lang.Character$UnicodeScript
    public static INSCRIPTIONAL_PARTHIAN: java.lang.Character$UnicodeScript
    public static INSCRIPTIONAL_PAHLAVI: java.lang.Character$UnicodeScript
    public static OLD_TURKIC: java.lang.Character$UnicodeScript
    public static BRAHMI: java.lang.Character$UnicodeScript
    public static KAITHI: java.lang.Character$UnicodeScript
    public static MEROITIC_HIEROGLYPHS: java.lang.Character$UnicodeScript
    public static MEROITIC_CURSIVE: java.lang.Character$UnicodeScript
    public static SORA_SOMPENG: java.lang.Character$UnicodeScript
    public static CHAKMA: java.lang.Character$UnicodeScript
    public static SHARADA: java.lang.Character$UnicodeScript
    public static TAKRI: java.lang.Character$UnicodeScript
    public static MIAO: java.lang.Character$UnicodeScript
    public static UNKNOWN: java.lang.Character$UnicodeScript
    public static values(): java.lang.Character$UnicodeScript[]
    public static valueOf(arg0: java.lang.String | string): java.lang.Character$UnicodeScript
    public static of(arg0: int): java.lang.Character$UnicodeScript
    public static forName(arg0: java.lang.String | string): java.lang.Character$UnicodeScript
    public static class: java.lang.Class<any>
}

    }
}