declare namespace sun {
    namespace awt {
        namespace X11 {
class XConstants {
    public static X_PROTOCOL: int
    public static X_PROTOCOL_REVISION: int
    public static None: long
    public static ParentRelative: long
    public static CopyFromParent: long
    public static PointerWindow: long
    public static InputFocus: long
    public static PointerRoot: long
    public static AnyPropertyType: long
    public static AnyKey: long
    public static AnyButton: long
    public static AllTemporary: long
    public static CurrentTime: long
    public static NoSymbol: long
    public static NoEventMask: long
    public static KeyPressMask: long
    public static KeyReleaseMask: long
    public static ButtonPressMask: long
    public static ButtonReleaseMask: long
    public static EnterWindowMask: long
    public static LeaveWindowMask: long
    public static PointerMotionMask: long
    public static PointerMotionHintMask: long
    public static Button1MotionMask: long
    public static Button2MotionMask: long
    public static Button3MotionMask: long
    public static Button4MotionMask: long
    public static Button5MotionMask: long
    public static ButtonMotionMask: long
    public static KeymapStateMask: long
    public static ExposureMask: long
    public static VisibilityChangeMask: long
    public static StructureNotifyMask: long
    public static ResizeRedirectMask: long
    public static SubstructureNotifyMask: long
    public static SubstructureRedirectMask: long
    public static FocusChangeMask: long
    public static PropertyChangeMask: long
    public static ColormapChangeMask: long
    public static OwnerGrabButtonMask: long
    public static MAX_BUTTONS: int
    public static ALL_BUTTONS_MASK: int
    public static KeyPress: int
    public static KeyRelease: int
    public static ButtonPress: int
    public static ButtonRelease: int
    public static MotionNotify: int
    public static EnterNotify: int
    public static LeaveNotify: int
    public static FocusIn: int
    public static FocusOut: int
    public static KeymapNotify: int
    public static Expose: int
    public static GraphicsExpose: int
    public static NoExpose: int
    public static VisibilityNotify: int
    public static CreateNotify: int
    public static DestroyNotify: int
    public static UnmapNotify: int
    public static MapNotify: int
    public static MapRequest: int
    public static ReparentNotify: int
    public static ConfigureNotify: int
    public static ConfigureRequest: int
    public static GravityNotify: int
    public static ResizeRequest: int
    public static CirculateNotify: int
    public static CirculateRequest: int
    public static PropertyNotify: int
    public static SelectionClear: int
    public static SelectionRequest: int
    public static SelectionNotify: int
    public static ColormapNotify: int
    public static ClientMessage: int
    public static MappingNotify: int
    public static LASTEvent: int
    public static ShiftMask: int
    public static LockMask: int
    public static ControlMask: int
    public static Mod1Mask: int
    public static Mod2Mask: int
    public static Mod3Mask: int
    public static Mod4Mask: int
    public static Mod5Mask: int
    public static ShiftMapIndex: int
    public static LockMapIndex: int
    public static ControlMapIndex: int
    public static Mod1MapIndex: int
    public static Mod2MapIndex: int
    public static Mod3MapIndex: int
    public static Mod4MapIndex: int
    public static Mod5MapIndex: int
    public static AnyModifier: int
    public static buttons: int[]
    public static NotifyNormal: int
    public static NotifyGrab: int
    public static NotifyUngrab: int
    public static NotifyWhileGrabbed: int
    public static NotifyHint: int
    public static NotifyAncestor: int
    public static NotifyVirtual: int
    public static NotifyInferior: int
    public static NotifyNonlinear: int
    public static NotifyNonlinearVirtual: int
    public static NotifyPointer: int
    public static NotifyPointerRoot: int
    public static NotifyDetailNone: int
    public static VisibilityUnobscured: int
    public static VisibilityPartiallyObscured: int
    public static VisibilityFullyObscured: int
    public static PlaceOnTop: int
    public static PlaceOnBottom: int
    public static FamilyInternet: int
    public static FamilyDECnet: int
    public static FamilyChaos: int
    public static PropertyNewValue: int
    public static PropertyDelete: int
    public static ColormapUninstalled: int
    public static ColormapInstalled: int
    public static GrabModeSync: int
    public static GrabModeAsync: int
    public static GrabSuccess: int
    public static AlreadyGrabbed: int
    public static GrabInvalidTime: int
    public static GrabNotViewable: int
    public static GrabFrozen: int
    public static AsyncPointer: int
    public static SyncPointer: int
    public static ReplayPointer: int
    public static AsyncKeyboard: int
    public static SyncKeyboard: int
    public static ReplayKeyboard: int
    public static AsyncBoth: int
    public static SyncBoth: int
    public static RevertToNone: int
    public static RevertToPointerRoot: int
    public static RevertToParent: int
    public static QueuedAlready: int
    public static QueuedAfterReading: int
    public static QueuedAfterFlush: int
    public static Success: int
    public static BadRequest: int
    public static BadValue: int
    public static BadWindow: int
    public static BadPixmap: int
    public static BadAtom: int
    public static BadCursor: int
    public static BadFont: int
    public static BadMatch: int
    public static BadDrawable: int
    public static BadAccess: int
    public static BadAlloc: int
    public static BadColor: int
    public static BadGC: int
    public static BadIDChoice: int
    public static BadName: int
    public static BadLength: int
    public static BadImplementation: int
    public static FirstExtensionError: int
    public static LastExtensionError: int
    public static InputOutput: int
    public static InputOnly: int
    public static CWBackPixmap: long
    public static CWBackPixel: long
    public static CWBorderPixmap: long
    public static CWBorderPixel: long
    public static CWBitGravity: long
    public static CWWinGravity: long
    public static CWBackingStore: long
    public static CWBackingPlanes: long
    public static CWBackingPixel: long
    public static CWOverrideRedirect: long
    public static CWSaveUnder: long
    public static CWEventMask: long
    public static CWDontPropagate: long
    public static CWColormap: long
    public static CWCursor: long
    public static CWX: int
    public static CWY: int
    public static CWWidth: int
    public static CWHeight: int
    public static CWBorderWidth: int
    public static CWSibling: int
    public static CWStackMode: int
    public static ForgetGravity: int
    public static NorthWestGravity: int
    public static NorthGravity: int
    public static NorthEastGravity: int
    public static WestGravity: int
    public static CenterGravity: int
    public static EastGravity: int
    public static SouthWestGravity: int
    public static SouthGravity: int
    public static SouthEastGravity: int
    public static StaticGravity: int
    public static UnmapGravity: int
    public static NotUseful: int
    public static WhenMapped: int
    public static Always: int
    public static IsUnmapped: int
    public static IsUnviewable: int
    public static IsViewable: int
    public static SetModeInsert: int
    public static SetModeDelete: int
    public static DestroyAll: int
    public static RetainPermanent: int
    public static RetainTemporary: int
    public static Above: int
    public static Below: int
    public static TopIf: int
    public static BottomIf: int
    public static Opposite: int
    public static RaiseLowest: int
    public static LowerHighest: int
    public static PropModeReplace: int
    public static PropModePrepend: int
    public static PropModeAppend: int
    public static GXclear: int
    public static GXand: int
    public static GXandReverse: int
    public static GXcopy: int
    public static GXandInverted: int
    public static GXnoop: int
    public static GXxor: int
    public static GXor: int
    public static GXnor: int
    public static GXequiv: int
    public static GXinvert: int
    public static GXorReverse: int
    public static GXcopyInverted: int
    public static GXorInverted: int
    public static GXnand: int
    public static GXset: int
    public static LineSolid: int
    public static LineOnOffDash: int
    public static LineDoubleDash: int
    public static CapNotLast: int
    public static CapButt: int
    public static CapRound: int
    public static CapProjecting: int
    public static JoinMiter: int
    public static JoinRound: int
    public static JoinBevel: int
    public static FillSolid: int
    public static FillTiled: int
    public static FillStippled: int
    public static FillOpaqueStippled: int
    public static EvenOddRule: int
    public static WindingRule: int
    public static ClipByChildren: int
    public static IncludeInferiors: int
    public static Unsorted: int
    public static YSorted: int
    public static YXSorted: int
    public static YXBanded: int
    public static CoordModeOrigin: int
    public static CoordModePrevious: int
    public static Complex: int
    public static Nonconvex: int
    public static Convex: int
    public static ArcChord: int
    public static ArcPieSlice: int
    public static GCFunction: long
    public static GCPlaneMask: long
    public static GCForeground: long
    public static GCBackground: long
    public static GCLineWidth: long
    public static GCLineStyle: long
    public static GCCapStyle: long
    public static GCJoinStyle: long
    public static GCFillStyle: long
    public static GCFillRule: long
    public static GCTile: long
    public static GCStipple: long
    public static GCTileStipXOrigin: long
    public static GCTileStipYOrigin: long
    public static GCFont: long
    public static GCSubwindowMode: long
    public static GCGraphicsExposures: long
    public static GCClipXOrigin: long
    public static GCClipYOrigin: long
    public static GCClipMask: long
    public static GCDashOffset: long
    public static GCDashList: long
    public static GCArcMode: long
    public static GCLastBit: int
    public static FontLeftToRight: int
    public static FontRightToLeft: int
    public static FontChange: int
    public static XYBitmap: int
    public static XYPixmap: int
    public static ZPixmap: int
    public static AllocNone: int
    public static AllocAll: int
    public static DoRed: int
    public static DoGreen: int
    public static DoBlue: int
    public static CursorShape: int
    public static TileShape: int
    public static StippleShape: int
    public static AutoRepeatModeOff: int
    public static AutoRepeatModeOn: int
    public static AutoRepeatModeDefault: int
    public static LedModeOff: int
    public static LedModeOn: int
    public static KBKeyClickPercent: long
    public static KBBellPercent: long
    public static KBBellPitch: long
    public static KBBellDuration: long
    public static KBLed: long
    public static KBLedMode: long
    public static KBKey: long
    public static KBAutoRepeatMode: long
    public static MappingSuccess: int
    public static MappingBusy: int
    public static MappingFailed: int
    public static MappingModifier: int
    public static MappingKeyboard: int
    public static MappingPointer: int
    public static DontPreferBlanking: int
    public static PreferBlanking: int
    public static DefaultBlanking: int
    public static DisableScreenSaver: int
    public static DisableScreenInterval: int
    public static DontAllowExposures: int
    public static AllowExposures: int
    public static DefaultExposures: int
    public static ScreenSaverReset: int
    public static ScreenSaverActive: int
    public static HostInsert: int
    public static HostDelete: int
    public static EnableAccess: int
    public static DisableAccess: int
    public static StaticGray: int
    public static GrayScale: int
    public static StaticColor: int
    public static PseudoColor: int
    public static TrueColor: int
    public static DirectColor: int
    public static LSBFirst: int
    public static MSBFirst: int
    public static XkbUseCoreKbd: int
    public static XkbNewKeyboardNotify: int
    public static XkbMapNotify: int
    public static XkbStateNotify: int
    public static XkbNewKeyboardNotifyMask: long
    public static XkbMapNotifyMask: long
    public static XkbStateNotifyMask: long
    public static XkbGroupStateMask: long
    public static XkbKeyTypesMask: long
    public static XkbKeySymsMask: long
    public static XkbModifierMapMask: long
    public static XkbVirtualModsMask: long
    public static class: java.lang.Class<any>
}

        }
    }
}