declare namespace sun {
    namespace net {
        namespace idn {
interface UCharacterEnums$ECharacterDirection {
    LEFT_TO_RIGHT: int
    DIRECTIONALITY_LEFT_TO_RIGHT: byte
    RIGHT_TO_LEFT: int
    DIRECTIONALITY_RIGHT_TO_LEFT: byte
    EUROPEAN_NUMBER: int
    DIRECTIONALITY_EUROPEAN_NUMBER: byte
    EUROPEAN_NUMBER_SEPARATOR: int
    DIRECTIONALITY_EUROPEAN_NUMBER_SEPARATOR: byte
    EUROPEAN_NUMBER_TERMINATOR: int
    DIRECTIONALITY_EUROPEAN_NUMBER_TERMINATOR: byte
    ARABIC_NUMBER: int
    DIRECTIONALITY_ARABIC_NUMBER: byte
    COMMON_NUMBER_SEPARATOR: int
    DIRECTIONALITY_COMMON_NUMBER_SEPARATOR: byte
    BLOCK_SEPARATOR: int
    DIRECTIONALITY_PARAGRAPH_SEPARATOR: byte
    SEGMENT_SEPARATOR: int
    DIRECTIONALITY_SEGMENT_SEPARATOR: byte
    WHITE_SPACE_NEUTRAL: int
    DIRECTIONALITY_WHITESPACE: byte
    OTHER_NEUTRAL: int
    DIRECTIONALITY_OTHER_NEUTRALS: byte
    LEFT_TO_RIGHT_EMBEDDING: int
    DIRECTIONALITY_LEFT_TO_RIGHT_EMBEDDING: byte
    LEFT_TO_RIGHT_OVERRIDE: int
    DIRECTIONALITY_LEFT_TO_RIGHT_OVERRIDE: byte
    RIGHT_TO_LEFT_ARABIC: int
    DIRECTIONALITY_RIGHT_TO_LEFT_ARABIC: byte
    RIGHT_TO_LEFT_EMBEDDING: int
    DIRECTIONALITY_RIGHT_TO_LEFT_EMBEDDING: byte
    RIGHT_TO_LEFT_OVERRIDE: int
    DIRECTIONALITY_RIGHT_TO_LEFT_OVERRIDE: byte
    POP_DIRECTIONAL_FORMAT: int
    DIRECTIONALITY_POP_DIRECTIONAL_FORMAT: byte
    DIR_NON_SPACING_MARK: int
    DIRECTIONALITY_NON_SPACING_MARK: byte
    BOUNDARY_NEUTRAL: int
    DIRECTIONALITY_BOUNDARY_NEUTRAL: byte
    CHAR_DIRECTION_COUNT: int
    DIRECTIONALITY_UNDEFINED: byte
}

        }
    }
}