declare namespace sun {
    namespace security {
        namespace krb5 {
            namespace internal {
                class Krb5 {
                    public static readonly DEFAULT_ALLOWABLE_CLOCKSKEW: int
                    public static readonly DEFAULT_MINIMUM_LIFETIME: int
                    public static readonly DEFAULT_MAXIMUM_RENEWABLE_LIFETIME: int
                    public static readonly DEFAULT_MAXIMUM_TICKET_LIFETIME: int
                    public static readonly DEFAULT_FORWARDABLE_ALLOWED: boolean
                    public static readonly DEFAULT_PROXIABLE_ALLOWED: boolean
                    public static readonly DEFAULT_POSTDATE_ALLOWED: boolean
                    public static readonly DEFAULT_RENEWABLE_ALLOWED: boolean
                    public static readonly AP_EMPTY_ADDRESSES_ALLOWED: boolean
                    public static readonly AP_OPTS_RESERVED: int
                    public static readonly AP_OPTS_USE_SESSION_KEY: int
                    public static readonly AP_OPTS_MUTUAL_REQUIRED: int
                    public static readonly AP_OPTS_MAX: int
                    public static readonly TKT_OPTS_RESERVED: int
                    public static readonly TKT_OPTS_FORWARDABLE: int
                    public static readonly TKT_OPTS_FORWARDED: int
                    public static readonly TKT_OPTS_PROXIABLE: int
                    public static readonly TKT_OPTS_PROXY: int
                    public static readonly TKT_OPTS_MAY_POSTDATE: int
                    public static readonly TKT_OPTS_POSTDATED: int
                    public static readonly TKT_OPTS_INVALID: int
                    public static readonly TKT_OPTS_RENEWABLE: int
                    public static readonly TKT_OPTS_INITIAL: int
                    public static readonly TKT_OPTS_PRE_AUTHENT: int
                    public static readonly TKT_OPTS_HW_AUTHENT: int
                    public static readonly TKT_OPTS_DELEGATE: int
                    public static readonly TKT_OPTS_MAX: int
                    public static readonly KDC_OPTS_MAX: int
                    public static readonly KRB_FLAGS_MAX: int
                    public static readonly LRTYPE_NONE: int
                    public static readonly LRTYPE_TIME_OF_INITIAL_TGT: int
                    public static readonly LRTYPE_TIME_OF_INITIAL_REQ: int
                    public static readonly LRTYPE_TIME_OF_NEWEST_TGT: int
                    public static readonly LRTYPE_TIME_OF_LAST_RENEWAL: int
                    public static readonly LRTYPE_TIME_OF_LAST_REQ: int
                    public static readonly ADDR_LEN_INET: int
                    public static readonly ADDR_LEN_CHAOS: int
                    public static readonly ADDR_LEN_OSI: int
                    public static readonly ADDR_LEN_XNS: int
                    public static readonly ADDR_LEN_APPLETALK: int
                    public static readonly ADDR_LEN_DECNET: int
                    public static readonly ADDRTYPE_UNIX: int
                    public static readonly ADDRTYPE_INET: int
                    public static readonly ADDRTYPE_IMPLINK: int
                    public static readonly ADDRTYPE_PUP: int
                    public static readonly ADDRTYPE_CHAOS: int
                    public static readonly ADDRTYPE_XNS: int
                    public static readonly ADDRTYPE_IPX: int
                    public static readonly ADDRTYPE_ISO: int
                    public static readonly ADDRTYPE_ECMA: int
                    public static readonly ADDRTYPE_DATAKIT: int
                    public static readonly ADDRTYPE_CCITT: int
                    public static readonly ADDRTYPE_SNA: int
                    public static readonly ADDRTYPE_DECNET: int
                    public static readonly ADDRTYPE_DLI: int
                    public static readonly ADDRTYPE_LAT: int
                    public static readonly ADDRTYPE_HYLINK: int
                    public static readonly ADDRTYPE_APPLETALK: int
                    public static readonly ADDRTYPE_NETBIOS: int
                    public static readonly ADDRTYPE_VOICEVIEW: int
                    public static readonly ADDRTYPE_FIREFOX: int
                    public static readonly ADDRTYPE_BAN: int
                    public static readonly ADDRTYPE_ATM: int
                    public static readonly ADDRTYPE_INET6: int
                    public static readonly KDC_INET_DEFAULT_PORT: int
                    public static readonly KDC_RETRY_LIMIT: int
                    public static readonly KDC_DEFAULT_UDP_PREF_LIMIT: int
                    public static readonly KDC_HARD_UDP_LIMIT: int
                    public static readonly KEYTYPE_NULL: int
                    public static readonly KEYTYPE_DES: int
                    public static readonly KEYTYPE_DES3: int
                    public static readonly KEYTYPE_AES: int
                    public static readonly KEYTYPE_ARCFOUR_HMAC: int
                    public static readonly PA_TGS_REQ: int
                    public static readonly PA_ENC_TIMESTAMP: int
                    public static readonly PA_PW_SALT: int
                    public static readonly PA_ETYPE_INFO: int
                    public static readonly PA_ETYPE_INFO2: int
                    public static readonly PA_FOR_USER: int
                    public static readonly OSF_DCE: int
                    public static readonly SESAME: int
                    public static readonly ATT_CHALLENGE_RESPONSE: int
                    public static readonly DOMAIN_X500_COMPRESS: int
                    public static readonly PVNO: int
                    public static readonly AUTHNETICATOR_VNO: int
                    public static readonly TICKET_VNO: int
                    public static readonly KRB_AS_REQ: int
                    public static readonly KRB_AS_REP: int
                    public static readonly KRB_TGS_REQ: int
                    public static readonly KRB_TGS_REP: int
                    public static readonly KRB_AP_REQ: int
                    public static readonly KRB_AP_REP: int
                    public static readonly KRB_SAFE: int
                    public static readonly KRB_PRIV: int
                    public static readonly KRB_CRED: int
                    public static readonly KRB_ERROR: int
                    public static readonly KRB_TKT: int
                    public static readonly KRB_AUTHENTICATOR: int
                    public static readonly KRB_ENC_TKT_PART: int
                    public static readonly KRB_ENC_AS_REP_PART: int
                    public static readonly KRB_ENC_TGS_REP_PART: int
                    public static readonly KRB_ENC_AP_REP_PART: int
                    public static readonly KRB_ENC_KRB_PRIV_PART: int
                    public static readonly KRB_ENC_KRB_CRED_PART: int
                    public static readonly KDC_ERR_NONE: int
                    public static readonly KDC_ERR_NAME_EXP: int
                    public static readonly KDC_ERR_SERVICE_EXP: int
                    public static readonly KDC_ERR_BAD_PVNO: int
                    public static readonly KDC_ERR_C_OLD_MAST_KVNO: int
                    public static readonly KDC_ERR_S_OLD_MAST_KVNO: int
                    public static readonly KDC_ERR_C_PRINCIPAL_UNKNOWN: int
                    public static readonly KDC_ERR_S_PRINCIPAL_UNKNOWN: int
                    public static readonly KDC_ERR_PRINCIPAL_NOT_UNIQUE: int
                    public static readonly KDC_ERR_NULL_KEY: int
                    public static readonly KDC_ERR_CANNOT_POSTDATE: int
                    public static readonly KDC_ERR_NEVER_VALID: int
                    public static readonly KDC_ERR_POLICY: int
                    public static readonly KDC_ERR_BADOPTION: int
                    public static readonly KDC_ERR_ETYPE_NOSUPP: int
                    public static readonly KDC_ERR_SUMTYPE_NOSUPP: int
                    public static readonly KDC_ERR_PADATA_TYPE_NOSUPP: int
                    public static readonly KDC_ERR_TRTYPE_NOSUPP: int
                    public static readonly KDC_ERR_CLIENT_REVOKED: int
                    public static readonly KDC_ERR_SERVICE_REVOKED: int
                    public static readonly KDC_ERR_TGT_REVOKED: int
                    public static readonly KDC_ERR_CLIENT_NOTYET: int
                    public static readonly KDC_ERR_SERVICE_NOTYET: int
                    public static readonly KDC_ERR_KEY_EXPIRED: int
                    public static readonly KDC_ERR_PREAUTH_FAILED: int
                    public static readonly KDC_ERR_PREAUTH_REQUIRED: int
                    public static readonly KRB_AP_ERR_BAD_INTEGRITY: int
                    public static readonly KRB_AP_ERR_TKT_EXPIRED: int
                    public static readonly KRB_AP_ERR_TKT_NYV: int
                    public static readonly KRB_AP_ERR_REPEAT: int
                    public static readonly KRB_AP_ERR_NOT_US: int
                    public static readonly KRB_AP_ERR_BADMATCH: int
                    public static readonly KRB_AP_ERR_SKEW: int
                    public static readonly KRB_AP_ERR_BADADDR: int
                    public static readonly KRB_AP_ERR_BADVERSION: int
                    public static readonly KRB_AP_ERR_MSG_TYPE: int
                    public static readonly KRB_AP_ERR_MODIFIED: int
                    public static readonly KRB_AP_ERR_BADORDER: int
                    public static readonly KRB_AP_ERR_BADKEYVER: int
                    public static readonly KRB_AP_ERR_NOKEY: int
                    public static readonly KRB_AP_ERR_MUT_FAIL: int
                    public static readonly KRB_AP_ERR_BADDIRECTION: int
                    public static readonly KRB_AP_ERR_METHOD: int
                    public static readonly KRB_AP_ERR_BADSEQ: int
                    public static readonly KRB_AP_ERR_INAPP_CKSUM: int
                    public static readonly KRB_ERR_RESPONSE_TOO_BIG: int
                    public static readonly KRB_ERR_GENERIC: int
                    public static readonly KRB_ERR_FIELD_TOOLONG: int
                    public static readonly KRB_CRYPTO_NOT_SUPPORT: int
                    public static readonly KRB_AP_ERR_NOREALM: int
                    public static readonly KRB_AP_ERR_GEN_CRED: int
                    public static readonly KRB_AP_ERR_REQ_OPTIONS: int
                    public static readonly API_INVALID_ARG: int
                    public static readonly BITSTRING_SIZE_INVALID: int
                    public static readonly BITSTRING_INDEX_OUT_OF_BOUNDS: int
                    public static readonly BITSTRING_BAD_LENGTH: int
                    public static readonly REALM_ILLCHAR: int
                    public static readonly REALM_NULL: int
                    public static readonly ASN1_BAD_TIMEFORMAT: int
                    public static readonly ASN1_MISSING_FIELD: int
                    public static readonly ASN1_MISPLACED_FIELD: int
                    public static readonly ASN1_TYPE_MISMATCH: int
                    public static readonly ASN1_OVERFLOW: int
                    public static readonly ASN1_OVERRUN: int
                    public static readonly ASN1_BAD_ID: int
                    public static readonly ASN1_BAD_LENGTH: int
                    public static readonly ASN1_BAD_FORMAT: int
                    public static readonly ASN1_PARSE_ERROR: int
                    public static readonly ASN1_BAD_CLASS: int
                    public static readonly ASN1_BAD_TYPE: int
                    public static readonly ASN1_BAD_TAG: int
                    public static readonly ASN1_UNSUPPORTED_TYPE: int
                    public static readonly ASN1_CANNOT_ENCODE: int
                    public static readonly DEBUG: boolean
                    public static readonly hexDumper: sun.misc.HexDumpEncoder
                    public constructor()
                    public static getErrorMessage(arg0: int): string
                    public static class: java.lang.Class<any>
                }
            }
        }
    }
}