declare namespace sun {
    namespace reflect {
        interface ClassFileConstants {
            opc_aconst_null: byte
            opc_sipush: byte
            opc_ldc: byte
            opc_iload_0: byte
            opc_iload_1: byte
            opc_iload_2: byte
            opc_iload_3: byte
            opc_lload_0: byte
            opc_lload_1: byte
            opc_lload_2: byte
            opc_lload_3: byte
            opc_fload_0: byte
            opc_fload_1: byte
            opc_fload_2: byte
            opc_fload_3: byte
            opc_dload_0: byte
            opc_dload_1: byte
            opc_dload_2: byte
            opc_dload_3: byte
            opc_aload_0: byte
            opc_aload_1: byte
            opc_aload_2: byte
            opc_aload_3: byte
            opc_aaload: byte
            opc_astore_0: byte
            opc_astore_1: byte
            opc_astore_2: byte
            opc_astore_3: byte
            opc_pop: byte
            opc_dup: byte
            opc_dup_x1: byte
            opc_swap: byte
            opc_i2l: byte
            opc_i2f: byte
            opc_i2d: byte
            opc_l2i: byte
            opc_l2f: byte
            opc_l2d: byte
            opc_f2i: byte
            opc_f2l: byte
            opc_f2d: byte
            opc_d2i: byte
            opc_d2l: byte
            opc_d2f: byte
            opc_i2b: byte
            opc_i2c: byte
            opc_i2s: byte
            opc_ifeq: byte
            opc_if_icmpeq: byte
            opc_goto: byte
            opc_ireturn: byte
            opc_lreturn: byte
            opc_freturn: byte
            opc_dreturn: byte
            opc_areturn: byte
            opc_return: byte
            opc_getstatic: byte
            opc_putstatic: byte
            opc_getfield: byte
            opc_putfield: byte
            opc_invokevirtual: byte
            opc_invokespecial: byte
            opc_invokestatic: byte
            opc_invokeinterface: byte
            opc_arraylength: byte
            opc_new: byte
            opc_athrow: byte
            opc_checkcast: byte
            opc_instanceof: byte
            opc_ifnull: byte
            opc_ifnonnull: byte
            CONSTANT_Class: byte
            CONSTANT_Fieldref: byte
            CONSTANT_Methodref: byte
            CONSTANT_InterfaceMethodref: byte
            CONSTANT_NameAndType: byte
            CONSTANT_String: byte
            CONSTANT_Utf8: byte
            ACC_PUBLIC: short
        }
    }
}