declare namespace sun {
    namespace awt {
        namespace X11 {
interface XKeySymConstants {
    XK_VoidSymbol: long
    XK_BackSpace: long
    XK_Tab: long
    XK_Linefeed: long
    XK_Clear: long
    XK_Return: long
    XK_Pause: long
    XK_Scroll_Lock: long
    XK_Sys_Req: long
    XK_Escape: long
    XK_Delete: long
    XK_Multi_key: long
    XK_Codeinput: long
    XK_SingleCandidate: long
    XK_MultipleCandidate: long
    XK_PreviousCandidate: long
    XK_Kanji: long
    XK_Muhenkan: long
    XK_Henkan_Mode: long
    XK_Henkan: long
    XK_Romaji: long
    XK_Hiragana: long
    XK_Katakana: long
    XK_Hiragana_Katakana: long
    XK_Zenkaku: long
    XK_Hankaku: long
    XK_Zenkaku_Hankaku: long
    XK_Touroku: long
    XK_Massyo: long
    XK_Kana_Lock: long
    XK_Kana_Shift: long
    XK_Eisu_Shift: long
    XK_Eisu_toggle: long
    XK_Kanji_Bangou: long
    XK_Zen_Koho: long
    XK_Mae_Koho: long
    XK_Home: long
    XK_Left: long
    XK_Up: long
    XK_Right: long
    XK_Down: long
    XK_Prior: long
    XK_Page_Up: long
    XK_Next: long
    XK_Page_Down: long
    XK_End: long
    XK_Begin: long
    XK_Select: long
    XK_Print: long
    XK_Execute: long
    XK_Insert: long
    XK_Undo: long
    XK_Redo: long
    XK_Menu: long
    XK_Find: long
    XK_Cancel: long
    XK_Help: long
    XK_Break: long
    XK_Mode_switch: long
    XK_script_switch: long
    XK_Num_Lock: long
    XK_KP_Space: long
    XK_KP_Tab: long
    XK_KP_Enter: long
    XK_KP_F1: long
    XK_KP_F2: long
    XK_KP_F3: long
    XK_KP_F4: long
    XK_KP_Home: long
    XK_KP_Left: long
    XK_KP_Up: long
    XK_KP_Right: long
    XK_KP_Down: long
    XK_KP_Prior: long
    XK_KP_Page_Up: long
    XK_KP_Next: long
    XK_KP_Page_Down: long
    XK_KP_End: long
    XK_KP_Begin: long
    XK_KP_Insert: long
    XK_KP_Delete: long
    XK_KP_Equal: long
    XK_KP_Multiply: long
    XK_KP_Add: long
    XK_KP_Separator: long
    XK_KP_Subtract: long
    XK_KP_Decimal: long
    XK_KP_Divide: long
    XK_KP_0: long
    XK_KP_1: long
    XK_KP_2: long
    XK_KP_3: long
    XK_KP_4: long
    XK_KP_5: long
    XK_KP_6: long
    XK_KP_7: long
    XK_KP_8: long
    XK_KP_9: long
    XK_F1: long
    XK_F2: long
    XK_F3: long
    XK_F4: long
    XK_F5: long
    XK_F6: long
    XK_F7: long
    XK_F8: long
    XK_F9: long
    XK_F10: long
    XK_F11: long
    XK_L1: long
    XK_F12: long
    XK_L2: long
    XK_F13: long
    XK_L3: long
    XK_F14: long
    XK_L4: long
    XK_F15: long
    XK_L5: long
    XK_F16: long
    XK_L6: long
    XK_F17: long
    XK_L7: long
    XK_F18: long
    XK_L8: long
    XK_F19: long
    XK_L9: long
    XK_F20: long
    XK_L10: long
    XK_F21: long
    XK_R1: long
    XK_F22: long
    XK_R2: long
    XK_F23: long
    XK_R3: long
    XK_F24: long
    XK_R4: long
    XK_F25: long
    XK_R5: long
    XK_F26: long
    XK_R6: long
    XK_F27: long
    XK_R7: long
    XK_F28: long
    XK_R8: long
    XK_F29: long
    XK_R9: long
    XK_F30: long
    XK_R10: long
    XK_F31: long
    XK_R11: long
    XK_F32: long
    XK_R12: long
    XK_F33: long
    XK_R13: long
    XK_F34: long
    XK_R14: long
    XK_F35: long
    XK_R15: long
    XK_Shift_L: long
    XK_Shift_R: long
    XK_Control_L: long
    XK_Control_R: long
    XK_Caps_Lock: long
    XK_Shift_Lock: long
    XK_Meta_L: long
    XK_Meta_R: long
    XK_Alt_L: long
    XK_Alt_R: long
    XK_Super_L: long
    XK_Super_R: long
    XK_Hyper_L: long
    XK_Hyper_R: long
    XK_ISO_Lock: long
    XK_ISO_Level2_Latch: long
    XK_ISO_Level3_Shift: long
    XK_ISO_Level3_Latch: long
    XK_ISO_Level3_Lock: long
    XK_ISO_Group_Shift: long
    XK_ISO_Group_Latch: long
    XK_ISO_Group_Lock: long
    XK_ISO_Next_Group: long
    XK_ISO_Next_Group_Lock: long
    XK_ISO_Prev_Group: long
    XK_ISO_Prev_Group_Lock: long
    XK_ISO_First_Group: long
    XK_ISO_First_Group_Lock: long
    XK_ISO_Last_Group: long
    XK_ISO_Last_Group_Lock: long
    XK_ISO_Left_Tab: long
    XK_ISO_Move_Line_Up: long
    XK_ISO_Move_Line_Down: long
    XK_ISO_Partial_Line_Up: long
    XK_ISO_Partial_Line_Down: long
    XK_ISO_Partial_Space_Left: long
    XK_ISO_Partial_Space_Right: long
    XK_ISO_Set_Margin_Left: long
    XK_ISO_Set_Margin_Right: long
    XK_ISO_Release_Margin_Left: long
    XK_ISO_Release_Margin_Right: long
    XK_ISO_Release_Both_Margins: long
    XK_ISO_Fast_Cursor_Left: long
    XK_ISO_Fast_Cursor_Right: long
    XK_ISO_Fast_Cursor_Up: long
    XK_ISO_Fast_Cursor_Down: long
    XK_ISO_Continuous_Underline: long
    XK_ISO_Discontinuous_Underline: long
    XK_ISO_Emphasize: long
    XK_ISO_Center_Object: long
    XK_ISO_Enter: long
    XK_dead_grave: long
    XK_dead_acute: long
    XK_dead_circumflex: long
    XK_dead_tilde: long
    XK_dead_macron: long
    XK_dead_breve: long
    XK_dead_abovedot: long
    XK_dead_diaeresis: long
    XK_dead_abovering: long
    XK_dead_doubleacute: long
    XK_dead_caron: long
    XK_dead_cedilla: long
    XK_dead_ogonek: long
    XK_dead_iota: long
    XK_dead_voiced_sound: long
    XK_dead_semivoiced_sound: long
    XK_dead_belowdot: long
    XK_First_Virtual_Screen: long
    XK_Prev_Virtual_Screen: long
    XK_Next_Virtual_Screen: long
    XK_Last_Virtual_Screen: long
    XK_Terminate_Server: long
    XK_AccessX_Enable: long
    XK_AccessX_Feedback_Enable: long
    XK_RepeatKeys_Enable: long
    XK_SlowKeys_Enable: long
    XK_BounceKeys_Enable: long
    XK_StickyKeys_Enable: long
    XK_MouseKeys_Enable: long
    XK_MouseKeys_Accel_Enable: long
    XK_Overlay1_Enable: long
    XK_Overlay2_Enable: long
    XK_AudibleBell_Enable: long
    XK_Pointer_Left: long
    XK_Pointer_Right: long
    XK_Pointer_Up: long
    XK_Pointer_Down: long
    XK_Pointer_UpLeft: long
    XK_Pointer_UpRight: long
    XK_Pointer_DownLeft: long
    XK_Pointer_DownRight: long
    XK_Pointer_Button_Dflt: long
    XK_Pointer_Button1: long
    XK_Pointer_Button2: long
    XK_Pointer_Button3: long
    XK_Pointer_Button4: long
    XK_Pointer_Button5: long
    XK_Pointer_DblClick_Dflt: long
    XK_Pointer_DblClick1: long
    XK_Pointer_DblClick2: long
    XK_Pointer_DblClick3: long
    XK_Pointer_DblClick4: long
    XK_Pointer_DblClick5: long
    XK_Pointer_Drag_Dflt: long
    XK_Pointer_Drag1: long
    XK_Pointer_Drag2: long
    XK_Pointer_Drag3: long
    XK_Pointer_Drag4: long
    XK_Pointer_Drag5: long
    XK_Pointer_EnableKeys: long
    XK_Pointer_Accelerate: long
    XK_Pointer_DfltBtnNext: long
    XK_Pointer_DfltBtnPrev: long
    XK_3270_Duplicate: long
    XK_3270_FieldMark: long
    XK_3270_Right2: long
    XK_3270_Left2: long
    XK_3270_BackTab: long
    XK_3270_EraseEOF: long
    XK_3270_EraseInput: long
    XK_3270_Reset: long
    XK_3270_Quit: long
    XK_3270_PA1: long
    XK_3270_PA2: long
    XK_3270_PA3: long
    XK_3270_Test: long
    XK_3270_Attn: long
    XK_3270_CursorBlink: long
    XK_3270_AltCursor: long
    XK_3270_KeyClick: long
    XK_3270_Jump: long
    XK_3270_Ident: long
    XK_3270_Rule: long
    XK_3270_Copy: long
    XK_3270_Play: long
    XK_3270_Setup: long
    XK_3270_Record: long
    XK_3270_ChangeScreen: long
    XK_3270_DeleteWord: long
    XK_3270_ExSelect: long
    XK_3270_CursorSelect: long
    XK_3270_PrintScreen: long
    XK_3270_Enter: long
    XK_space: long
    XK_exclam: long
    XK_quotedbl: long
    XK_numbersign: long
    XK_dollar: long
    XK_percent: long
    XK_ampersand: long
    XK_apostrophe: long
    XK_quoteright: long
    XK_parenleft: long
    XK_parenright: long
    XK_asterisk: long
    XK_plus: long
    XK_comma: long
    XK_minus: long
    XK_period: long
    XK_slash: long
    XK_0: long
    XK_1: long
    XK_2: long
    XK_3: long
    XK_4: long
    XK_5: long
    XK_6: long
    XK_7: long
    XK_8: long
    XK_9: long
    XK_colon: long
    XK_semicolon: long
    XK_less: long
    XK_equal: long
    XK_greater: long
    XK_question: long
    XK_at: long
    XK_A: long
    XK_B: long
    XK_C: long
    XK_D: long
    XK_E: long
    XK_F: long
    XK_G: long
    XK_H: long
    XK_I: long
    XK_J: long
    XK_K: long
    XK_L: long
    XK_M: long
    XK_N: long
    XK_O: long
    XK_P: long
    XK_Q: long
    XK_R: long
    XK_S: long
    XK_T: long
    XK_U: long
    XK_V: long
    XK_W: long
    XK_X: long
    XK_Y: long
    XK_Z: long
    XK_bracketleft: long
    XK_backslash: long
    XK_bracketright: long
    XK_asciicircum: long
    XK_underscore: long
    XK_grave: long
    XK_quoteleft: long
    XK_a: long
    XK_b: long
    XK_c: long
    XK_d: long
    XK_e: long
    XK_f: long
    XK_g: long
    XK_h: long
    XK_i: long
    XK_j: long
    XK_k: long
    XK_l: long
    XK_m: long
    XK_n: long
    XK_o: long
    XK_p: long
    XK_q: long
    XK_r: long
    XK_s: long
    XK_t: long
    XK_u: long
    XK_v: long
    XK_w: long
    XK_x: long
    XK_y: long
    XK_z: long
    XK_braceleft: long
    XK_bar: long
    XK_braceright: long
    XK_asciitilde: long
    XK_nobreakspace: long
    XK_exclamdown: long
    XK_cent: long
    XK_sterling: long
    XK_currency: long
    XK_yen: long
    XK_brokenbar: long
    XK_section: long
    XK_diaeresis: long
    XK_copyright: long
    XK_ordfeminine: long
    XK_guillemotleft: long
    XK_notsign: long
    XK_hyphen: long
    XK_registered: long
    XK_macron: long
    XK_degree: long
    XK_plusminus: long
    XK_twosuperior: long
    XK_threesuperior: long
    XK_acute: long
    XK_mu: long
    XK_paragraph: long
    XK_periodcentered: long
    XK_cedilla: long
    XK_onesuperior: long
    XK_masculine: long
    XK_guillemotright: long
    XK_onequarter: long
    XK_onehalf: long
    XK_threequarters: long
    XK_questiondown: long
    XK_Agrave: long
    XK_Aacute: long
    XK_Acircumflex: long
    XK_Atilde: long
    XK_Adiaeresis: long
    XK_Aring: long
    XK_AE: long
    XK_Ccedilla: long
    XK_Egrave: long
    XK_Eacute: long
    XK_Ecircumflex: long
    XK_Ediaeresis: long
    XK_Igrave: long
    XK_Iacute: long
    XK_Icircumflex: long
    XK_Idiaeresis: long
    XK_ETH: long
    XK_Eth: long
    XK_Ntilde: long
    XK_Ograve: long
    XK_Oacute: long
    XK_Ocircumflex: long
    XK_Otilde: long
    XK_Odiaeresis: long
    XK_multiply: long
    XK_Ooblique: long
    XK_Ugrave: long
    XK_Uacute: long
    XK_Ucircumflex: long
    XK_Udiaeresis: long
    XK_Yacute: long
    XK_THORN: long
    XK_Thorn: long
    XK_ssharp: long
    XK_agrave: long
    XK_aacute: long
    XK_acircumflex: long
    XK_atilde: long
    XK_adiaeresis: long
    XK_aring: long
    XK_ae: long
    XK_ccedilla: long
    XK_egrave: long
    XK_eacute: long
    XK_ecircumflex: long
    XK_ediaeresis: long
    XK_igrave: long
    XK_iacute: long
    XK_icircumflex: long
    XK_idiaeresis: long
    XK_eth: long
    XK_ntilde: long
    XK_ograve: long
    XK_oacute: long
    XK_ocircumflex: long
    XK_otilde: long
    XK_odiaeresis: long
    XK_division: long
    XK_oslash: long
    XK_ugrave: long
    XK_uacute: long
    XK_ucircumflex: long
    XK_udiaeresis: long
    XK_yacute: long
    XK_thorn: long
    XK_ydiaeresis: long
    XK_Aogonek: long
    XK_breve: long
    XK_Lstroke: long
    XK_Lcaron: long
    XK_Sacute: long
    XK_Scaron: long
    XK_Scedilla: long
    XK_Tcaron: long
    XK_Zacute: long
    XK_Zcaron: long
    XK_Zabovedot: long
    XK_aogonek: long
    XK_ogonek: long
    XK_lstroke: long
    XK_lcaron: long
    XK_sacute: long
    XK_caron: long
    XK_scaron: long
    XK_scedilla: long
    XK_tcaron: long
    XK_zacute: long
    XK_doubleacute: long
    XK_zcaron: long
    XK_zabovedot: long
    XK_Racute: long
    XK_Abreve: long
    XK_Lacute: long
    XK_Cacute: long
    XK_Ccaron: long
    XK_Eogonek: long
    XK_Ecaron: long
    XK_Dcaron: long
    XK_Dstroke: long
    XK_Nacute: long
    XK_Ncaron: long
    XK_Odoubleacute: long
    XK_Rcaron: long
    XK_Uring: long
    XK_Udoubleacute: long
    XK_Tcedilla: long
    XK_racute: long
    XK_abreve: long
    XK_lacute: long
    XK_cacute: long
    XK_ccaron: long
    XK_eogonek: long
    XK_ecaron: long
    XK_dcaron: long
    XK_dstroke: long
    XK_nacute: long
    XK_ncaron: long
    XK_odoubleacute: long
    XK_udoubleacute: long
    XK_rcaron: long
    XK_uring: long
    XK_tcedilla: long
    XK_abovedot: long
    XK_Hstroke: long
    XK_Hcircumflex: long
    XK_Iabovedot: long
    XK_Gbreve: long
    XK_Jcircumflex: long
    XK_hstroke: long
    XK_hcircumflex: long
    XK_idotless: long
    XK_gbreve: long
    XK_jcircumflex: long
    XK_Cabovedot: long
    XK_Ccircumflex: long
    XK_Gabovedot: long
    XK_Gcircumflex: long
    XK_Ubreve: long
    XK_Scircumflex: long
    XK_cabovedot: long
    XK_ccircumflex: long
    XK_gabovedot: long
    XK_gcircumflex: long
    XK_ubreve: long
    XK_scircumflex: long
    XK_kra: long
    XK_kappa: long
    XK_Rcedilla: long
    XK_Itilde: long
    XK_Lcedilla: long
    XK_Emacron: long
    XK_Gcedilla: long
    XK_Tslash: long
    XK_rcedilla: long
    XK_itilde: long
    XK_lcedilla: long
    XK_emacron: long
    XK_gcedilla: long
    XK_tslash: long
    XK_ENG: long
    XK_eng: long
    XK_Amacron: long
    XK_Iogonek: long
    XK_Eabovedot: long
    XK_Imacron: long
    XK_Ncedilla: long
    XK_Omacron: long
    XK_Kcedilla: long
    XK_Uogonek: long
    XK_Utilde: long
    XK_Umacron: long
    XK_amacron: long
    XK_iogonek: long
    XK_eabovedot: long
    XK_imacron: long
    XK_ncedilla: long
    XK_omacron: long
    XK_kcedilla: long
    XK_uogonek: long
    XK_utilde: long
    XK_umacron: long
    XK_OE: long
    XK_oe: long
    XK_Ydiaeresis: long
    XK_overline: long
    XK_kana_fullstop: long
    XK_kana_openingbracket: long
    XK_kana_closingbracket: long
    XK_kana_comma: long
    XK_kana_conjunctive: long
    XK_kana_middledot: long
    XK_kana_WO: long
    XK_kana_a: long
    XK_kana_i: long
    XK_kana_u: long
    XK_kana_e: long
    XK_kana_o: long
    XK_kana_ya: long
    XK_kana_yu: long
    XK_kana_yo: long
    XK_kana_tsu: long
    XK_kana_tu: long
    XK_prolongedsound: long
    XK_kana_A: long
    XK_kana_I: long
    XK_kana_U: long
    XK_kana_E: long
    XK_kana_O: long
    XK_kana_KA: long
    XK_kana_KI: long
    XK_kana_KU: long
    XK_kana_KE: long
    XK_kana_KO: long
    XK_kana_SA: long
    XK_kana_SHI: long
    XK_kana_SU: long
    XK_kana_SE: long
    XK_kana_SO: long
    XK_kana_TA: long
    XK_kana_CHI: long
    XK_kana_TI: long
    XK_kana_TSU: long
    XK_kana_TU: long
    XK_kana_TE: long
    XK_kana_TO: long
    XK_kana_NA: long
    XK_kana_NI: long
    XK_kana_NU: long
    XK_kana_NE: long
    XK_kana_NO: long
    XK_kana_HA: long
    XK_kana_HI: long
    XK_kana_FU: long
    XK_kana_HU: long
    XK_kana_HE: long
    XK_kana_HO: long
    XK_kana_MA: long
    XK_kana_MI: long
    XK_kana_MU: long
    XK_kana_ME: long
    XK_kana_MO: long
    XK_kana_YA: long
    XK_kana_YU: long
    XK_kana_YO: long
    XK_kana_RA: long
    XK_kana_RI: long
    XK_kana_RU: long
    XK_kana_RE: long
    XK_kana_RO: long
    XK_kana_WA: long
    XK_kana_N: long
    XK_voicedsound: long
    XK_semivoicedsound: long
    XK_kana_switch: long
    XK_Arabic_comma: long
    XK_Arabic_semicolon: long
    XK_Arabic_question_mark: long
    XK_Arabic_hamza: long
    XK_Arabic_maddaonalef: long
    XK_Arabic_hamzaonalef: long
    XK_Arabic_hamzaonwaw: long
    XK_Arabic_hamzaunderalef: long
    XK_Arabic_hamzaonyeh: long
    XK_Arabic_alef: long
    XK_Arabic_beh: long
    XK_Arabic_tehmarbuta: long
    XK_Arabic_teh: long
    XK_Arabic_theh: long
    XK_Arabic_jeem: long
    XK_Arabic_hah: long
    XK_Arabic_khah: long
    XK_Arabic_dal: long
    XK_Arabic_thal: long
    XK_Arabic_ra: long
    XK_Arabic_zain: long
    XK_Arabic_seen: long
    XK_Arabic_sheen: long
    XK_Arabic_sad: long
    XK_Arabic_dad: long
    XK_Arabic_tah: long
    XK_Arabic_zah: long
    XK_Arabic_ain: long
    XK_Arabic_ghain: long
    XK_Arabic_tatweel: long
    XK_Arabic_feh: long
    XK_Arabic_qaf: long
    XK_Arabic_kaf: long
    XK_Arabic_lam: long
    XK_Arabic_meem: long
    XK_Arabic_noon: long
    XK_Arabic_ha: long
    XK_Arabic_heh: long
    XK_Arabic_waw: long
    XK_Arabic_alefmaksura: long
    XK_Arabic_yeh: long
    XK_Arabic_fathatan: long
    XK_Arabic_dammatan: long
    XK_Arabic_kasratan: long
    XK_Arabic_fatha: long
    XK_Arabic_damma: long
    XK_Arabic_kasra: long
    XK_Arabic_shadda: long
    XK_Arabic_sukun: long
    XK_Arabic_switch: long
    XK_Serbian_dje: long
    XK_Macedonia_gje: long
    XK_Cyrillic_io: long
    XK_Ukrainian_ie: long
    XK_Ukranian_je: long
    XK_Macedonia_dse: long
    XK_Ukrainian_i: long
    XK_Ukranian_i: long
    XK_Ukrainian_yi: long
    XK_Ukranian_yi: long
    XK_Cyrillic_je: long
    XK_Serbian_je: long
    XK_Cyrillic_lje: long
    XK_Serbian_lje: long
    XK_Cyrillic_nje: long
    XK_Serbian_nje: long
    XK_Serbian_tshe: long
    XK_Macedonia_kje: long
    XK_Byelorussian_shortu: long
    XK_Cyrillic_dzhe: long
    XK_Serbian_dze: long
    XK_numerosign: long
    XK_Serbian_DJE: long
    XK_Macedonia_GJE: long
    XK_Cyrillic_IO: long
    XK_Ukrainian_IE: long
    XK_Ukranian_JE: long
    XK_Macedonia_DSE: long
    XK_Ukrainian_I: long
    XK_Ukranian_I: long
    XK_Ukrainian_YI: long
    XK_Ukranian_YI: long
    XK_Cyrillic_JE: long
    XK_Serbian_JE: long
    XK_Cyrillic_LJE: long
    XK_Serbian_LJE: long
    XK_Cyrillic_NJE: long
    XK_Serbian_NJE: long
    XK_Serbian_TSHE: long
    XK_Macedonia_KJE: long
    XK_Byelorussian_SHORTU: long
    XK_Cyrillic_DZHE: long
    XK_Serbian_DZE: long
    XK_Cyrillic_yu: long
    XK_Cyrillic_a: long
    XK_Cyrillic_be: long
    XK_Cyrillic_tse: long
    XK_Cyrillic_de: long
    XK_Cyrillic_ie: long
    XK_Cyrillic_ef: long
    XK_Cyrillic_ghe: long
    XK_Cyrillic_ha: long
    XK_Cyrillic_i: long
    XK_Cyrillic_shorti: long
    XK_Cyrillic_ka: long
    XK_Cyrillic_el: long
    XK_Cyrillic_em: long
    XK_Cyrillic_en: long
    XK_Cyrillic_o: long
    XK_Cyrillic_pe: long
    XK_Cyrillic_ya: long
    XK_Cyrillic_er: long
    XK_Cyrillic_es: long
    XK_Cyrillic_te: long
    XK_Cyrillic_u: long
    XK_Cyrillic_zhe: long
    XK_Cyrillic_ve: long
    XK_Cyrillic_softsign: long
    XK_Cyrillic_yeru: long
    XK_Cyrillic_ze: long
    XK_Cyrillic_sha: long
    XK_Cyrillic_e: long
    XK_Cyrillic_shcha: long
    XK_Cyrillic_che: long
    XK_Cyrillic_hardsign: long
    XK_Cyrillic_YU: long
    XK_Cyrillic_A: long
    XK_Cyrillic_BE: long
    XK_Cyrillic_TSE: long
    XK_Cyrillic_DE: long
    XK_Cyrillic_IE: long
    XK_Cyrillic_EF: long
    XK_Cyrillic_GHE: long
    XK_Cyrillic_HA: long
    XK_Cyrillic_I: long
    XK_Cyrillic_SHORTI: long
    XK_Cyrillic_KA: long
    XK_Cyrillic_EL: long
    XK_Cyrillic_EM: long
    XK_Cyrillic_EN: long
    XK_Cyrillic_O: long
    XK_Cyrillic_PE: long
    XK_Cyrillic_YA: long
    XK_Cyrillic_ER: long
    XK_Cyrillic_ES: long
    XK_Cyrillic_TE: long
    XK_Cyrillic_U: long
    XK_Cyrillic_ZHE: long
    XK_Cyrillic_VE: long
    XK_Cyrillic_SOFTSIGN: long
    XK_Cyrillic_YERU: long
    XK_Cyrillic_ZE: long
    XK_Cyrillic_SHA: long
    XK_Cyrillic_E: long
    XK_Cyrillic_SHCHA: long
    XK_Cyrillic_CHE: long
    XK_Cyrillic_HARDSIGN: long
    XK_Greek_ALPHAaccent: long
    XK_Greek_EPSILONaccent: long
    XK_Greek_ETAaccent: long
    XK_Greek_IOTAaccent: long
    XK_Greek_IOTAdiaeresis: long
    XK_Greek_OMICRONaccent: long
    XK_Greek_UPSILONaccent: long
    XK_Greek_UPSILONdieresis: long
    XK_Greek_OMEGAaccent: long
    XK_Greek_accentdieresis: long
    XK_Greek_horizbar: long
    XK_Greek_alphaaccent: long
    XK_Greek_epsilonaccent: long
    XK_Greek_etaaccent: long
    XK_Greek_iotaaccent: long
    XK_Greek_iotadieresis: long
    XK_Greek_iotaaccentdieresis: long
    XK_Greek_omicronaccent: long
    XK_Greek_upsilonaccent: long
    XK_Greek_upsilondieresis: long
    XK_Greek_upsilonaccentdieresis: long
    XK_Greek_omegaaccent: long
    XK_Greek_ALPHA: long
    XK_Greek_BETA: long
    XK_Greek_GAMMA: long
    XK_Greek_DELTA: long
    XK_Greek_EPSILON: long
    XK_Greek_ZETA: long
    XK_Greek_ETA: long
    XK_Greek_THETA: long
    XK_Greek_IOTA: long
    XK_Greek_KAPPA: long
    XK_Greek_LAMDA: long
    XK_Greek_LAMBDA: long
    XK_Greek_MU: long
    XK_Greek_NU: long
    XK_Greek_XI: long
    XK_Greek_OMICRON: long
    XK_Greek_PI: long
    XK_Greek_RHO: long
    XK_Greek_SIGMA: long
    XK_Greek_TAU: long
    XK_Greek_UPSILON: long
    XK_Greek_PHI: long
    XK_Greek_CHI: long
    XK_Greek_PSI: long
    XK_Greek_OMEGA: long
    XK_Greek_alpha: long
    XK_Greek_beta: long
    XK_Greek_gamma: long
    XK_Greek_delta: long
    XK_Greek_epsilon: long
    XK_Greek_zeta: long
    XK_Greek_eta: long
    XK_Greek_theta: long
    XK_Greek_iota: long
    XK_Greek_kappa: long
    XK_Greek_lamda: long
    XK_Greek_lambda: long
    XK_Greek_mu: long
    XK_Greek_nu: long
    XK_Greek_xi: long
    XK_Greek_omicron: long
    XK_Greek_pi: long
    XK_Greek_rho: long
    XK_Greek_sigma: long
    XK_Greek_finalsmallsigma: long
    XK_Greek_tau: long
    XK_Greek_upsilon: long
    XK_Greek_phi: long
    XK_Greek_chi: long
    XK_Greek_psi: long
    XK_Greek_omega: long
    XK_Greek_switch: long
    XK_leftradical: long
    XK_topleftradical: long
    XK_horizconnector: long
    XK_topintegral: long
    XK_botintegral: long
    XK_vertconnector: long
    XK_topleftsqbracket: long
    XK_botleftsqbracket: long
    XK_toprightsqbracket: long
    XK_botrightsqbracket: long
    XK_topleftparens: long
    XK_botleftparens: long
    XK_toprightparens: long
    XK_botrightparens: long
    XK_leftmiddlecurlybrace: long
    XK_rightmiddlecurlybrace: long
    XK_topleftsummation: long
    XK_botleftsummation: long
    XK_topvertsummationconnector: long
    XK_botvertsummationconnector: long
    XK_toprightsummation: long
    XK_botrightsummation: long
    XK_rightmiddlesummation: long
    XK_lessthanequal: long
    XK_notequal: long
    XK_greaterthanequal: long
    XK_integral: long
    XK_therefore: long
    XK_variation: long
    XK_infinity: long
    XK_nabla: long
    XK_approximate: long
    XK_similarequal: long
    XK_ifonlyif: long
    XK_implies: long
    XK_identical: long
    XK_radical: long
    XK_includedin: long
    XK_includes: long
    XK_intersection: long
    XK_union: long
    XK_logicaland: long
    XK_logicalor: long
    XK_partialderivative: long
    XK_function: long
    XK_leftarrow: long
    XK_uparrow: long
    XK_rightarrow: long
    XK_downarrow: long
    XK_blank: long
    XK_soliddiamond: long
    XK_checkerboard: long
    XK_ht: long
    XK_ff: long
    XK_cr: long
    XK_lf: long
    XK_nl: long
    XK_vt: long
    XK_lowrightcorner: long
    XK_uprightcorner: long
    XK_upleftcorner: long
    XK_lowleftcorner: long
    XK_crossinglines: long
    XK_horizlinescan1: long
    XK_horizlinescan3: long
    XK_horizlinescan5: long
    XK_horizlinescan7: long
    XK_horizlinescan9: long
    XK_leftt: long
    XK_rightt: long
    XK_bott: long
    XK_topt: long
    XK_vertbar: long
    XK_emspace: long
    XK_enspace: long
    XK_em3space: long
    XK_em4space: long
    XK_digitspace: long
    XK_punctspace: long
    XK_thinspace: long
    XK_hairspace: long
    XK_emdash: long
    XK_endash: long
    XK_signifblank: long
    XK_ellipsis: long
    XK_doubbaselinedot: long
    XK_onethird: long
    XK_twothirds: long
    XK_onefifth: long
    XK_twofifths: long
    XK_threefifths: long
    XK_fourfifths: long
    XK_onesixth: long
    XK_fivesixths: long
    XK_careof: long
    XK_figdash: long
    XK_leftanglebracket: long
    XK_decimalpoint: long
    XK_rightanglebracket: long
    XK_marker: long
    XK_oneeighth: long
    XK_threeeighths: long
    XK_fiveeighths: long
    XK_seveneighths: long
    XK_trademark: long
    XK_signaturemark: long
    XK_trademarkincircle: long
    XK_leftopentriangle: long
    XK_rightopentriangle: long
    XK_emopencircle: long
    XK_emopenrectangle: long
    XK_leftsinglequotemark: long
    XK_rightsinglequotemark: long
    XK_leftdoublequotemark: long
    XK_rightdoublequotemark: long
    XK_prescription: long
    XK_minutes: long
    XK_seconds: long
    XK_latincross: long
    XK_hexagram: long
    XK_filledrectbullet: long
    XK_filledlefttribullet: long
    XK_filledrighttribullet: long
    XK_emfilledcircle: long
    XK_emfilledrect: long
    XK_enopencircbullet: long
    XK_enopensquarebullet: long
    XK_openrectbullet: long
    XK_opentribulletup: long
    XK_opentribulletdown: long
    XK_openstar: long
    XK_enfilledcircbullet: long
    XK_enfilledsqbullet: long
    XK_filledtribulletup: long
    XK_filledtribulletdown: long
    XK_leftpointer: long
    XK_rightpointer: long
    XK_club: long
    XK_diamond: long
    XK_heart: long
    XK_maltesecross: long
    XK_dagger: long
    XK_doubledagger: long
    XK_checkmark: long
    XK_ballotcross: long
    XK_musicalsharp: long
    XK_musicalflat: long
    XK_malesymbol: long
    XK_femalesymbol: long
    XK_telephone: long
    XK_telephonerecorder: long
    XK_phonographcopyright: long
    XK_caret: long
    XK_singlelowquotemark: long
    XK_doublelowquotemark: long
    XK_cursor: long
    XK_leftcaret: long
    XK_rightcaret: long
    XK_downcaret: long
    XK_upcaret: long
    XK_overbar: long
    XK_downtack: long
    XK_upshoe: long
    XK_downstile: long
    XK_underbar: long
    XK_jot: long
    XK_quad: long
    XK_uptack: long
    XK_circle: long
    XK_upstile: long
    XK_downshoe: long
    XK_rightshoe: long
    XK_leftshoe: long
    XK_lefttack: long
    XK_righttack: long
    XK_hebrew_doublelowline: long
    XK_hebrew_aleph: long
    XK_hebrew_bet: long
    XK_hebrew_beth: long
    XK_hebrew_gimel: long
    XK_hebrew_gimmel: long
    XK_hebrew_dalet: long
    XK_hebrew_daleth: long
    XK_hebrew_he: long
    XK_hebrew_waw: long
    XK_hebrew_zain: long
    XK_hebrew_zayin: long
    XK_hebrew_chet: long
    XK_hebrew_het: long
    XK_hebrew_tet: long
    XK_hebrew_teth: long
    XK_hebrew_yod: long
    XK_hebrew_finalkaph: long
    XK_hebrew_kaph: long
    XK_hebrew_lamed: long
    XK_hebrew_finalmem: long
    XK_hebrew_mem: long
    XK_hebrew_finalnun: long
    XK_hebrew_nun: long
    XK_hebrew_samech: long
    XK_hebrew_samekh: long
    XK_hebrew_ayin: long
    XK_hebrew_finalpe: long
    XK_hebrew_pe: long
    XK_hebrew_finalzade: long
    XK_hebrew_finalzadi: long
    XK_hebrew_zade: long
    XK_hebrew_zadi: long
    XK_hebrew_qoph: long
    XK_hebrew_kuf: long
    XK_hebrew_resh: long
    XK_hebrew_shin: long
    XK_hebrew_taw: long
    XK_hebrew_taf: long
    XK_Hebrew_switch: long
    XK_Thai_kokai: long
    XK_Thai_khokhai: long
    XK_Thai_khokhuat: long
    XK_Thai_khokhwai: long
    XK_Thai_khokhon: long
    XK_Thai_khorakhang: long
    XK_Thai_ngongu: long
    XK_Thai_chochan: long
    XK_Thai_choching: long
    XK_Thai_chochang: long
    XK_Thai_soso: long
    XK_Thai_chochoe: long
    XK_Thai_yoying: long
    XK_Thai_dochada: long
    XK_Thai_topatak: long
    XK_Thai_thothan: long
    XK_Thai_thonangmontho: long
    XK_Thai_thophuthao: long
    XK_Thai_nonen: long
    XK_Thai_dodek: long
    XK_Thai_totao: long
    XK_Thai_thothung: long
    XK_Thai_thothahan: long
    XK_Thai_thothong: long
    XK_Thai_nonu: long
    XK_Thai_bobaimai: long
    XK_Thai_popla: long
    XK_Thai_phophung: long
    XK_Thai_fofa: long
    XK_Thai_phophan: long
    XK_Thai_fofan: long
    XK_Thai_phosamphao: long
    XK_Thai_moma: long
    XK_Thai_yoyak: long
    XK_Thai_rorua: long
    XK_Thai_ru: long
    XK_Thai_loling: long
    XK_Thai_lu: long
    XK_Thai_wowaen: long
    XK_Thai_sosala: long
    XK_Thai_sorusi: long
    XK_Thai_sosua: long
    XK_Thai_hohip: long
    XK_Thai_lochula: long
    XK_Thai_oang: long
    XK_Thai_honokhuk: long
    XK_Thai_paiyannoi: long
    XK_Thai_saraa: long
    XK_Thai_maihanakat: long
    XK_Thai_saraaa: long
    XK_Thai_saraam: long
    XK_Thai_sarai: long
    XK_Thai_saraii: long
    XK_Thai_saraue: long
    XK_Thai_sarauee: long
    XK_Thai_sarau: long
    XK_Thai_sarauu: long
    XK_Thai_phinthu: long
    XK_Thai_maihanakat_maitho: long
    XK_Thai_baht: long
    XK_Thai_sarae: long
    XK_Thai_saraae: long
    XK_Thai_sarao: long
    XK_Thai_saraaimaimuan: long
    XK_Thai_saraaimaimalai: long
    XK_Thai_lakkhangyao: long
    XK_Thai_maiyamok: long
    XK_Thai_maitaikhu: long
    XK_Thai_maiek: long
    XK_Thai_maitho: long
    XK_Thai_maitri: long
    XK_Thai_maichattawa: long
    XK_Thai_thanthakhat: long
    XK_Thai_nikhahit: long
    XK_Thai_leksun: long
    XK_Thai_leknung: long
    XK_Thai_leksong: long
    XK_Thai_leksam: long
    XK_Thai_leksi: long
    XK_Thai_lekha: long
    XK_Thai_lekhok: long
    XK_Thai_lekchet: long
    XK_Thai_lekpaet: long
    XK_Thai_lekkao: long
    XK_Hangul: long
    XK_Hangul_Start: long
    XK_Hangul_End: long
    XK_Hangul_Hanja: long
    XK_Hangul_Jamo: long
    XK_Hangul_Romaja: long
    XK_Hangul_Codeinput: long
    XK_Hangul_Jeonja: long
    XK_Hangul_Banja: long
    XK_Hangul_PreHanja: long
    XK_Hangul_PostHanja: long
    XK_Hangul_SingleCandidate: long
    XK_Hangul_MultipleCandidate: long
    XK_Hangul_PreviousCandidate: long
    XK_Hangul_Special: long
    XK_Hangul_switch: long
    XK_Hangul_Kiyeog: long
    XK_Hangul_SsangKiyeog: long
    XK_Hangul_KiyeogSios: long
    XK_Hangul_Nieun: long
    XK_Hangul_NieunJieuj: long
    XK_Hangul_NieunHieuh: long
    XK_Hangul_Dikeud: long
    XK_Hangul_SsangDikeud: long
    XK_Hangul_Rieul: long
    XK_Hangul_RieulKiyeog: long
    XK_Hangul_RieulMieum: long
    XK_Hangul_RieulPieub: long
    XK_Hangul_RieulSios: long
    XK_Hangul_RieulTieut: long
    XK_Hangul_RieulPhieuf: long
    XK_Hangul_RieulHieuh: long
    XK_Hangul_Mieum: long
    XK_Hangul_Pieub: long
    XK_Hangul_SsangPieub: long
    XK_Hangul_PieubSios: long
    XK_Hangul_Sios: long
    XK_Hangul_SsangSios: long
    XK_Hangul_Ieung: long
    XK_Hangul_Jieuj: long
    XK_Hangul_SsangJieuj: long
    XK_Hangul_Cieuc: long
    XK_Hangul_Khieuq: long
    XK_Hangul_Tieut: long
    XK_Hangul_Phieuf: long
    XK_Hangul_Hieuh: long
    XK_Hangul_A: long
    XK_Hangul_AE: long
    XK_Hangul_YA: long
    XK_Hangul_YAE: long
    XK_Hangul_EO: long
    XK_Hangul_E: long
    XK_Hangul_YEO: long
    XK_Hangul_YE: long
    XK_Hangul_O: long
    XK_Hangul_WA: long
    XK_Hangul_WAE: long
    XK_Hangul_OE: long
    XK_Hangul_YO: long
    XK_Hangul_U: long
    XK_Hangul_WEO: long
    XK_Hangul_WE: long
    XK_Hangul_WI: long
    XK_Hangul_YU: long
    XK_Hangul_EU: long
    XK_Hangul_YI: long
    XK_Hangul_I: long
    XK_Hangul_J_Kiyeog: long
    XK_Hangul_J_SsangKiyeog: long
    XK_Hangul_J_KiyeogSios: long
    XK_Hangul_J_Nieun: long
    XK_Hangul_J_NieunJieuj: long
    XK_Hangul_J_NieunHieuh: long
    XK_Hangul_J_Dikeud: long
    XK_Hangul_J_Rieul: long
    XK_Hangul_J_RieulKiyeog: long
    XK_Hangul_J_RieulMieum: long
    XK_Hangul_J_RieulPieub: long
    XK_Hangul_J_RieulSios: long
    XK_Hangul_J_RieulTieut: long
    XK_Hangul_J_RieulPhieuf: long
    XK_Hangul_J_RieulHieuh: long
    XK_Hangul_J_Mieum: long
    XK_Hangul_J_Pieub: long
    XK_Hangul_J_PieubSios: long
    XK_Hangul_J_Sios: long
    XK_Hangul_J_SsangSios: long
    XK_Hangul_J_Ieung: long
    XK_Hangul_J_Jieuj: long
    XK_Hangul_J_Cieuc: long
    XK_Hangul_J_Khieuq: long
    XK_Hangul_J_Tieut: long
    XK_Hangul_J_Phieuf: long
    XK_Hangul_J_Hieuh: long
    XK_Hangul_RieulYeorinHieuh: long
    XK_Hangul_SunkyeongeumMieum: long
    XK_Hangul_SunkyeongeumPieub: long
    XK_Hangul_PanSios: long
    XK_Hangul_KkogjiDalrinIeung: long
    XK_Hangul_SunkyeongeumPhieuf: long
    XK_Hangul_YeorinHieuh: long
    XK_Hangul_AraeA: long
    XK_Hangul_AraeAE: long
    XK_Hangul_J_PanSios: long
    XK_Hangul_J_KkogjiDalrinIeung: long
    XK_Hangul_J_YeorinHieuh: long
    XK_Korean_Won: long
    XK_EcuSign: long
    XK_ColonSign: long
    XK_CruzeiroSign: long
    XK_FFrancSign: long
    XK_LiraSign: long
    XK_MillSign: long
    XK_NairaSign: long
    XK_PesetaSign: long
    XK_RupeeSign: long
    XK_WonSign: long
    XK_NewSheqelSign: long
    XK_DongSign: long
    XK_EuroSign: long
    apXK_Copy: long
    apXK_Cut: long
    apXK_Paste: long
    DXK_ring_accent: long
    DXK_circumflex_accent: long
    DXK_cedilla_accent: long
    DXK_acute_accent: long
    DXK_grave_accent: long
    DXK_tilde: long
    DXK_diaeresis: long
    hpXK_ClearLine: long
    hpXK_InsertLine: long
    hpXK_DeleteLine: long
    hpXK_InsertChar: long
    hpXK_DeleteChar: long
    hpXK_BackTab: long
    hpXK_KP_BackTab: long
    hpXK_Modelock1: long
    hpXK_Modelock2: long
    hpXK_Reset: long
    hpXK_System: long
    hpXK_User: long
    hpXK_mute_acute: long
    hpXK_mute_grave: long
    hpXK_mute_asciicircum: long
    hpXK_mute_diaeresis: long
    hpXK_mute_asciitilde: long
    hpXK_lira: long
    hpXK_guilder: long
    hpXK_Ydiaeresis: long
    hpXK_IO: long
    hpXK_longminus: long
    hpXK_block: long
    osfXK_Copy: long
    osfXK_Cut: long
    osfXK_Paste: long
    osfXK_BackTab: long
    osfXK_BackSpace: long
    osfXK_Clear: long
    osfXK_Escape: long
    osfXK_AddMode: long
    osfXK_PrimaryPaste: long
    osfXK_QuickPaste: long
    osfXK_PageLeft: long
    osfXK_PageUp: long
    osfXK_PageDown: long
    osfXK_PageRight: long
    osfXK_Activate: long
    osfXK_MenuBar: long
    osfXK_Left: long
    osfXK_Up: long
    osfXK_Right: long
    osfXK_Down: long
    osfXK_EndLine: long
    osfXK_BeginLine: long
    osfXK_EndData: long
    osfXK_BeginData: long
    osfXK_PrevMenu: long
    osfXK_NextMenu: long
    osfXK_PrevField: long
    osfXK_NextField: long
    osfXK_Select: long
    osfXK_Insert: long
    osfXK_Undo: long
    osfXK_Menu: long
    osfXK_Cancel: long
    osfXK_Help: long
    osfXK_Delete: long
    osfXK_Prior: long
    osfXK_Next: long
    SunXK_FA_Grave: long
    SunXK_FA_Circum: long
    SunXK_FA_Tilde: long
    SunXK_FA_Acute: long
    SunXK_FA_Diaeresis: long
    SunXK_FA_Cedilla: long
    SunXK_F36: long
    SunXK_F37: long
    SunXK_Sys_Req: long
    SunXK_Print_Screen: long
    SunXK_Compose: long
    SunXK_AltGraph: long
    SunXK_PageUp: long
    SunXK_PageDown: long
    SunXK_Undo: long
    SunXK_Again: long
    SunXK_Find: long
    SunXK_Stop: long
    SunXK_Props: long
    SunXK_Front: long
    SunXK_Copy: long
    SunXK_Open: long
    SunXK_Paste: long
    SunXK_Cut: long
    SunXK_PowerSwitch: long
    SunXK_AudioLowerVolume: long
    SunXK_AudioMute: long
    SunXK_AudioRaiseVolume: long
    SunXK_VideoDegauss: long
    SunXK_VideoLowerBrightness: long
    SunXK_VideoRaiseBrightness: long
    SunXK_PowerSwitchShift: long
}

        }
    }
}