declare namespace sun {
    namespace security {
        namespace krb5 {
            namespace internal {
                class Krb5 {
                    public static DEFAULT_ALLOWABLE_CLOCKSKEW: int
                    public static DEFAULT_MINIMUM_LIFETIME: int
                    public static DEFAULT_MAXIMUM_RENEWABLE_LIFETIME: int
                    public static DEFAULT_MAXIMUM_TICKET_LIFETIME: int
                    public static DEFAULT_FORWARDABLE_ALLOWED: boolean
                    public static DEFAULT_PROXIABLE_ALLOWED: boolean
                    public static DEFAULT_POSTDATE_ALLOWED: boolean
                    public static DEFAULT_RENEWABLE_ALLOWED: boolean
                    public static AP_EMPTY_ADDRESSES_ALLOWED: boolean
                    public static AP_OPTS_RESERVED: int
                    public static AP_OPTS_USE_SESSION_KEY: int
                    public static AP_OPTS_MUTUAL_REQUIRED: int
                    public static AP_OPTS_MAX: int
                    public static TKT_OPTS_RESERVED: int
                    public static TKT_OPTS_FORWARDABLE: int
                    public static TKT_OPTS_FORWARDED: int
                    public static TKT_OPTS_PROXIABLE: int
                    public static TKT_OPTS_PROXY: int
                    public static TKT_OPTS_MAY_POSTDATE: int
                    public static TKT_OPTS_POSTDATED: int
                    public static TKT_OPTS_INVALID: int
                    public static TKT_OPTS_RENEWABLE: int
                    public static TKT_OPTS_INITIAL: int
                    public static TKT_OPTS_PRE_AUTHENT: int
                    public static TKT_OPTS_HW_AUTHENT: int
                    public static TKT_OPTS_DELEGATE: int
                    public static TKT_OPTS_MAX: int
                    public static KDC_OPTS_MAX: int
                    public static KRB_FLAGS_MAX: int
                    public static LRTYPE_NONE: int
                    public static LRTYPE_TIME_OF_INITIAL_TGT: int
                    public static LRTYPE_TIME_OF_INITIAL_REQ: int
                    public static LRTYPE_TIME_OF_NEWEST_TGT: int
                    public static LRTYPE_TIME_OF_LAST_RENEWAL: int
                    public static LRTYPE_TIME_OF_LAST_REQ: int
                    public static ADDR_LEN_INET: int
                    public static ADDR_LEN_CHAOS: int
                    public static ADDR_LEN_OSI: int
                    public static ADDR_LEN_XNS: int
                    public static ADDR_LEN_APPLETALK: int
                    public static ADDR_LEN_DECNET: int
                    public static ADDRTYPE_UNIX: int
                    public static ADDRTYPE_INET: int
                    public static ADDRTYPE_IMPLINK: int
                    public static ADDRTYPE_PUP: int
                    public static ADDRTYPE_CHAOS: int
                    public static ADDRTYPE_XNS: int
                    public static ADDRTYPE_IPX: int
                    public static ADDRTYPE_ISO: int
                    public static ADDRTYPE_ECMA: int
                    public static ADDRTYPE_DATAKIT: int
                    public static ADDRTYPE_CCITT: int
                    public static ADDRTYPE_SNA: int
                    public static ADDRTYPE_DECNET: int
                    public static ADDRTYPE_DLI: int
                    public static ADDRTYPE_LAT: int
                    public static ADDRTYPE_HYLINK: int
                    public static ADDRTYPE_APPLETALK: int
                    public static ADDRTYPE_NETBIOS: int
                    public static ADDRTYPE_VOICEVIEW: int
                    public static ADDRTYPE_FIREFOX: int
                    public static ADDRTYPE_BAN: int
                    public static ADDRTYPE_ATM: int
                    public static ADDRTYPE_INET6: int
                    public static KDC_INET_DEFAULT_PORT: int
                    public static KDC_RETRY_LIMIT: int
                    public static KDC_DEFAULT_UDP_PREF_LIMIT: int
                    public static KDC_HARD_UDP_LIMIT: int
                    public static KEYTYPE_NULL: int
                    public static KEYTYPE_DES: int
                    public static KEYTYPE_DES3: int
                    public static KEYTYPE_AES: int
                    public static KEYTYPE_ARCFOUR_HMAC: int
                    public static PA_TGS_REQ: int
                    public static PA_ENC_TIMESTAMP: int
                    public static PA_PW_SALT: int
                    public static PA_ETYPE_INFO: int
                    public static PA_ETYPE_INFO2: int
                    public static PA_FOR_USER: int
                    public static OSF_DCE: int
                    public static SESAME: int
                    public static ATT_CHALLENGE_RESPONSE: int
                    public static DOMAIN_X500_COMPRESS: int
                    public static PVNO: int
                    public static AUTHNETICATOR_VNO: int
                    public static TICKET_VNO: int
                    public static KRB_AS_REQ: int
                    public static KRB_AS_REP: int
                    public static KRB_TGS_REQ: int
                    public static KRB_TGS_REP: int
                    public static KRB_AP_REQ: int
                    public static KRB_AP_REP: int
                    public static KRB_SAFE: int
                    public static KRB_PRIV: int
                    public static KRB_CRED: int
                    public static KRB_ERROR: int
                    public static KRB_TKT: int
                    public static KRB_AUTHENTICATOR: int
                    public static KRB_ENC_TKT_PART: int
                    public static KRB_ENC_AS_REP_PART: int
                    public static KRB_ENC_TGS_REP_PART: int
                    public static KRB_ENC_AP_REP_PART: int
                    public static KRB_ENC_KRB_PRIV_PART: int
                    public static KRB_ENC_KRB_CRED_PART: int
                    public static KDC_ERR_NONE: int
                    public static KDC_ERR_NAME_EXP: int
                    public static KDC_ERR_SERVICE_EXP: int
                    public static KDC_ERR_BAD_PVNO: int
                    public static KDC_ERR_C_OLD_MAST_KVNO: int
                    public static KDC_ERR_S_OLD_MAST_KVNO: int
                    public static KDC_ERR_C_PRINCIPAL_UNKNOWN: int
                    public static KDC_ERR_S_PRINCIPAL_UNKNOWN: int
                    public static KDC_ERR_PRINCIPAL_NOT_UNIQUE: int
                    public static KDC_ERR_NULL_KEY: int
                    public static KDC_ERR_CANNOT_POSTDATE: int
                    public static KDC_ERR_NEVER_VALID: int
                    public static KDC_ERR_POLICY: int
                    public static KDC_ERR_BADOPTION: int
                    public static KDC_ERR_ETYPE_NOSUPP: int
                    public static KDC_ERR_SUMTYPE_NOSUPP: int
                    public static KDC_ERR_PADATA_TYPE_NOSUPP: int
                    public static KDC_ERR_TRTYPE_NOSUPP: int
                    public static KDC_ERR_CLIENT_REVOKED: int
                    public static KDC_ERR_SERVICE_REVOKED: int
                    public static KDC_ERR_TGT_REVOKED: int
                    public static KDC_ERR_CLIENT_NOTYET: int
                    public static KDC_ERR_SERVICE_NOTYET: int
                    public static KDC_ERR_KEY_EXPIRED: int
                    public static KDC_ERR_PREAUTH_FAILED: int
                    public static KDC_ERR_PREAUTH_REQUIRED: int
                    public static KRB_AP_ERR_BAD_INTEGRITY: int
                    public static KRB_AP_ERR_TKT_EXPIRED: int
                    public static KRB_AP_ERR_TKT_NYV: int
                    public static KRB_AP_ERR_REPEAT: int
                    public static KRB_AP_ERR_NOT_US: int
                    public static KRB_AP_ERR_BADMATCH: int
                    public static KRB_AP_ERR_SKEW: int
                    public static KRB_AP_ERR_BADADDR: int
                    public static KRB_AP_ERR_BADVERSION: int
                    public static KRB_AP_ERR_MSG_TYPE: int
                    public static KRB_AP_ERR_MODIFIED: int
                    public static KRB_AP_ERR_BADORDER: int
                    public static KRB_AP_ERR_BADKEYVER: int
                    public static KRB_AP_ERR_NOKEY: int
                    public static KRB_AP_ERR_MUT_FAIL: int
                    public static KRB_AP_ERR_BADDIRECTION: int
                    public static KRB_AP_ERR_METHOD: int
                    public static KRB_AP_ERR_BADSEQ: int
                    public static KRB_AP_ERR_INAPP_CKSUM: int
                    public static KRB_ERR_RESPONSE_TOO_BIG: int
                    public static KRB_ERR_GENERIC: int
                    public static KRB_ERR_FIELD_TOOLONG: int
                    public static KRB_CRYPTO_NOT_SUPPORT: int
                    public static KRB_AP_ERR_NOREALM: int
                    public static KRB_AP_ERR_GEN_CRED: int
                    public static KRB_AP_ERR_REQ_OPTIONS: int
                    public static API_INVALID_ARG: int
                    public static BITSTRING_SIZE_INVALID: int
                    public static BITSTRING_INDEX_OUT_OF_BOUNDS: int
                    public static BITSTRING_BAD_LENGTH: int
                    public static REALM_ILLCHAR: int
                    public static REALM_NULL: int
                    public static ASN1_BAD_TIMEFORMAT: int
                    public static ASN1_MISSING_FIELD: int
                    public static ASN1_MISPLACED_FIELD: int
                    public static ASN1_TYPE_MISMATCH: int
                    public static ASN1_OVERFLOW: int
                    public static ASN1_OVERRUN: int
                    public static ASN1_BAD_ID: int
                    public static ASN1_BAD_LENGTH: int
                    public static ASN1_BAD_FORMAT: int
                    public static ASN1_PARSE_ERROR: int
                    public static ASN1_BAD_CLASS: int
                    public static ASN1_BAD_TYPE: int
                    public static ASN1_BAD_TAG: int
                    public static ASN1_UNSUPPORTED_TYPE: int
                    public static ASN1_CANNOT_ENCODE: int
                    public static DEBUG: boolean
                    public static hexDumper: sun.misc.HexDumpEncoder
                    public constructor()
                    public static getErrorMessage(arg0: int): string
                    public static class: java.lang.Class<any>
                }
            }
        }
    }
}