on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - v11

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "8.0.362+9"
          distribution: "temurin"
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm install
      - run: npm run build
      - working-directory: example
        run: |
          ../bin/tyrian install
          ../bin/tyrian build main.ts
          ../bin/tyrian run main.js
